### PR TITLE
Add SUSD Token

### PR DESCRIPTION
**Pull request by czhiqi**
Official announcement: 
https://www.facebook.com/STAR-Secured-Tangible-Asset-Reserves-107270137533909/
https://www.linkedin.com/company/30877164/

Project team background:

Chew Lih Ren, Chief Executive Officer

Linkedin Profile:
https://www.linkedin.com/in/chew-lih-ren-ab25ab84/

Lynn Heng, Chief Technology Officer
Linkedin Profile:
https://www.linkedin.com/in/lynn-heng

En Shen, Chief Finance Officer
Linkedin Profile:
https://www.linkedin.com/in/en-shen-lew-13512419b/

Media publications:
Facebook : https://www.facebook.com/STAR-Secure-Tangible-Asset-Reserve-107270137533909/?tn-str=k*F
LinkedIn :https://www.linkedin.com/company/starsc/
Telegram: https://t.me/Starsecure

Project basic information: 
Star Stable Coins (STAR) endorsed by World Digital Central Bank (WDCB), is a 1-1 asset backed stablecoins that is fully collaterized, legally protected and transparently verified by 3rd party attestations.

Tradeable exchanges: Nil

Recommended Gas Limit: 60,000

### CODE REVIEW

**Comment by sfsy520** [comment]
Logo不符合要求

**Comment by czhiqi** [comment]
请问是因为 logo 背景没透明还是尺寸不符合要求？

**Comment by sfsy520** [comment]
Logo要求如下：
* * 尺寸: 120x120 像素
* * 图片为透明背景的 PNG 格式
* * 品牌标识水平竖直居中顶边

**Comment by czhiqi** [comment]
已更新logo在#5596，麻烦审核。谢谢

**Pull request closed without merging**
