### PR TITLE
Add SAFE token

### PR DESCRIPTION
**Pull request by CryptoCoinLab**
### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

**.json 及 .png 文件检查项**
- [ √] logo 尺寸：120*120 px
- [ √ ] logo 背景：透明
- [ √ ] 代币有至少一笔成功的转账记录
- [ √ ] 此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
- [ √ ] .json 和 .png 文件名一致（包括大小写）

**项目资料：**

官方公告：https://twitter.com/safeanwang/status/1529348436494913536

团队背景：SAFE由新加坡SAFE基金会运营，SAFE开发团队由资深的比特币和区块链专家、技术研发团队和区块链运营人才组成，并且邀请了业内知名的技术专家和运营专家担任项目顾问，旨在打造一个有影响力、专注于区块链应用落地的项目。

项目基本情况：安网（SAFE）是由新加坡SAFE基金会于2014年10月推出的、去中心化的、专注数字资产隐私保护的区块链安全支付和隐私计算平台。距今2021年7月为止，已经有7年历史，期间经历从安网1.0、安网2.0、安网3.0等3个大版本的迭代更替，在各种创新技术和商业应用上进行了众多有益的探索。安网4.0携多年的行业实践经验和成果，以密码学理论和隐私计算为基础，以技术创新和应用创新为导向，着眼隐私保护，强化安全支付，优化资产隐私，引入跨链资产和稳定币，打造safeswap交易场，拓展更多商业化应用，旨在构建一个全球范围的隐私保护生态圈。

本次申报的合约是SAFE跨链至ETH网络的ERC20合约，已经在etherscan.io中注册合约代码和代币。https://etherscan.io/token/0xee9c1ea4dcf0aaf4ff2d78b6ff83aa69797b65eb
跨链方案： https://github.com/SAFE-anwang/SAFE4/blob/main/doc/wsafe.md 

媒体报道：https://bitsonline.com/bankledger-fork-dash-safe/

收录的交易所：
zb   https://www.zb.com/cn/kline/safe_usdt
zb   https://www.zb.com/cn/kline/safe_qc
jbex   https://www.jbex.com/exchange/SAFE/USDT

转账所需 Gas Limit（对 ERC-20 项目方）：60000

telegram: https://t.me/safeanwang
twitter:     https://twitter.com/safeanwang
reddit:      https://www.reddit.com/r/safeanwang
github:     https://github.com/SAFE-anwang

---

### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [√] logo dimensions: 120*120 px
- [√] logo background: Transparent
- [√] At least one transaction on the token contract
- [√] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [√] Same document name for both .json and .png (Including capitalization)

**Project background:**

Official announcement:https://twitter.com/safeanwang/status/1529348436494913536
Project team background: SAFE is operated by the Singapore SAFE Foundation. The SAFE development team is composed of senior Bitcoin and blockchain experts, technical R&D teams and blockchain operation talents, and has invited well-known technical experts and operation experts in the industry as project consultants. Create an influential project focusing on the implementation of blockchain applications.

Project basic information:
SAFE network is a decentralized, secure payment and privacy computing blockchain system focused on privacy protection, which was launched by Singapore SAFE Foundation in October 2014. It has been seven years since then. During this period, it has experienced the iterative replacement of three major versions of DNC 1.0, DNC 2.0 and SAFE 3.0, and made many beneficial explorations in various innovative technologies and commercial applications. Based on cryptography theory and privacy computing, and guided by technology innovation and application innovation, SAFE 4.0 focuses on privacy protection, strengthens secure payment, optimizes asset privacy, imports cross chain assets and stable currency, creates SAFESwap trading field, expands more commercial applications, and aims to build a global privacy protection ecosystem.

Media publications: https://bitsonline.com/bankledger-fork-dash-safe/

Tradeable exchanges:
zb   https://www.zb.com/cn/kline/safe_usdt
zb   https://www.zb.com/cn/kline/safe_qc
jbex   https://www.jbex.com/exchange/SAFE/USDT

Recommended Gas Limit (For ERC-20 project teams) for transaction:  60,000

### CODE REVIEW

**Comment by kaiko1203** [comment]
Hello, we reviewed your project information and your website has phishing behavior
I will not pass your token request

**Comment by amwgufjq01** [comment]
> Hello, we reviewed your project information and your website has phishing behavior I will not pass your token request

thanks for replying
Yes, in the last week, our website has indeed been suspended by the domain name provider, and the reason for the suspension is also phishing.
Our domain name was created on July 3, 2003, which is a long time ago.
This phishing behavior is a false positive. We have appealed to the domain name provider, and it will be released and restored to normal use on 2022-07-25.
Please check again, the inclusion of IM is very important to us.
Our foundation attaches great importance to the IM wallet, and has been using the IM wallet as an example during the preaching process, and we are constantly recommending believers to use the IM wallet.
thanks

**Comment by amwgufjq01** [comment]
> Hello, we reviewed your project information and your website has phishing behavior I will not pass your token request

Hello buddy 
Are you there？

**Comment by CryptoCoinLab** [comment]
域名注册商是误报，我们的网站并没有任何钓鱼行为，经过我们的解释，域名注册商于7月25日已经取消了这一说法，能正常访问了。

**Pull request closed without merging**
