### PR TITLE
Add GAL token

### PR DESCRIPTION
**Pull request by oyyblin**
### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [x] logo dimensions: 120*120 px
- [x] logo background: Transparent
- [x] At least one transaction on the token contract
- [x] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [x] Same document name for both .json and .png (Including capitalization)

### **Project background:**

**Official announcement:** 

https://twitter.com/ProjectGalaxyHQ/status/1519590266369417216

**Project team background:** 

- Harry Zhang, Co-Founder & Project Lead of Project Galaxy

Prior to founding Project Galaxy, Harry was the Co-Founder & COO of Lino Network and Co-Founder of Dlive.tv (merged into BitTorrent ecosystem in 2019). At Lino and DLive, Harry led the team and built the product that served more than 10 million monthly active users. Prior to that, Harry was the Head of Data Product at Club Factory (No.3 ecommerce platform in India at the time), where Harry designed a data-centric supply chain and recommendation system from the ground up. Harry holds a bachelor's degree of Computer Science and Statistics from UC Berkeley. He was also the President of Associate of Chinese Entrepreneurs (ACE) at Berkeley from 2016 to 2017. 

- Charles Wayn, Co-Founder & Strategy Lead of Project Galaxy

Prior to founding Project Galaxy, Charles was the Co-Founder & CEO of DLive.tv. After DLive merged into BitTorrent in 2019, Charles became the VP of Interactive Entertainment at BitTorrent, managing multiple streaming business units including DLive.tv, DLive Protocol, and the Two App. Charles holds a bachelor's degree of Economics from UC Berkeley. He was also the President of Associate of Chinese Entrepreneurs (ACE) at Berkeley from 2017 to 2018. 

**Project basic information:** 

Project Galaxy is the largest Web3 credential data network in the world.Project Galaxy helps developers and organizations leverage NFTs and digital credential data to build better products and communities in Web3.

Credentials live in our day-to-day life. An example of an on-chain credential would be the record that you borrowed money from DeFi lending protocols but were never liquidated. Your contribution to a protocol’s liquidity pool when it first launched, or your on-chain voting history are all credentials. All of your behavioral data in Web2 counts towards your credentials, companies like Google and Facebook run algorithms on your credentials so that they can send you targeted advertisements. Credentials are important due to the high use case they provide. Application developers can use your credentials to calculate credit scores, find target audiences, reward community contributors, etc. With the advance of Web3 and DAOs, there will be an explosion of behavioral data generated by waves of new users. Project Galaxy will provide the necessary infrastructure to help these new users build digital credentials that will be of paramount importance. 

Credential data today are segregated across closed databases that are owned and permissioned by applications, government organizations, and financial and credit institutions. This has led to a fractured landscape that is not open to the individuals who should own that data or the applications that need it. Project Galaxy aims to solve this problem using an open and collaborative credential data network which will help Web3 developers leverage credential data and NFTs to build better products and more engaging communities.

Project Galaxy provides the infrastructure for community members to curate and contribute digital credentials to the Galaxy Credential Data Network. The infrastructure supports curating credentials through multiple data sources. Curators can contribute data from 7 different chains with subgraph queries or snapshots for on-chain credentials. They can also provide data from Twitter, Discord, Github, or offline events for off-chain credentials. 
Project Galaxy also provides Application Modules, Credential API, and a Credential Oracle Engine to help developers leverage credential data. Use cases of the Application Modules include Galaxy OATs (On-chain Achievement Tokens), NFT loyalty programs, growth hacking campaigns, gated community, and customized governance. Developers can also utilize the Credential Oracle Engine and Credential API for enhanced customized use cases such as credit scoring and Sybil attack prevention algorithms.

**Media publications:**

- https://www.coindesk.com/layer2/2022/05/05/smart-money-wallets-accumulate-gal-and-decrease-ape-holdings-nansen-data/
- https://www.odaily.news/post/5178417 
- https://www.cryptopolitan.com/binance-coinbase-support-project-galaxy/
- https://www.gfinityesports.com/cryptocurrency/project-galaxy-token-gal-buy/
- https://coinjournal.net/news/project-galaxy-coin-rises-on-multiple-listings-heres-where-to-buy-project-galaxy/
- https://www.theblockbeats.info/en/news/28871
- https://www.defidaonews.com/article/6748134
- https://lunarcrush.com/influencers/ProjectGalaxyHQ
 
**Tradeable exchanges:**

Binance
Binance TR
Huobi Global
Gate.io
KuCoin
Bybit
FTX
Coinbase Exchange
Coinlist Pro
MEXC
PancakeSwap (V2)
Uniswap (V3)
WOO Network
BitMark
BitGet
For more: https://coinmarketcap.com/currencies/project-galaxy/markets/
 
**Recommended Gas Limit (For ERC-20 project teams) for transaction: (Default is 60,000)** 

60,000 should be fine

### CODE REVIEW

**Review by shahngah — APPROVED** [review]

**Comment by oyyblin** [comment]
@shahngah what's the status of the review process? Just curious whether we can merge the PR now :P. Thanks!

**Comment by Alfonsoanava** [comment]
Can somebody help me deploy my tokens there on Binance They're called world credit tokens I'm having a problem deploying them and running them I need some help thank you

**Comment by Alfonsoanava** [comment]
They're cold World credit symbol is world

**Comment by Alfonsoanava** [comment]
I am the creator this is how you can find them on the Binance smart test 0xA901Cf8023D4a644aCC27582232EB70E9222F2e8

**Pull request merged**
