### PR TITLE
ADD FB Token

### PR DESCRIPTION
**Pull request by FLY-EX**
### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

**.json 及 .png 文件检查项**
- [x] logo 尺寸：120*120 px
- [x] logo 背景：透明
- [x] 代币有至少一笔成功的转账记录
- [x] 此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
- [x] .json 和 .png 文件名一致（包括大小写）

**项目资料：**

- 官方公告：https://flyex.zendesk.com/hc/zh-cn/articles/360038441653 
- 团队背景：FB Token 团队分布在飞币在新加坡、美国、日本、韩国、香港等多个国家和地区设立运营中心。核心成员平均超过十年互联网产品开发经验，是国内早期比特币布道者、研究区块链领域的创业团队。 
- 项目基本情况：FB是在飞币数字资产交易平台上通行的功能性Token，是平台功能的拓展、多项权益的实现和生态价值回报的重要组成部分。 
- 媒体报道：暂无
- 收录的交易所：暂无 
- 转账所需 Gas Limit（对 ERC-20 项目方）：60000

---

### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [x] logo dimensions: 120*120 px
- [x] logo background: Transparent
- [x] At least one transaction on the token contract
- [x] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [x] Same document name for both .json and .png (Including capitalization)

**Project background:**

Official announcement:https://flyex.zendesk.com/hc/zh-cn/articles/360038441653
Project team background:FB token team is distributed in many countries and regions such as Singapore, the United States, Japan, South Korea, Hong Kong to set up operation centers. With an average of more than 10 years of Internet product development experience, the core members are the early bitcoin evangelists in China and the entrepreneurial team in the field of blockchain research.
Project basic information:FB is a functional token commonly used on the digital asset trading platform of flying coin, which is an important part of the expansion of platform functions, the realization of multiple rights and interests and the return of ecological value.
Media publications:No
Tradeable exchanges:No
Recommended Gas Limit (For ERC-20 project teams) for transaction: 60000

### CODE REVIEW

**Comment by FLY-EX** [comment]
ok

**Comment by sfsy520** [comment]
请检查Checksum

**Comment by FLY-EX** [comment]
@sfsy520  你好，已经做过Checksum，如果有错误，还希望您能给我们指教~

**Comment by sfsy520** [comment]
json文件中的合约地址也需要检查Checksum

**Comment by sfsy520** [comment]
非常抱歉，由于该PR长时间未更新，我们先关闭这个PR
如果仍需提交，请参考教程重新提交：
https://github.com/consenlabs/token-profile#token-profile-guideline

**Pull request closed without merging**
