### PR TITLE
Add Token Symbol: YP

### PR DESCRIPTION
**Pull request by yepchain**
YP is the token for the Yep Chain

### CODE REVIEW

**Comment by makoshan** [comment]
你好，请核对正确的合约地址, 确认是不是一下地址

```
0x02E2C716230C6750208F7Cb1Af34049472C91527
```

**Comment by yepchain** [comment]
hello, do I need to update the files with the contract address or you will take care of the updates while merging ?  Thanks !

**Comment by makoshan** [comment]
你好，请提交正确合约地址，并修改文件名

**Comment by yepchain** [comment]
updated, please check. Thanks.

**Comment by makoshan** [comment]
请遵循我们的 logo 规范，顶边

**Comment by yepchain** [comment]
@makoshan updated, thx !

**Pull request merged**
