### PR TITLE
Add DOI token

### PR DESCRIPTION
**Pull request by daoswap001**
## Official announcement:
https://twitter.com/SwapDao/status/1334023646814191618?s=19

## Project team background: 
Daoswap is a global community, started by develpers and domain experts from Dubai, US, Canda and other regions joining, started from 2020. Working togather the community focus on the Automatic Market Maker (AMM) algorithm, trying to optimize both from tech and Defi Mode.

## Project basic information:
Daoswap is a Decentralized exchange platform based on Ethereum, applied an AMM algorithm rather than orderbook to provide traders a new way to aquire Liquidity.

## More info
Offical Website: <https://www.daoswap.global>
Telegram: <https://t.me/daoswap>
Twitter: <https://twitter.com/SwapDao>

Media publications:
<http://www.shilian.com/kuaixun/252896.html>
<https://www.fn.com/lives/147017.html>

## Supported Exchanges:
Suggested Gas limit setting (default is 60,000): default 60,000

### CODE REVIEW

**Comment by sfsy520** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 ，imToken 支持比特币, 以太坊, Comos, EOS, 波场, Nervos, 比特币现金, 莱特币，波卡等资产管理；同时支持去中心化币币兑换功能 Tokenlon；转账页面支持 ETH, USDT, EOS, BTC OTC 功能；另外对于没有 ETH 矿工费的用户，也提供 ETH 手续费充值功能。

**Comment by davidliu3721** [comment]
@sfsy520 你好，已提交了代币信息，但为什么TOKEN的LOGO还没有显示出来呢？
image

**Comment by sfsy520** [comment]
您好，json格式正确，已经reverted，请修正后重新提交。

**Comment by daoswap001** [comment]
@sfsy520 It's been revised and submitted again，<https://github.com/consenlabs/token-profile/pull/6616>

**Pull request merged**
