### PR TITLE
Btt

### PR DESCRIPTION
**Pull request by 0405degrees**
### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

**.json 及 .png 文件检查项**
- [x] logo 尺寸：120*120 px
- [x] logo 背景：透明
- [x] 代币有至少一笔成功的转账记录
- [x] 此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
- [x] .json 和 .png 文件名一致（包括大小写）

**项目资料：**

官方公告：
团队背景：
项目基本情况：
媒体报道：
收录的交易所：
转账所需 Gas Limit（对 ERC-20 项目方）：（默认为 60000）

---

### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [x] logo dimensions: 120*120 px
- [x] logo background: Transparent
- [x] At least one transaction on the token contract
- [x] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [x] Same document name for both .json and .png (Including capitalization)

**Project background:**

Official announcement: https://twitter.com/bitloto
Project team background: The team from Bitloto Develop this platform using a system that is directly integrated and uses Blockchain technology as the basis of its development. Bitloto sees that Blockchain's technology is a renewable solution in the sweepstakes industry, and takes this opportunity to improve a better sweepstakes service. Bitloto Designed for raffle tickets to be mine by using supercomputer supported by the user, so this ticket is the first cryptocurrency that can be used as cryptocurrency as well as a ticket in lottery service. This is a renewable breakthrough in global sweepstakes service, with the help of CPU, Bitloto along with Users mines cryptocurrency to achieve a larger jackpot. users can play on without the need to buy tickets or anything else, users can directly mine lottery tickets directly through the app has been designed by Bitloto.

Team Profile: https://bitloto188.com/about/
Project basic information: Bitloto is focusing on sweepstakes service providers based on the renewable and sustainable Blockchain technology. Bitloto uses revolutionary Blockchain technology and changing the pattern of lottery games better than ever before. Bitloto incorporates Blockchain System technology that is designed in such a way as to provide users with a fair and transparent lottery service. 

Media publications: http://asiashift.com/news/bitloto-now-offers-sustainable-blockchain-lottery-platform-with-unique-cryptocurrency-ticketing/265330/
http://frontalreport.com/news/bitloto-now-offers-sustainable-blockchain-lottery-platform-with-unique-cryptocurrency-ticketing/265330/
http://dailytechgeek.com/news/bitloto-now-offers-sustainable-blockchain-lottery-platform-with-unique-cryptocurrency-ticketing/265330/
http://24-7reporters.com/news/bitloto-now-offers-sustainable-blockchain-lottery-platform-with-unique-cryptocurrency-ticketing/265330/
Tradeable exchanges: N/A
Recommended Gas Limit (For ERC-20 project teams) for transaction: 180,000

### CODE REVIEW

**Comment by sfsy520** [comment]
Logo不符合要求

**Comment by 0405degrees** [comment]
Updated logo size. Thanks!!

**Comment by 0405degrees** [comment]
hello. Anybody here?

**Comment by sfsy520** [comment]
为确保资料提交的真实性，请在贵方官网或其他经过认证的社交媒体渠道发布公告，并将此公告链接附于「官方公告」。推荐文案：
#imToken# #1636# 我们正在完善 XXX 在 imToken 中的代币相关资料。完成后，大家可以在 imToken 里看到 logo，更方便地管理 XXX，同时能看到更多代币信息。
注：
* 1636 为 pr 序号，如 https://github.com/consenlabs/token-profile/pull/1636 的序号为 1636，这是帮助 imToken 判断 pr 真实性的关键。
* #imToken #1636 标签及其展示形式可自行调整。
* 若未提供「官方公告」，则无法显示代币信息。

**Comment by 0405degrees** [comment]
https://twitter.com/bitloto/status/1331878035293954050?s=19

**Pull request closed without merging**
