### PR TITLE
Add CNDL

### PR DESCRIPTION
**Pull request by samisbakedham**
### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [x] logo dimensions: 120*120 px
- [x] logo background: Transparent
- [x] At least one transaction on the token contract
- [x] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [x] Same document name for both .json and .png (Including capitalization)

**Project background:**

Official announcement: https://twitter.com/candle_labs
Project team background: https://candlelabs.org
Project basic information: Decentralized Human-focused metaverse - Candle (CNDL) is the utility and governance token for the Candle Protocol. This protocol is designed to decentralize social media and build out a community governed and moderated place to discuss and share thoughts and ideas.
Media publications: CoinTelegraph
Tradeable exchanges: Decoin, Tokpie, BankCEX, Coinbase
Official Announcement:
[Twitter Link](https://twitter.com/Candle_Labs/status/1507194752009089030?s=20&t=5_aeWl1O3U1E7jP3HT9ZPg)
Recommended Gas Limit (For ERC-20 project teams) for transaction: 40,000

### CODE REVIEW

**Comment by kaiko1203** [comment]
1.Your PR is missing project information
2.Official Twitter is missing imToken listing announcement
3.Please don't upload more than one logo

**Comment by samisbakedham** [comment]
> 1.Your PR is missing project information
> 2.Official Twitter is missing imToken listing announcement
> 3.Please don't upload more than one logo

Fixing now

**Comment by samisbakedham** [comment]
[Twitter Link](https://twitter.com/Candle_Labs/status/1507194752009089030?s=20&t=5_aeWl1O3U1E7jP3HT9ZPg)

**Review by samisbakedham — COMMENTED** [review]
Fixed

**Comment by samisbakedham** [comment]
Please merge

**Comment by samisbakedham** [comment]
Merge me

**Comment by samisbakedham** [comment]
Please merge

**Comment by kaiko1203** [comment]
Please do not delete in the local database

**Comment by samisbakedham** [comment]
Fixed it

**Comment by samisbakedham** [comment]
> Please do not delete in the local database
> 
> 

Good to merge? Thanks

**Comment by kaiko1203** [comment]
You have not uploaded the LOGO, please do not make changes in your database

**Comment by samisbakedham** [comment]
> You have not uploaded the LOGO, please do not make changes in your database

Fixed

**Comment by zengbing15** [comment]
Not sure if the project is still being maintained。

**Comment by makoshan** [comment]
提交信息有问题，我先关闭这个 PR

**Pull request closed without merging**
