### PR TITLE
Create 0xdc30a5baf62f3ce8d7e74a272bc139fbb7a0cab4

### PR DESCRIPTION
**Pull request by OriginForecast**

### CODE REVIEW

**Comment by makoshan** [comment]
Please attach the token logo image, And refer to the following:

```
{
  "symbol": "OF",
  "address": "0xdc30a5baf62f3ce8d7e74a272bc139fbb7a0cab4",
  "overview":{
        "en":"ToOrigin Forecast is an algorithm to analyze and predict the market.Through analysis and quantification Market data Community data CryptoCurrencies companies events  the price trend of the token is accurately reflected.escription."
  },
  "email": "onforecast@gmail.com",
  "website": "https://www.onft.info/",
  "whitepaper": "http://16858662.s21d-16.faiusrd.com/61/ABUIABA9GAAgiffM2AUogJSpsAI.pdf",
  "published_on": "2018-06-01",
  "initial_price":{
        "ETH":"0.000001 ETH",   
  },
  "links": {
    "twitter": "https://twitter.com/Origin_Forecast",
    "telegram": "https://t.me/Origin_Forecast",
    "github": "https://github.com/OriginForecast",
  }
}
```

**Comment by OriginForecast** [comment]
This message is incorrect and has been corrected to:
website": "https://www.onforecast.info/",

**Comment by OriginForecast** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
Hello, thanks for your help，I have added it under your link. What should I do next?


    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                                    


    On 6/6/2018 21:47，Mako Shan<notifications@github.com> wrote： 


Please attach the token logo image, And refer to the following:
{
  "symbol": "OF",
  "address": "0xdc30a5baf62f3ce8d7e74a272bc139fbb7a0cab4",
  "overview":{
        "en":"ToOrigin Forecast is an algorithm to analyze and predict the market.Through analysis and quantification Market data Community data CryptoCurrencies companies events  the price trend of the token is accurately reflected.escription."
  },
  "email": "onforecast@gmail.com",
  "website": "https://www.onft.info/",
  "whitepaper": "http://16858662.s21d-16.faiusrd.com/61/ABUIABA9GAAgiffM2AUogJSpsAI.pdf",
  "published_on": "2018-06-01",
  "initial_price":{
        "ETH":"0.000001 ETH",   
  },
  "links": {
    "twitter": "https://twitter.com/Origin_Forecast",
    "telegram": "https://t.me/Origin_Forecast",
    "github": "https://github.com/OriginForecast",
  }
}

**Comment by makoshan** [comment]
请通过 github PR 修改信息。

**Comment by makoshan** [comment]
Please update token information.

**Comment by OriginForecast** [comment]
I don't know how to correct the information. If you don't change the information, it's ok.
No need to change the information.

**Comment by OriginForecast** [comment]
No need to change the information.
The information I provided earlier was correct, including this website.He can use it without changing it.

**Comment by OriginForecast** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    

No need to change the information.The information I provided earlier was correct, including this website.He can use it without changing it.                


    On 6/14/2018 11:42，Mako Shan<notifications@github.com> wrote： 


Closed #37.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.



        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }

**Pull request closed without merging**
