### PR TITLE
Exx token

### PR DESCRIPTION
**Pull request by coder-exx**
### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

**.json 及 .png 文件检查项**
- [x] logo 尺寸：120*120 px
- [x] logo 背景：透明
- [x] 代币有至少一笔成功的转账记录
- [x] 此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
- [x] .json 和 .png 文件名一致（包括大小写）

**项目资料：**

官方公告：https://weibo.com/6409905840/I0XUhmcKB?from=page_1005056409905840_profile&wvr=6&mod=weibotime&type=comment
团队背景：
项目基本情况：ET为EXX Token的简称，2018年 7月9日，ET 正式对外发行，总量恒定 100 亿，永不增发。ET是 EXX 交易平台本身的权益证明，基于以太坊ERC20协议发行，是EXX平台唯一的全球通证。ET作为EXX生态中的重要组成部分，未来会应用到EXX实体生态的应用场景中。ET 持有者共同享有社区治理等各类权利，是EXX社区成员协同发展的基石。持有者享受ET全生态的相应权益，并得到生态子通证奖励，以及享受ET持续回购销毁带来的稀缺性提升。
媒体报道：
收录的交易所：EXX.com、ZBG.com、BW.com
转账所需 Gas Limit（对 ERC-20 项目方）：（默认为 60000）

---

### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [x] logo dimensions: 120*120 px
- [x] logo background: Transparent
- [x] At least one transaction on the token contract
- [x] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [x] Same document name for both .json and .png (Including capitalization)

**Project background:**

Official announcement:https://weibo.com/6409905840/I0XUhmcKB?from=page_1005056409905840_profile&wvr=6&mod=weibotime&type=comment
Project team background:
Project basic information:ET is the abbreviation of EXX Token. On July 9, 2018, ET was officially issued, with a total amount of 10 billion, and will never be issued. ET is a proof of the rights of the EXX trading platform itself. It is based on the Ethereum ERC20 agreement and is the only global certificate of the EXX platform. As an important part of the EXX ecosystem, ET will be applied to the application environment of the EXX entity ecosystem in the future. ET holders share various rights such as community governance and are the cornerstone of the collaborative development of EXX community members. Holders enjoy the corresponding rights of ET's entire ecology and enjoy the scarcity of ET's continued repurchase and destruction.
Media publications:
Tradeable exchanges:EXX.com、ZBG.com、BW.com
Recommended Gas Limit (For ERC-20 project teams) for transaction: (Default is 60,000)

### CODE REVIEW

**Comment by coder-exx** [comment]
why build failed

**Comment by tstt** [comment]
pr 中存在的问题已在标签中指出，请参考教程检查修改。

关于「need to verified」：
https://github.com/consenlabs/token-profile/blob/master/tutorial/erc20-tutorial.zh-CN.md#%E8%B5%84%E6%96%99%E7%9A%84%E5%AE%8C%E6%95%B4%E5%92%8C%E5%87%86%E7%A1%AE

image

**Comment by coder-exx** [comment]
附上了公告

**Comment by tstt** [comment]
欢迎推荐社区用户使用 imToken 2.0 管理代币。

**Comment by coder-exx** [comment]
现在这样算是已经提交成功了吗？

**Comment by tstt** [comment]
合并（merged）就代表提交成功了，用户可以在 app 内看到这些代币信息。

**Pull request merged**
