### PR TITLE
Add SASN erc-20 token to Imtoken

### PR DESCRIPTION
**Pull request by ASNchain**
Official Announcement:
【An announcement about SASN submitting token information in imToken】
http://asn.plus/a/News/2020/1008/21.html

Media Reports:
ASN NETWORK IS PARTNERING WITH ASIAN B2B PLATFORMS
https://www.globalnewsonline.info/asn-network-is-partnering-with-asian-b2b-platforms/
http://finance.dailyherald.com/dailyherald/news/read/40402832/
http://markets.financialcontent.com/stocks/news/read/40402832
http://markets.ask.com/ask/news/read/40402832
http://business.times-online.com/times-online/markets/news/read/40402832/
http://business.dailytimesleader.com/dailytimesleader/markets/news/read/40402832/
http://markets.chroniclejournal.com/chroniclejournal/news/read/40402832/

Team background:
ASN Network team is distributed in Singapore, China,Hongkong,UK and other regions. The core members are elites from the blockchain industry, financial industry, Internet product research and development, digital currency economy and other industries. With a wealth of successful blockchain project cases,ASN network aims to make cross-border B2B financial transactions be processed in a frictionless, cost-efficient, and faster manner compared to the existing Swift system and related clearing and settlement facilities.
For example，David Yeung,the CEO of ASN Network
He has rich business service experience and significant marketing experience in multinational companies. and has the ability of market management, technology research and development, and digital economy project research.

Basic project information:
ASN (Alternative Swift Network) is the world’s first Defi featured decentralized network which can facilitate cross-border B2B financial transactions without using traditional Swift system.   
It aims to make cross-border B2B financial transactions be processed in a frictionless, cost-efficient, and faster manner compared to the existing Swift system and related clearing and settlement facilities. 
ASN’s Defi features can further attract targeted users (B2B business owners and other interested parties) as it empowers them to leverage more financial resources to expand their businesses and/or increase benefits. 
ASN’s Defi features have real-world usage (say, in B2B) compared to many other Defi protocols (which mostly only help users to speculate in the crypto market).

More about SASN:
ASN Governance Token: Super ASN (or SASN):
official website：http://asn.plus/
twitter：https://twitter.com/AsnCommittee
Facebook:https://www.facebook.com/asn.plus.3
suggest gas limit：60000
Indexed exchange：Uniswap

### CODE REVIEW

**Comment by ASNchain** [comment]
Official Announcement:
【An announcement about SASN submitting token information in imToken】
http://asn.plus/a/News/2020/1008/21.html

**Comment by ASNchain** [comment]
Official Announcement:
【An announcement about SASN submitting token information in imToken】
http://asn.plus/a/News/2020/1008/22.html


https://github.com/consenlabs/token-profile/pull/6306

**Comment by sfsy520** [comment]
Logo需背景透明

**Comment by ASNchain** [comment]
Logo image has re-uploaded

**Comment by sfsy520** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 ，imToken 支持比特币, 以太坊, Comos, EOS, 波场, Nervos, 比特币现金, 莱特币，波卡等资产管理；同时支持去中心化币币兑换功能 Tokenlon；转账页面支持 ETH, USDT, EOS, BTC OTC 功能；另外对于没有 ETH 矿工费的用户，也提供 ETH 手续费充值功能。

**Comment by ASNchain** [comment]
为什么 imtoken里面代币还是没有显示图标





------------------ Original ------------------

**Comment by sfsy520** [comment]
由于Json文件格式不正确，导致merge失败，请修改后重新提交，这个PR将会Revert处理。

**Comment by ASNchain** [comment]
已经提交新的PR，重新提交了 #6394





------------------ Original ------------------

**Pull request merged**
