### PR TITLE
Add NIRX Token

### PR DESCRIPTION
**Pull request by NairaX**
### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

**.json 及 .png 文件检查项**
- [x] logo 尺寸：120*120 px
- [x] logo 背景：透明
- [x] 代币有至少一笔成功的转账记录
- [x] 此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
- [x] .json 和 .png 文件名一致（包括大小写）

**项目资料：**

官方公告：https://twitter.com/nirxcoin/status/1300376218362142720?s=19
https://www.facebook.com/601064640390185/posts/947353822427930/
https://bitcointalk.org/index.php?topic=5167146.0
团队背景：https://www.nirxblock.com/team, https://icoholder.com/en/nairax-30458
项目基本情况：奈拉克斯项目开发了NIRX，作为第一个与尼日利亚的菲亚特价值挂钩的非洲稳定品，在电子商务方面提出了一个实用工具。NairaX 于 2019 年 4 月 20 日启动，在尼日利亚注册 （RC-2903759） – 旨在通过我们稳定的资产"NIRX"解决全球加密货币波动问题，以促进全球在一般电子商务中采用加密和污秽。
媒体报道：https://twitter.com/nirxcoin/status/1298458021337718786
https://block.cc/coin/nairax
https://www.cicryptosolutions.com/post/nairx-trading-competition-on-naijacrypto-deposit-and-trade-to-win-nairx
https://icobench.com/ico/nairax
https://qryptocentral.com/?p=565
https://diutocoinnews.com.ng/nairax-trading-competition/4137/
https://www.publish0x.com/kriptosedat/nirx-blok-new-announcements-from-africas-first-stable-coinag-xvpwly
收录的交易所：XT.com, Homiex.com, Zgtop.io, naijacrypto.com, azbit.com
转账所需 Gas Limit（对 ERC-20 项目方） 60,000

---

### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [x] logo dimensions: 120*120 px
- [x] logo background: Transparent
- [x] At least one transaction on the token contract
- [x] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [x] Same document name for both .json and .png (Including capitalization)

**Project background:**

Official announcement: https://twitter.com/nirxcoin/status/1300376218362142720?s=19
https://www.facebook.com/601064640390185/posts/947353822427930/
https://bitcointalk.org/index.php?topic=5167146.0
Project team background: https://www.nirxblock.com/team, https://icoholder.com/en/nairax-30458
Project basic information: Project NairaX developed NIRX as the first African stablecoin pegged to Nigeria's FIAT value with a proposed utility in ecommerce. Launched on 20/04/2019, NairaX is registered in Nigeria (RC-2903759) & aims to tackle problems of cryptocurrency volatility in the world via our stable asset "NIRX", in order to foster global adoption of crypto in general e-commerce & defi.
Media publications: https://twitter.com/nirxcoin/status/1298458021337718786
https://block.cc/coin/nairax
https://www.cicryptosolutions.com/post/nairx-trading-competition-on-naijacrypto-deposit-and-trade-to-win-nairx
https://icobench.com/ico/nairax
https://qryptocentral.com/?p=565
https://diutocoinnews.com.ng/nairax-trading-competition/4137/
https://www.publish0x.com/kriptosedat/nirx-blok-new-announcements-from-africas-first-stable-coinag-xvpwly
Tradeable exchanges: XT.com, Homiex.com, Zgtop.io, naijacrypto.com, azbit.com
Recommended Gas Limit (For ERC-20 project teams) for transaction: 60,000

### CODE REVIEW

**Comment by sfsy520** [comment]
In order to ensure the authenticity of the information submitted, please publish an announcement on your website or official social media channels and attach the corresponding link in “Official announcement”. We recommended a format similar to the following:
#imToken #1636 We are providing XXX token’s information on imToken. After completion, you can see the logo and full information inside imToken’s Token Manager.
Note:
* 1636 is the PR number, as in: https://github.com/consenlabs/token-profile/pull/1636 This number is the key to verify yourself as the rightful editor of the information to imToken.
* The token information can only be changed after the official verification

**Comment by NairaX** [comment]
Hi @sfsy520, thanks. Please find announcement in "Official Announcement" category.
Ref link: https://twitter.com/nirxcoin/status/1300376218362142720?s=19

**Comment by sfsy520** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 ，imToken 支持比特币, 以太坊, Comos, EOS, 波场, Nervos, 比特币现金, 莱特币，波卡等资产管理；同时支持去中心化币币兑换功能 Tokenlon；转账页面支持 ETH, USDT, EOS, BTC OTC 功能；另外对于没有 ETH 矿工费的用户，也提供 ETH 手续费充值功能。

**Comment by NairaX** [comment]
Thanks for merging @sfsy520. Gracias

**Pull request merged**
