### PR TITLE
Add DMMM token

### PR DESCRIPTION
**Pull request by d-mmm**
Project background:
Official website: https://d-mmm.github.io

Official announcement:
https://d-mmm.github.io/announcements/token-info-for-imtoken.md

Team background:
We are an international team of tech geeks from Russia, China and India.

Project basic information:
The dMMM game is the first classic dApp on the dMMM ecosystem. In the dMMM game, players can participate in the game by paying tokens and earn income when they wait in line to end the game. In the process of continuously participating in the game, the player account can be upgraded to obtain more interesting and tangible benefits or rewards.

Recommended Gas Limit for transaction: 80000

### CODE REVIEW

**Comment by sfsy520** [comment]
请在官网添加跳转至官方公告渠道的链接。

**Comment by d-mmm** [comment]
> 请在官网添加跳转至官方公告渠道的链接。

Here is the Google Translate result of your reply content:

> Please add a link to the official announcement channel on the official website.

If it is correct, the work had been done before. Please see the bottom of the official site

image

**Comment by sfsy520** [comment]
Your website was https://dmmm.io

**Comment by d-mmm** [comment]
> Your website was https://dmmm.io

Thanks for your reply, but this is the dApp link, not the OFFICIAL WEBSITE.

image

The dApp link was designed for users to interact with dApp in crypto wallet and it's not suitable for adding some other links there, like announcemet or something else, or it will look wired.

As I mentioned before, our official website is: https://d-mmm.github.io

image

Yours.

**Comment by sfsy520** [comment]
so you should replace the website address with "https://d-mmm.github.io"，in the json file

**Comment by d-mmm** [comment]
> so you should replace the website address with "[https://d-mmm.github.io"，in](https://d-mmm.github.io%22%EF%BC%8Cin) the json file

Thank you for your kind reply, I've fixed this problem.

**Comment by sfsy520** [comment]
Welcome to recommend imToken 2.0 to your token holders to manage their token.

**Pull request merged**
