### PR TITLE
Add BULL token

### PR DESCRIPTION
**Pull request by bulldex**
**Official announcement:** 
BULL is the integration of decentralized finance and e-commerce, a symbiotic Internet for freedom and wealth
BULL echoes, circulates and balances existing mainstream Internet applications (such as Facebook, YouTube and WeChat), thus forming a strong internal structure at the early stage. Its internal financial balance, community promotion, business connection, value accumulation and network expansion will further improve the shortcomings of the centralized business model
 
BULL will be a symbiotic Internet for everybody. It supports the development of separate Web browsers, where each BULL address can be used as an anonymous IP address. In this open symbiotic network, all applications of the centralized Internet can be migrated. To create a new, decentralized ecosystem of Internet freedom through community efforts

Link: [http://bulldex.org/](http://bulldex.org/)
 
**Project team background:** 
 Bull team works in the world's top Internet companies, with rich experience and great influence. Own blockchain, good at e-commerce, online games, blockchain
 
**Project basic information:** 
Bull combines Internet decentralized Finance
And decentralized e-commerce, symbiosis with internet giants. Bull will become the universal "symbiotic token" in the future decentralized Global Finance
 
**Bull volume:**
Total, 21 million bull. 
21 million obtained by mining
1 million bull usage allocation table
51% Community feedback and construction 
bull community promotion, ecological construction,
 user reward and pass replacement
19% of the bull fund is invested in relevant digital ecosystems, philanthropy, and rewarding outstanding contributors.
The locking period was 12 months.
15% of the founding team,
 the lock-in period is one year.
8% Strategic partner lock period 12 months
7% Private  lock for 6 months.
 
**Media publications:** 
https://twitter.com/bulldextoken
https://www.facebook.com/dex.bull.33
https://t.me/bulldexofficialgroup
https://t.me/bulldextoken
 
**Tradeable exchanges:** 
BIKI
UNISWAP

**Recommended Gas Limit (For ERC-20 project teams) for transaction:** 
60000

### CODE REVIEW

**Comment by sfsy520** [comment]
为确保资料提交的真实性，请在贵方官网或其他经过认证的社交媒体渠道发布公告，并将此公告链接附于「官方公告」。推荐文案：
#imToken# #1636# 我们正在完善 XXX 在 imToken 中的代币相关资料。完成后，大家可以在 imToken 里看到 logo，更方便地管理 XXX，同时能看到更多代币信息。
注：
* 1636 为 pr 序号，如 https://github.com/consenlabs/token-profile/pull/1636 的序号为 1636，这是帮助 imToken 判断 pr 真实性的关键。
* #imToken #1636 标签及其展示形式可自行调整。
* 若未提供「官方公告」，则无法显示代币信息。

**Comment by bulldex** [comment]
「官方公告」

**Comment by bulldex** [comment]
「官方公告」
http://bulldex.org/

**Comment by bulldex** [comment]
We have published an announcement on the official website channel to help IMToken judge the authenticity of PR, our official website: http://bulldex.org

**Comment by sfsy520** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 ，imToken 支持比特币, 以太坊, Comos, EOS, 波场, Nervos, 比特币现金, 莱特币，波卡等资产管理；同时支持去中心化币币兑换功能 Tokenlon；转账页面支持 ETH, USDT, EOS, BTC OTC 功能；另外对于没有 ETH 矿工费的用户，也提供 ETH 手续费充值功能。

**Pull request merged**
