### PR TITLE
Add POW & POWX tokens

### PR DESCRIPTION
**Pull request by powhfund**
### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

**.json 及 .png 文件检查项**
- [ ] logo 尺寸：120*120 px
- [ ] logo 背景：透明
- [ ] 代币有至少一笔成功的转账记录
- [ ] 此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
- [ ] .json 和 .png 文件名一致（包括大小写）

**项目资料：**

官方公告：
团队背景：
项目基本情况：
媒体报道：
收录的交易所：
转账所需 Gas Limit（对 ERC-20 项目方）：（默认为 60000）

---

### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [x] logo dimensions: 120*120 px
- [x] logo background: Transparent
- [x] At least one transaction on the token contract
- [ ] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [x] Same document name for both .json and .png (Including capitalization)

**Project background:**

Official announcement: https://twitter.com/powhfund/status/1168901573973557248
Project team background: The team has experience with creation and launch of several prominent blockchain based projects and development for Ethereum and EOS. However to keep Proof of Weak Hands as a truly community driven project governed by code, not personalities, the team has opted to stay anonymous.
Project basic information: Proof of Weak Hands (POWh) is an EOS based exchange that shares benefits from activity on the platform (token buys, sells or transfers) to all POW token holders in transparent and verifiable manner. Price setting mechanics is defined in a smart contract. Exchange operates under a perfect economic simulation where each POW token grants you a stake of all cryptocurrency volume.
POWX is a loyalty/transitional token in POW Ecosystem, that enables exchange of value outside of the platform. It can be swapped into POW token and back without any restrictions.

### CODE REVIEW

**Comment by tstt** [comment]
有两个问题需要处理：

1. 请提供「官方公告」
https://github.com/consenlabs/token-profile/blob/master/tutorial/erc20-tutorial.zh-CN.md#%E8%B5%84%E6%96%99%E7%9A%84%E5%AE%8C%E6%95%B4%E5%92%8C%E5%87%86%E7%A1%AE

image

2. 请补充基本项目资料：
image

**Comment by powhfund** [comment]
Official announcement: 
https://twitter.com/powhfund/status/1168901573973557248

Project team background: 
The team has experience with creation and launch of several prominent blockchain based projects and development for Ethereum and EOS. However to keep Proof of Weak Hands as a truly community driven project governed by code, not personalities, the team has opted to stay anonymous.

Project basic information: 
Proof of Weak Hands (POWh) is an EOS based exchange that shares benefits from activity on the platform (token buys, sells or transfers) to all POW token holders in transparent and verifiable manner. Price setting mechanics is defined in a smart contract. Exchange operates under a perfect economic simulation where each POW token grants you a stake of all cryptocurrency volume.
POWX is a loyalty/transitional token in POW Ecosystem, that enables exchange of value outside of the platform. It can be swapped into POW token and back without any restrictions.

**Comment by sfsy520** [comment]
官网无实质内容，请丰富并提供官方公告，并附于 pr 中，以确保项目真实性。

**Comment by powhfund** [comment]
Web site: https://powh.fund/dapp

**Comment by sfsy520** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 管理资产。

**Pull request merged**
