### PR TITLE
vrh-token

### PR DESCRIPTION
**Pull request by VersaillesHeroes**
Official announcement: 
twitter link： https://twitter.com/VersHeroes/status/1570619702464114689

#imToken#7401#VRH-Token
Versailles Heroes is improving VRH token related information in imToken.📝
After completion, you can see VRH logo in imToken, manage VRH more conveniently, and reveal more token information at the same time.✅

Team：
The Versailles Heroes development team collaborates globally in the US, UK, Canada, UAE, Europe and more, providing a complete technology incubation center from design to deployment solutions. The Versailles Hero team is known for quality and reputation in the Metaverse Solutions business. It has gained extensive experience in AI/ML and AR/VR enabled mobile applications to improve applications accordingly. teamwork 
We have a passion for video games and a desire for the Metaverse, coupled with our experience developing several high-quality and successful games with the help of many smart contract experts, economic modeling experts, and GameFi community leaders from Silicon Valley.

Introduction:

VRH (Versailles Heroes) is a DAO (DeFi) financial infrastructure on the Ethereum chain, aiming to build a fast-growing TVL financial environment for DeFi investment. VRH tokens are issued through ERC-20 contracts and by utilizing the DAO protocol to achieve an open, transparent, and fair governance. In addition, it is committed to promoting the ecological development of DeFi and blockchain games. Investors can lock up VRH for 1, 2, 3, and 4 years to obtain veVRH. veVRH can be used to vote on network proposals and can also be used by investors to create a guild or join a guild for mining. To participate in the internal competition of the guild, investors can burn game token (MOH) in exchange for GAS, which can accelerate the weight of their individual mining by up to 2.5 times. In this way, a competitive environment that promotes the growth of market value is established, and investors who participate in the competition by using GAS acceleration can obtain higher returns.

Contract transaction Gas limit（60000）

Social media：
twitter: https://twitter.com/VersHeroes 

discord: https://discord.gg/bz2jJv4dJ2 

facebook: https://www.facebook.com/VersaillesHeroes 

telegram: https://t.me/VRHannouncement

telegram: https://t.me/VRHWorldwide

### CODE REVIEW

**Comment by kaiko1203** [comment]
Audit not approved
Reason.
token transactions need to have 1 transaction in the last 10 days

**Comment by VersaillesHeroes** [comment]
I have one latest transaction today. Please refer to: https://etherscan.io/tx/0xc961f8875a610ed0cd581438aee2de7fd1254fc24915ddf85a79dfc071e71c36
@kaiko1203 #7401

**Comment by newbein123** [comment]
- [ ] @ #### 

> ****

**Comment by VersaillesHeroes** [comment]
@kaiko120 @7401 I have one token transaction in the last 10 days.
https://etherscan.io/tx/0xc961f8875a610ed0cd581438aee2de7fd1254fc24915ddf85a79dfc071e71c36
@kaiko1203 @newbein123 @VersaillesHeroes @ashchan @kaichen @7401

**Comment by VersaillesHeroes** [comment]
@sfsy520 Can you help to merge my requests to main branch?

**Comment by VersaillesHeroes** [comment]
@beenhero @kaichen @mistricky I already fixed the issue. Can you help to merge my requests to main branch?

**Comment by VersaillesHeroes** [comment]
@zengbing15  I already fixed the issue. Can you help to merge my requests to main branch?

**Comment by VersaillesHeroes** [comment]
@kaiko1203 can you help to review my PR#7401 again?

**Comment by VersaillesHeroes** [comment]
Dear Support Team,

I have one latest token transaction today. Please refer to:
https://etherscan.io/tx/0xc961f8875a610ed0cd581438aee2de7fd1254fc24915ddf85a79dfc071e71c36
@kaiko1203 <https://github.com/kaiko1203> #7401
<https://github.com/consenlabs/token-profile/pull/7401>


Regards,


Versailles Heroes Team

**Comment by newbein123** [comment]
Yes it was successful your token has been accepted and confirmed Sent from Mail for Windows From: VersaillesHeroesSent: Monday, September 19, 2022 11:24 AMTo: consenlabs/token-profileCc: SubscribedSubject: Re: [consenlabs/token-profile] vrh-token (PR #7401) I have one latest transaction today. Please refer to: ***@***.*** #7401—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by VersaillesHeroes** [comment]
@newbein123 can you help to merge to main branch?

**Pull request merged**
