### PR TITLE
Add ERC20 token

### PR DESCRIPTION
**Pull request by Belance**
* * Project current situation: beta release https://Belance.io
* * Community Support and Feedback: https://etherscan.io/token/0xc3761eb917cd790b30dad99f6cc5b4ff93c4f9ea#comments
* * CoinMarketCap page: https://coinmarketcap.com/currencies/erc20/
* * EtherScan Page: https://etherscan.io/token/0xc3761eb917cd790b30dad99f6cc5b4ff93c4f9ea
* * Media publications: 
https://www.investing.com/crypto/erc20/news , https://news.bitcoin.com/?s=erc20 , https://coinranking.com/coin/erc20-erc20/news , https://cointelegraph.com/search?query=erc20 , https://www.bloomberg.com/search?query=erc20 , https://www.newsbtc.com/?s=erc20&lang=en 
* * Gas limit: 60,000
* * Listed exchanges: ERC20 already listed on Mercatox, Kuna, TokenStore and ForkDelta:
* Mercatox https://mercatox.com/exchange/ERC20/ETH 
* https://mercatox.com/exchange/ERC20/BTC
* KUNA  https://kuna.io/markets/erc20btc
* ForkDelta https://forkdelta.app/#!/trade/ERC20-ETH
* TokenStore https://token.store/trade/ERC20
* * Basic information of the project:  ERC20  is payment method for Belance platform, future project and application and more. Real token utility. 
Belance is a large unique blockchain platform which combines many opportunities and connects everyone in the blockchain world. The ERC20 Token is a growing currency which will be adopted as a payment gateway. Belance is a one stop place for everything and for everyone who is interested in or connected to the blockchain world
* * More about ERC20 Token
*  Website: https://index-erc20.io 
* Whitepaper: https://belance.io/aboutbelance.html 
* Twitter: https://twitter.com/ERC20_ 
* Telegram: https://t.me/erc20coin

### CODE REVIEW

**Comment by tstt** [comment]
hi，your logo is not qualified, check the "readme" tutorial.

**Comment by Belance** [comment]
> hi，your logo is not qualified, check the "readme" tutorial.

Hi @tstt , are you sure ?)

1. please use the same name as the json file. - done ✅
images/0xc3761EB917CD790B30dAD99f6Cc5b4Ff93C4F9eA.png
2.Size: 120x120 pixels. Done ✅
3. Transparent background PNG format. Done ✅
4. Brand logo horizontally and vertically centered , as shown below. Done ✅

Everything is like in readme tutorial. 



I didn’t get what exactly is not qualified🤔

**Comment by Belance** [comment]
@tstt hello, can please check ? thank you

**Comment by tstt** [comment]
like this
image

**Comment by Belance** [comment]
> like this
> image

@tstt Oh, Thank you very much! Fixed! Can you check please?)

https://github.com/Belance/token-profile/blob/063c9b52fb48d3b51c7bccf24063fbfc2255cbee/images/0xc3761EB917CD790B30dAD99f6Cc5b4Ff93C4F9eA.png 

Best Regards.

**Comment by tstt** [comment]
Welcome to recommend imToken 2.0 to your token holder to manage your token.
imToken Brand Board: https://projects.invisionapp.com/boards/GE3L46DWK2C

**Pull request merged**
