### PR TITLE
Add gamefi token

### PR DESCRIPTION
**Pull request by gamefishiba**
## Official Announcement:
√Liquidity Time ：12:00—UTC+8 (SGT) Sep 14
√OBT Time：Sep 14-Sep 24th
√Release Time：Sep. 25th
 
 
## Project team background:
We are a professional crypto game team with many years of working experience in well-known game companies. We creat 3DBTC NFT and Wired fox.
 
 
## Project basic information
✦Website: http://GameFiShiba.io
✦Token Name: GameFi (GAMEFI)
✦Number of issuances: 1 billion
✦Token Address #BSC#️ 0xc69Fc55d467EC02606eD11c63DDd7C89e24F5D84
 
## Media Publication：
[https://twitter.com/GamefiShiba/status/1440674157226643464](https://twitter.com/GamefiShiba/status/1440674157226643464)
[https://news.huoxing24.com/20210907213014470785.html](https://news.huoxing24.com/20210907213014470785.html)
[https://www.jinse.com/news/blockchain/1155370.html](https://www.jinse.com/news/blockchain/1155370.html)  
[https://www.beekuaibao.com/article/884946450737606656](https://www.beekuaibao.com/article/884946450737606656)
[http://chainstar.pro/news/10436](http://chainstar.pro/news/10436)
[http://www.pandafinance.cn/news/46653.html](http://www.pandafinance.cn/news/46653.html)
[http://www.okabcd.com/news/202109/13149837.html](http://www.okabcd.com/news/202109/13149837.html)
[https://www.biucaijing.com/article/306614/](https://www.biucaijing.com/article/306614/)
[http://www.liandaodao.cn/forum.php?mod=viewthread&tid=68251](http://www.liandaodao.cn/forum.php?mod=viewthread&tid=68251)
[http://www.52budao.com/news/viewpoint/98545.html](http://www.52budao.com/news/viewpoint/98545.html)

### CODE REVIEW

**Comment by gamefishiba** [comment]
https://twitter.com/GamefiShiba/status/1440674157226643464

**Comment by gamefishiba** [comment]
We are offical team  of GameFi Shiba，and we hope to add our  tokens info to your wallet, your early verification would be great appreciation.Thank you 

 Yours Sincerely
GameFi Shiba Team

**Comment by Leo2021zzz** [comment]
Not ERC-20 Token

**Comment by gamefishiba** [comment]
Thanks for your reply.
Leo2021zzz ***@***.***> 于2021年9月24日周五 上午10:38写道：

**Comment by gamefishiba** [comment]
If we need to submit EBP20 information,which deploy on bsc , what should we do?

**Pull request closed without merging**
