### PR TITLE
Add FLIC token

### PR DESCRIPTION
**Pull request by flicscc**
Official announcement: http://www.flics.cc/
Project team background:
The FLIC team was established in October 2019 and started design and development. The founder, Alan Lee, Ph.D., has research interests in futures payments and financial information processing. He is engaged in large-scale financial information systems and distributed application practices. Design experience. Team members have conducted in-depth research on the scalability, reliability, and elastic optimization of distributed systems. They have a deep understanding of the underlying technology and working principles of the blockchain and have practical experience.
Project basic information:
FLIC is a comprehensive service platform for digital assets that integrates one-stop secure storage management services for digital assets, intelligent financial management for digital assets and payment ecology.Build the most sturdy and powerful infrastructure in the digital financial asset industry, provide digital asset enthusiasts with the best quality, safe, convenient and efficient services, popularize the application of blockchain technology in all walks of life, open up the blockchain financial field Change in the new era! FLIC will build a strong P2P ecosystem and build a decentralized business ecosystem. By opening up the connection between digital assets and the value of physical business, connecting all walks of life, the platform token FLIC is used as a barrier-free token on the platform, with consumer flash payment function, open, transparent and decentralized.
Recommended Gas Limit (For ERC-20 project teams) for transaction:  60,000

### CODE REVIEW

**Comment by sfsy520** [comment]
In order to ensure the authenticity of the information submitted, please publish an announcement on your website or official social media channels and attach the corresponding link in “Official announcement”. We recommended a format similar to the following:
#imToken #1636 We are providing XXX token’s information on imToken. After completion, you can see the logo and full information inside imToken’s Token Manager.
Note:
* 1636 is the PR number, as in: https://github.com/consenlabs/token-profile/pull/1636 This number is the key to verify yourself as the rightful editor of the information to imToken.
* The token information can only be changed after the official verification

**Comment by tarochain** [comment]
Official announcement: http://www.flics.cc/

**Comment by flicscc** [comment]
Official announcement: http://www.flics.cc/

**Comment by sfsy520** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 管理资产。

**Pull request merged**
