### PR TITLE
Add Minershards Token

### PR DESCRIPTION
**Pull request by Khazonx**
### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

**.json 及 .png 文件检查项**
- [x ] logo 尺寸：120*120 px
- [x ] logo 背景：透明
- [x ] 代币有至少一笔成功的转账记录
- [ x] 此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
- [x ] .json 和 .png 文件名一致（包括大小写）

**项目资料：**

官方公告：https://www.facebook.com/Minershards/posts/106834447953515
团队背景：
项目基本情况：
媒体报道：https://www.facebook.com/Minershards
收录的交易所：
转账所需 Gas Limit（对 ERC-20 项目方）: 200000

---

### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [x ] logo dimensions: 120*120 px
- [x ] logo background: Transparent
- [x ] At least one transaction on the token contract
- [x ] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [x ] Same document name for both .json and .png (Including capitalization)

**Project background:**

Official announcement: https://www.facebook.com/Minershards/posts/106834447953515
Project team background:
Project basic information:
Media publications: https://www.facebook.com/Minershards
Tradeable exchanges:
Recommended Gas Limit (For ERC-20 project teams) for transaction: 200000

### CODE REVIEW

**Comment by sfsy520** [comment]
请修改state字段的值

**Comment by Khazonx** [comment]
sorry what do you mean?

**Comment by Khazonx** [comment]
Updated the gas limit. Hope that is what you meant.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by sfsy520** [comment]
state should be NORMAL or LOCKED

**Comment by Khazonx** [comment]
updated thanks

**Comment by sfsy520** [comment]
pls add website and official announcement

**Comment by Khazonx** [comment]
website and official announcement added

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by sfsy520** [comment]
In order to ensure the authenticity of the information submitted, please publish an announcement on your website or official social media channels and attach the corresponding link in “Official announcement”. We recommended a format similar to the following:
#imToken #1636 We are providing XXX token’s information on imToken. After completion, you can see the logo and full information inside imToken’s Token Manager.
Note:
* 1636 is the PR number, as in: https://github.com/consenlabs/token-profile/pull/1636 This number is the key to verify yourself as the rightful editor of the information to imToken.
* The token information can only be changed after the official verification

**Comment by Khazonx** [comment]
Already done that on december 6, 2020

https://m.facebook.com/story.php?story_fbid=106834447953515&id=106785967958363&sfnsn=mo

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Khazonx** [comment]
“Official announcement” json updated

**Comment by sfsy520** [comment]
该官方公告Facebook账户与官网不一致，无法合并。

**Pull request closed without merging**
