### PR TITLE
Jobchain

### PR DESCRIPTION
**Pull request by JobchainOfficial**
### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

**.json 及 .png 文件检查项**
- [ ] logo 尺寸：120*120 px
- [ ] logo 背景：透明
- [ ] 代币有至少一笔成功的转账记录
- [ ] 此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
- [ ] .json 和 .png 文件名一致（包括大小写）

**项目资料：**

官方公告：
团队背景：
项目基本情况：
媒体报道：
收录的交易所：
转账所需 Gas Limit（对 ERC-20 项目方）：（默认为 60000）

---

### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [ ] logo dimensions: 120*120 px
- [x] logo background: Transparent
- [x] At least one transaction on the token contract
- [x] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [x] Same document name for both .json and .png (Including capitalization)

**Project background:**

Official announcement: https://www.jobchain.com
Project team background: Jobchain Team consists of a team of experts from IO as IAEA, UN, OSCE, etc. 
Project basic information: Jobchain is an ecosystem that enables anybody to find jobs while getting their salary in cryptocurrency. 
Media publications: https://blog.jobchain.com
Tradeable exchanges: Digifinex, P2PB2B, Tagz, Vindax, 
Recommended Gas Limit (For ERC-20 project teams) for transaction: 60000

### CODE REVIEW

**Comment by sfsy520** [comment]
In order to ensure the authenticity of the information submitted, please publish an announcement on your website or official social media channels and attach the corresponding link in “Official announcement”. We recommended a format similar to the following:
#imToken #1636 We are providing XXX token’s information on imToken. After completion, you can see the logo and full information inside imToken’s Token Manager.
Note:
* 1636 is the PR number, as in: https://github.com/consenlabs/token-profile/pull/1636 This number is the key to verify yourself as the rightful editor of the information to imToken.
* The token information can only be changed after the official verification

**Comment by JobchainOfficial** [comment]
Dear SFfy520,

Dear ImToken Team,

Please find attached the official announcements in Telegram and from blog.jobchain.com

1. Telegram: https://t.me/JobchainAnnouncements
2. https://blog.jobchain.com/jobchain-r-job-token-swap/

Also, the address has been already updated in etherscan, please check:

https://etherscan.io/address/0xdfbc9050f5b01df53512dcc39b4f2b2bbacd517a

Additionally, can you please let me know what else do you need in order to have the price of the token appear in imToken?

Thank you,

The Jobchain Team
[Jobchain152 2 Logo 4 Blue (4 pt)]
Follow us on www.jobchain.com<https://nam01.safelinks.protection.outlook.com/?url=www.jobchain.com&data=02%7C01%7C%7C39f407af697e4695fe7408d6bcf173d3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636904142549580106&sdata=xOOsSFn7FJnuy%2FKOXIPGgzZUYDYd49o8OPfv9f0OI5I%3D&reserved=0>
[signature_1328568794]<http://https/twitter.com/jobchain>[signature_1405087573]<https://facebook.com/jobchainofficial>[signature_670045311]<https://instagram.com/jobchain>[Imagen que contiene imágenes prediseñadas  Descripción generada automáticamente]<https://linkedin.com/company/jobchainofficial>[signature_1228002003]<https://www.medium.com/jobchain>[signature_2003085940]<https://t.me/JobchainOfficial>

Copyright © 2020 Jobchain®, All Rights Reserved.

This email message is intended only for the use of the named recipient. Information contained in this email message and its attachments may be privileged, confidential and protected from disclosure. If you are not the intended recipient, please do not read, copy, use or disclose this communication to others. Also please notify the sender by replying to this message and then delete it from your system.



De: sfsy520 <notifications@github.com>
Responder a: consenlabs/token-profile <reply@reply.github.com>
Fecha: viernes, 31 de enero de 2020, 13:07
Para: consenlabs/token-profile <token-profile@noreply.github.com>
CC: Jobchain Team <info@jobchain.com>, Author <author@noreply.github.com>
Asunto: Re: [consenlabs/token-profile] Jobchain (#5477)


In order to ensure the authenticity of the information submitted, please publish an announcement on your website or official social media channels and attach the corresponding link in “Official announcement”. We recommended a format similar to the following:
#imToken #1636<https://github.com/consenlabs/token-profile/pull/1636> We are providing XXX token’s information on imToken. After completion, you can see the logo and full information inside imToken’s Token Manager.
Note:

  *   1636 is the PR number, as in: https://github.com/consenlabs/token-profile/pull/1636 This<https://github.com/consenlabs/token-profile/pull/1636%C2%A0This> number is the key to verify yourself as the rightful editor of the information to imToken.
  *   The token information can only be changed after the official verification

**Comment by JobchainOfficial** [comment]
Can you also please change the ticker of the old token contract to JOB_OLD and remove the logo from it?

**Comment by sfsy520** [comment]
About  the old token contract ：
Regarding Duplicated Token Names or Contract Amendment
In imToken 1.0, if duplicated token names are found, imToken team will add a number after the token name for the project, like TFT1, TFT2 etc. If you wish to remove the number, we need to claim, this is a very dangerous operation. Removing the number is not advisable, as amending the token name will cause the token to disappear from imToken display and may cause unnecessary panic among users. For tokens with many holders, we recommend the token project to suggest to your users, to download and use imToken 2.0, as imToken 2.0 distinguish tokens via contract address. Therefore, this mitigates the problem of duplicated token names.

If there are update requests due to contract amendment, follow the checklist:

make an official announcement for the upgrade of the contract
submit a new PR in GitHub:
desaturate the old logo (In Photoshop: image - adjustments - desaturate)
resubmit new token contract’s json and logo
share your announcement link under the comment section in the PR
imToken team will evaluate the situation.

**Pull request merged**
