### PR TITLE
Add GCP digital asset to imToken

### PR DESCRIPTION
**Pull request by HLFH**
Hi,

This PR https://github.com/consenlabs/token-profile/pull/4 provides more details for the ERC-20 token GCP that is only displayed after using the search button of the imToken app.

> How to be in your default Assets list to avoid having to use your search button to find the GCP token?

Can you please update the GCP with its logo on the imToken app? https://globcoin.io/assets/img/favicon-132x132.png

Right now, GCP has a default Ethereum logo on the imToken app and not the GCP logo.

So here is the PR to fix it, but `token-profile` repo is not yet documented.

Related to: https://github.com/consenlabs/token-profile/issues/3

Many thanks,
HLFH

### CODE REVIEW

**Comment by kaichen** [comment]
Hi Gaspard,

Thanks for your PR, this repo now is testing. Not accept outside contribution currently, we're review your PR when ready to launch this repo.

Many thanks.

**Comment by kaichen** [comment]
And I saw the transactions of this token on etherscan, is it really on locked state?

**Comment by HLFH** [comment]
@kaichen UNLOCKED state in fact. No explanation about `state` and its parameters on [README.md](https://github.com/consenlabs/token-profile/blob/master/README.md). If we link in the future another ERC-20 token to a token validation check such as [EIP-902](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-902.md), with offchain KYC & AML, shall we put the state as FLOAT?

I'll squash with the new commit this morning.

**Comment by HLFH** [comment]
Now in https://github.com/consenlabs/token-profile/pull/43 @kaichen

**Pull request closed without merging**
