### PR TITLE
Add dMMM token

### PR DESCRIPTION
**Pull request by d-mmm**
**Project background:**
Official websit: https://d-mmm.github.io

Official announcement: 
https://d-mmm.github.io/announcements/token-info-for-imtoken.md

Team background:
We are an international team of tech geeks from Russia, China and India.

Project basic information: 
The dMMM game is the first classic dApp on the dMMM ecosystem. In the dMMM game, players can participate in the game by paying tokens and earn income when they wait in line to end the game. In the process of continuously participating in the game, the player account can be upgraded to obtain more interesting and tangible benefits or rewards.

Recommended Gas Limit for transaction:  420000

### CODE REVIEW

**Comment by sfsy520** [comment]
请按要求提交具体有效的Json内容，无内容参数可删除。

**Comment by d-mmm** [comment]
> 请按要求提交具体有效的Json内容，无内容参数可删除。

Done.

**Comment by sfsy520** [comment]
请在官网添加跳转至官方公告的链接。

**Comment by sfsy520** [comment]
非常抱歉，由于该PR长时间未更新，我们先关闭这个PR
如果仍需提交，请参考教程重新提交：
https://github.com/consenlabs/token-profile#token-profile-guideline

**Pull request closed without merging**
