### PR TITLE
Add combo token

### PR DESCRIPTION
**Pull request by FMANET**
### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

**.json 及 .png 文件检查项**
- [ ] logo 尺寸：120*120 px
- [ ] logo 背景：透明
- [ ] 代币有至少一笔成功的转账记录
- [ ] 此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
- [ ] .json 和 .png 文件名一致（包括大小写）

**项目资料：**

官方公告：
团队背景：
项目基本情况：
媒体报道：
收录的交易所：
转账所需 Gas Limit（对 ERC-20 项目方）：（默认为 60000）

---

### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [ ] logo dimensions: 120*120 px
- [ ] logo background: Transparent
- [ ] At least one transaction on the token contract
- [ ] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [ ] Same document name for both .json and .png (Including capitalization)

**Project background:**
Mark believes the world should be easy for middle or average income earners as well as poor people. He beleives tge aim of decentralization that was birthed by crypto is to bring ease for people day in day out. Mark sees payments of bills to listen to radio while driving watching tv while at home isnnt fair as the exorbitant fee is outrageous and many poor people wont have the capability to pay. This gave birth to combo to take care of this aspect. Read more on website 
Official announcement: https://T.me/comboann 

Media publications: https://Combocoin.online/blog
Tradeable exchanges: Saturn.network, Kucoin.com
Recommended Gas Limit (For ERC-20 project teams) for transaction: (Default is 60,000)

### CODE REVIEW

**Comment by sfsy520** [comment]
Logo要求如下：
* * 尺寸: 120x120 像素
* * 图片为透明背景的 PNG 格式
* * 品牌标识水平竖直居中顶边

**Comment by laoma6** [comment]
white paper, website construction, security audit report. The lowest price in the whole network! If you need ，please add the wechat ：laoma1145, please delete it if you are disturbed, thank you.

**Comment by laoma6** [comment]
Blockchain technology service, imtoken submission, token issuance, white paper, website construction, security audit report. The lowest price in the whole network! If you need ，please add the wechat ：laoma1145, please delete it if you are disturbed, thank you.

**Comment by sfsy520** [comment]
非常抱歉，由于该PR长时间未更新，我们先关闭这个PR
如果仍需提交，请参考教程重新提交：
https://github.com/consenlabs/token-profile#token-profile-guideline

**Pull request closed without merging**
