### PR TITLE
Add 99X token

### PR DESCRIPTION
**Pull request by Xinshu1314**
----------------------------------------ch----------------------------------------
**团队背景：**
99X是初期项目Natasha计划的通行证代表，创办方为线下实体公司：广州心术科技有限公司，坐落于广州黄浦区，致力于研发区块链，AI算法，曾在计算机研讨大会提出《人与自然》的相关理念，研发人员来自各大精英人才，广大的理念，受到做多的合作方咨询合作，截至到2020.1.7，目前合作方实体商品高达150+，社区人数7500+，用公开透明无法逆转的，维护用户权益，打造人与自然，这才是项目方的唯一理念。
**项目基本情况：**
99X是作为Natasha计划的通行证，很简单的来讲，用户加入Natasha计划，用户会得到为期 1 个月的健康保障和等值 99X 代币的反馈，Natasha计划理念，取决于今年爆发的疾病，传染性极高，各地方各国出现口罩救护服等物资稀缺，人民在家无法出门，出门采购需要口罩，但口罩的稀缺引来了一些无良商家，为杜绝哄抬物价，决定用户期间若受到不可抗拒或天灾人祸之时，提供相应救护。
更多关于99X:
官网地址：https://www.xinshulnc.xin  或者 http://154.8.217.135
软件下载：https://www.99xin.xin 或者 http://47.92.200.77
企业电话：4008833206
企业邮箱：xinshulnc@cherishhan.com
微信平台：SCIENCEAT
**媒体报道**
金色财经：https://www.jinse.com/blockchain/616939.html
币乎：https://bihu.com/article/1989310226
**建议 gas limit：60000**
**收录的交易所**
99X Labs
----------------------------------------en----------------------------------------
**Team background:**
99x is the passport representative of Natasha plan of the initial project. Its founder is offline entity company: Guangzhou Xinshu Technology Co., Ltd., located in Huangpu District, Guangzhou, devoted to the research and development of blockchain and AI algorithm. It has put forward the relevant concept of "man and nature" in the computer seminar. The research and development personnel come from various elites, and the broad concept is consulted and cooperated by many partners, Up to January 7, 2020, the number of partners' physical goods is up to 150 + and the number of community members is 7500 +. The only idea of the project party is to safeguard the rights and interests of users and create people and nature with openness and transparency.
**Basic information of the project:**
99x is the passport of Natasha plan. In a very simple way, when users join the Natasha plan, they will get one month's health insurance and 99x equivalent Token feedback, Natasha plan concept, depends on this year's outbreak of disease, highly infectious, there is a shortage of masks, rescue clothing and other materials in various countries, people can't go out at home, go out to purchase masks, but the scarcity of masks has attracted some unscrupulous businesses, to bid up prices for Du Jue, to decide if users are irresistible or natural or man-made disasters, to provide corresponding rescue Protect.
More about 99x:
Official website address: https://www.xinshulnc.xin or http://154.8.217.135
Software download: https://www.99xin.xin or http://47.92.200.77
Tel: 4008833206
Email: xinshulnc@cherishhan.com
Wechat platform: scienceat
**Media coverage**
Golden Finance: https://www.jinse.com/blockchain/616939.html
Currency: https://bihu.com/article/1989310226
**Recommended gas limit: 60000**
**Included exchanges:**
99X Labs

### CODE REVIEW

**Comment by Xinshu1314** [comment]
如果遇见官网无法打开请打开，说明网站在维护，请打开IP地址http://154.8.217.135
谢谢

**Comment by Xinshu1314** [comment]
官网已同步文章，在中间新闻中心，显示 99X token #5672

**Comment by WX-laoma1145** [comment]
> ----------------------------------------ch----------------------------------------
> **团队背景：**
> 99X是初期项目Natasha计划的通行证代表，创办方为线下实体公司：广州心术科技有限公司，坐落于广州黄浦区，致力于研发区块链，AI算法，曾在计算机研讨大会提出《人与自然》的相关理念，研发人员来自各大精英人才，广大的理念，受到做多的合作方咨询合作，截至到2020.1.7，目前合作方实体商品高达150+，社区人数7500+，用公开透明无法逆转的，维护用户权益，打造人与自然，这才是项目方的唯一理念。
> **项目基本情况：**
> 99X是作为Natasha计划的通行证，很简单的来讲，用户加入Natasha计划，用户会得到为期 1 个月的健康保障和等值 99X 代币的反馈，Natasha计划理念，取决于今年爆发的疾病，传染性极高，各地方各国出现口罩救护服等物资稀缺，人民在家无法出门，出门采购需要口罩，但口罩的稀缺引来了一些无良商家，为杜绝哄抬物价，决定用户期间若受到不可抗拒或天灾人祸之时，提供相应救护。
> 更多关于99X:
> 官网地址：https://www.xinshulnc.xin 或者 http://154.8.217.135
> 软件下载：https://www.99xin.xin 或者 http://47.92.200.77
> 企业电话：4008833206
> 企业邮箱：[xinshulnc@cherishhan.com](mailto:xinshulnc@cherishhan.com)
> 微信平台：SCIENCEAT
> **媒体报道**
> 金色财经：https://www.jinse.com/blockchain/616939.html
> 币乎：https://bihu.com/article/1989310226
> **建议 gas limit：60000**
> **收录的交易所**
> 99X Labs
> ----------------------------------------en----------------------------------------
> **Team background:**
> 99x is the passport representative of Natasha plan of the initial project. Its founder is offline entity company: Guangzhou Xinshu Technology Co., Ltd., located in Huangpu District, Guangzhou, devoted to the research and development of blockchain and AI algorithm. It has put forward the relevant concept of "man and nature" in the computer seminar. The research and development personnel come from various elites, and the broad concept is consulted and cooperated by many partners, Up to January 7, 2020, the number of partners' physical goods is up to 150 + and the number of community members is 7500 +. The only idea of the project party is to safeguard the rights and interests of users and create people and nature with openness and transparency.
> **Basic information of the project:**
> 99x is the passport of Natasha plan. In a very simple way, when users join the Natasha plan, they will get one month's health insurance and 99x equivalent Token feedback, Natasha plan concept, depends on this year's outbreak of disease, highly infectious, there is a shortage of masks, rescue clothing and other materials in various countries, people can't go out at home, go out to purchase masks, but the scarcity of masks has attracted some unscrupulous businesses, to bid up prices for Du Jue, to decide if users are irresistible or natural or man-made disasters, to provide corresponding rescue Protect.
> More about 99x:
> Official website address: https://www.xinshulnc.xin or http://154.8.217.135
> Software download: https://www.99xin.xin or http://47.92.200.77
> Tel: 4008833206
> Email: [xinshulnc@cherishhan.com](mailto:xinshulnc@cherishhan.com)
> Wechat platform: scienceat
> **Media coverage**
> Golden Finance: https://www.jinse.com/blockchain/616939.html
> Currency: https://bihu.com/article/1989310226
> **Recommended gas limit: 60000**
> **Included exchanges:**
> 99X Labs

区块链技术服务，imtoken提交，发行代币，白皮书，logo设计，网站建设，安全审计报告。全网最低价！需要的加微信laoma1145，也欢迎各种商务合作，对接交易所等。如有打扰请删除，实在抱歉，谢谢。

Blockchain technology service, imtoken submission, Token issuance, White paper,Logo design, Website construction, Security audit report. The lowest price in the whole network! If you need，please add my wechat ：laoma1145 . And also welcome all kinds of business cooperation, docking exchanges, etc. Please delete if you are disturbed. I'm sorry, thank you.

**Comment by Xinshu1314** [comment]
@sfsy520 帮忙审核下呗

**Comment by sfsy520** [comment]
请检查Json文件是否符合要求，我这边看到的是空白的。

**Pull request closed without merging**
