### PR TITLE
Add XLDZ token

### PR DESCRIPTION
**Pull request by sbrendtro**
### Please check the following to ensure a successful verification of Token Profile
**.json and .png document checklists**

* [x]  logo dimensions: 120*120 px
* [x]  logo background: Transparent
* [x]  At least one transaction on the token contract
* [x]  For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
* [x]  Same document name for both .json and .png (Including capitalization)

**Project background:**

Official announcement: https://ld2coin.io

Project team background:
The LD2 team is located in the United States and Asia. Extra von NotHaus, Co-founder and CEO has over twenty years of experience in precious metals markets, alternative/digital currencies, international banking and Fintech, and was a founding member of multiple start-ups, in addition to developing the first graduate-level course on Blockchain at Northeastern University. Steven Brendtro, Co-founder and CTO has over twenty years of experience in alternative/digital currencies, payment processing, software engineering, systems architecture, and DevOps engineering, and founded multiple software, Fintech and KYC/AML start-ups, along with building an asset-backed debit card platform and serving as Regional Currency Officer for the Liberty Dollar. Bernard von NotHaus, Monetary Strategist, has over forty years of experience in precious metals markets, and was Monetary architect for the Liberty Dollar, where he issued over 50M USD of silver into circulation. Shawn Tham, Marketing Manager, oversees LD2 marketing in Asia and has over 20 years of experience in various industries from construction, insurance, and blockchain, working in sales, business development, and advisory roles.

Project basic information:
LD2 is an asset-backed cryptocurrency that facilitates vaulted, physical ownership of redeemable precious metals and real-time trading of those assets. Based on the most successful alternative currency in the history of the United States, Liberty Dollar, LD2 reimagines that economic model as a cryptocurrency. LD2 functions as a “stablecoin”, 100% backed by precious metals. Each token issued represents one Troy ounce of .999 fine physical silver stored in a secure vault, examined monthly by an independent auditor. As a digital warehouse receipt, every LD2 token is redeemable through the third-party depository for the precious metal on deposit. Physical redemption not only structures LD2’s economics and value proposition but builds trust with token holders, something badly needed within the existing cryptocurrency market/ecosystem.

Media publications:
[One Page Summary](https://ld2coin.io/wp-content/uploads/2018/05/LD2.zero_One-Pager.pdf)
[White Paper](https://ld2coin.io/wp-content/uploads/2018/05/LD2_White_Paper.pdf)
[Coin World Article](https://www.coinworld.com/news/precious-metals/liberty-dollar-becomes-silver-backed-cryptocurrency.html)

Tradeable exchanges:
Recommended Gas Limit (For ERC-20 project teams) for transaction: 60,000

### CODE REVIEW

**Comment by sbrendtro** [comment]
Posted pull request on both Twitter and Telegram

**Comment by sfsy520** [comment]
为确保资料提交的真实性，请在贵方官网或其他经过认证的社交媒体渠道发布公告，并将此公告链接附于「官方公告」。推荐文案：
#imToken# #1636# 我们正在完善 XXX 在 imToken 中的代币相关资料。完成后，大家可以在 imToken 里看到 logo，更方便地管理 XXX，同时能看到更多代币信息。
注：
* 1636 为 pr 序号，如 https://github.com/consenlabs/token-profile/pull/1636 的序号为 1636，这是帮助 imToken 判断 pr 真实性的关键。
* #imToken #1636 标签及其展示形式可自行调整。
* 若未提供「官方公告」，则无法显示代币信息

**Comment by sbrendtro** [comment]
We published this announcement on Twitter here:  https://twitter.com/Ld2Coin/
https://twitter.com/Ld2Coin/status/1182397583324598272

We also published it on our Telegram:
https://t.me/libertydollar2/205

**Comment by sfsy520** [comment]
Welcome to recommend imToken 2.0 to your token holders to manage their token.

**Pull request merged**
