### PR TITLE
add MOS token

### PR DESCRIPTION
**Pull request by MetaOasisDAO**
### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

**.json 及 .png 文件检查项**
- [x] logo 尺寸：120*120 px
- [x] logo 背景：透明
- [x] 代币有至少一笔成功的转账记录
- [x] 此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
- [x] .json 和 .png 文件名一致（包括大小写）

项目资料：

**官方公告**: https://www.metaoasis.fun/official-announcement

**团队背景**：创始团队是具有扎实教育背景的区块链资深人士，曾就职于全球顶级交易所和全球顶级投资银行，曾为DeHorizon、JennyDao、Alien Worlds提供咨询服务；在投资银行和区块链的各种国际项目中拥有宝贵的工作经验。 合作的设计工作室是哈佛毕业的资深设计人士。

**项目基本情况**：MetaOasis DAO旨在开启元宇宙中虚拟房地产投资与开发的新纪元，同时成为通过投资和开发土地的方式来打开元宇宙所有权的门户。目标是提供一种更便捷的方式来共同投资、开发和合作社区拥有的元宇宙土地和房地产资产。因此每个人，甚至是资本资源有限的人，都可以有机会参与并为元宇宙的发展做出贡献，并从这个快速增长的行业中获利。MetaOasis DAO的资产组合里面已经有超过20+的元宇宙地块；DAO的Sandbox总部建设如火如荼，主流的社区粉丝已达到3万+。

**媒体报道**：[Cointelegraph](https://security.larksuite.com/link/safety?target=https%3A%2F%2Fcointelegraph.com%2Fpress-releases%2Fmetaoasis-dao-aims-to-start-a-new-paradigm-of-virtual-real-estate-investment-and-development-in-the-metaverse&scene=ccm&logParams=%7B%22location%22%3A%22ccm_docs%22%7D&lang=zh-CN), [Yahoo Finance](https://finance.yahoo.com/news/metaoasis-dao-partner-season-studio-113000186.html), [AI technology insights](https://aithority.com/technology/blockchain/nft/metaoasis-dao-and-its-partner-season-studio-unveil-amazing-designs-of-the-daos-hq-in-the-sandbox/), [Businesswire](https://www.businesswire.com/news/home/20220124005272/en/MetaOasis-DAO-and-its-partner-Season-Studio-unveil-amazing-designs-of-the-DAOs-HQ-in-the-Sandbox), [Bakersfield](https://www.bakersfield.com/ap/news/metaoasis-dao-and-its-partner-season-studio-unveil-amazing-designs-of-the-daos-hq-in/article_b1cbb49c-4a74-55c1-b28d-4dcb68da8458.html)

**转账所需 Gas Limit**（对 ERC-20 项目方）：（默认为 60000）

---

### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [x] logo dimensions: 120*120 px
- [x] logo background: Transparent
- [x] At least one transaction on the token contract
- [x] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [x] Same document name for both .json and .png (Including capitalization)

Project background:

**Official announcement**: https://www.metaoasis.fun/official-announcement

**Project team background**: Founding contributors are blockchain veterans with solid education background, previously worked for Bithumb, Bybit and top global investment banks, advised on DeHorizon, JennyDao, Alien Worlds; had valuable experience working on a variety of international projects in finance, blockchain, DeFi and GameFi. Partnered Art Design studio consists of seasoned world-famous designers.

**Project basic information**: MetaOasis DAO is starting a new paradigm of virtual real estate investment and development in the age of the metaverse. The project aims to be a gateway of ownership in the metaverse through investment and development of the lands. The goal is to provide a more accessible means to invest, develop and collaborate on community-owned metaverse lands and real estate together, so everyone, even people with limited capital resources, can have the opportunity to participate and contribute to the evolution of the metaverse and to share the returns from this rapidly growing sector. MetaOasis DAO has now purchased more than 20+ metaverse plots in its asset portfolio; headquarter in the Sandbox is under development. The project has more than 30k followers on the mainstream communities.

**Media publications**: [Cointelegraph](https://security.larksuite.com/link/safety?target=https%3A%2F%2Fcointelegraph.com%2Fpress-releases%2Fmetaoasis-dao-aims-to-start-a-new-paradigm-of-virtual-real-estate-investment-and-development-in-the-metaverse&scene=ccm&logParams=%7B%22location%22%3A%22ccm_docs%22%7D&lang=zh-CN), [Yahoo Finance](https://finance.yahoo.com/news/metaoasis-dao-partner-season-studio-113000186.html), [AI technology insights](https://aithority.com/technology/blockchain/nft/metaoasis-dao-and-its-partner-season-studio-unveil-amazing-designs-of-the-daos-hq-in-the-sandbox/), [Businesswire](https://www.businesswire.com/news/home/20220124005272/en/MetaOasis-DAO-and-its-partner-Season-Studio-unveil-amazing-designs-of-the-DAOs-HQ-in-the-Sandbox), [Bakersfield](https://www.bakersfield.com/ap/news/metaoasis-dao-and-its-partner-season-studio-unveil-amazing-designs-of-the-daos-hq-in/article_b1cbb49c-4a74-55c1-b28d-4dcb68da8458.html)

**Recommended Gas Limit** (For ERC-20 project teams) for transaction: (Default is 60,000)

### CODE REVIEW

**Comment by evelyn2331** [comment]
Hi, Official announcement is needed to check you are the official to hand up this information. You can follow this tutorial https://github.com/consenlabs/token-profile/blob/master/tutorial/erc20-tutorial.en.md#completeness-and-accuracy-of-the-information.

**Comment by MetaOasisDAO** [comment]
@evelyn2331 Hi, official announcement is now available here: https://metaoasis.fun/official-announcement

**Comment by evelyn2331** [comment]
OK, we have received your announcement, but we need more infromationg about your project, the tutorial https://github.com/consenlabs/token-profile/blob/master/tutorial/erc20-tutorial has detail please follow that. Thank you very much.

**Comment by MetaOasisDAO** [comment]
@evelyn2331 More information updated, could you please have a check?

**Pull request merged**
