### PR TITLE
add UTLC token

### PR DESCRIPTION
**Pull request by utlctoken**
### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

**.json 及 .png 文件检查项**
- [x] logo 尺寸：120*120 px
- [x] logo 背景：透明
- [x] 代币有至少一笔成功的转账记录
- [x] 此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
- [x] .json 和 .png 文件名一致（包括大小写）

**项目资料：**

团队背景：UTLC团队由一支经验丰富的大健康产业营销团队以及资深区块链开发团队联合创立的社区，是由在大健康产业链生产、科研、流通、服务等环节方面有着丰富经验的人才组成
项目基本情况：UTLC技术团队目前正在为联盟通证投资提供高速的服务通道，为企业和投资者搭建良好的线上交易环境，积极打造联盟通证高品质生活社区自然生态，同时运营团队也在开设新的UTLC市场运营节点
媒体报道：
收录的交易所：比特QQ
转账所需 Gas Limit（对 ERC-20 项目方）：（默认为 60000）

---

### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [x] logo dimensions: 120*120 px
- [x] logo background: Transparent
- [x] At least one transaction on the token contract
- [x] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [x] Same document name for both .json and .png (Including capitalization)

**Project background:**

Project team background:The UTLC team is jointly established by an experienced large health industry marketing team and a senior blockchain development team. It is composed of talents with rich experience in the production, research, circulation and service of the big health industry chain.
Project basic information:UTLC technology team is currently providing high-speed service channels for alliance licensing investment, building a good online trading environment for enterprises and investors, actively building the natural ecology of high-quality life community of alliance licensing, and the operation team is also opening new UTLC market operation nodes.
Media publications:
Tradeable exchanges:bitqq
Recommended Gas Limit (For ERC-20 project teams) for transaction: (Default is 60,000)

### CODE REVIEW

**Comment by utlctoken** [comment]
add UTLC token

**Comment by tstt** [comment]
https://github.com/consenlabs/token-profile/blob/master/tutorial/erc20-tutorial.zh-CN.md#%E8%B5%84%E6%96%99%E7%9A%84%E5%AE%8C%E6%95%B4%E5%92%8C%E5%87%86%E7%A1%AE

image

**Comment by utlctoken** [comment]
> [https://github.com/consenlabs/token-profile/blob/master/tutorial/erc20-tutorial.zh-CN.md#%E8%B5%84%E6%96%99%E7%9A%84%E5 ％AE％8C％E6％95％B4％E5％92％8C％E5％87％86％E7％A1％AE](https://github.com/consenlabs/token-profile/blob/master/tutorial/erc20-tutorial.zh-CN.md#%E8%B5%84%E6%96%99%E7%9A%84%E5%AE%8C%E6%95%B4%E5%92%8C%E5%87%86%E7%A1%AE)
> 
> 图片

您好，UTLC项目已经发布公告，
公告链接：http://www.utlc.io/%EA%B3%B5%EA%B3%A0.htm

**Comment by tstt** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 管理资产。

**Pull request merged**
