### PR TITLE
Add DNA token

### PR DESCRIPTION
**Pull request by hgbc-io**
### 官方公告：
[http://news.hgbc.io/articles/2019/07/07/1562496139955.html](http://news.hgbc.io/articles/2019/07/07/1562496139955.html)

### 团队背景：
项目核心团队由遗传学、生物学、计算机、生物信息以及区块链背景的资深人士组成，在全基因组数据分析、解读和基因应用的开发方面具有丰富的经验。
### 项目基本情况：
DNA项目（原迅雷链上的HGBC项目）是国内基因行业里最早从事基因大数据、基因区块链业务的探索者，由一群具备遗传学、生物学、计算机、生物信息、大数据背景的专业人士发起，致力于通过基因大数据技术、基因区块链技术改善大众健康。DNA项目核心团队成员来自于/曾服务于中国科学院、北京大学、阿里巴巴等知名机构，长期专注于全基因组数据分析、解读和基因应用的开发，其自主研发的基因组云分析和解读服务（Genome Analysis and Interpretation in Cloud）GAIC能够以更快的速度、更低的成本完成人类基因组数据的分析和解读，并参与了国家“精准医疗”项目。
We are almost the first explorer in the domestic genetic industry to work on gene big data and gene blockchain business. Our team is sponsored by a group of professionals with backgrounds in genetics, biology, computers, bioinformatics, and big data. We are committed to improving public health through gene big data technology and gene blockchain technology. Our core team members have come from / have served in the Chinese Academy of Sciences, Peking University, Alibaba and other well-known institutions, long-term focus on genome-wide data analysis, interpretation and development of genetic applications. Our self-researched genomic cloud analysis and interpretation services (genomic analysis and interpretation in the cloud) can perform analysis and interpretation of human genome data at a faster rate and at a lower cost, and participate in the national “precise medical” project.
DNA项目正在基因行业建立一个新的生态系统，以用户为核心，基因测序公司、基因产品/服务提供商以及项目方共同参与。我们使用分布式存储和加密技术来解决基因数据隐私和安全问题。我们和其他第三方基因产品/服务提供商在平台上开发各种基因应用（基因产品/服务），用于营养饮食、运动健康、皮肤护理、健康管理、药物开发、血缘确认等，第三方研究机构可以在平台上发布项目使用用户的基因组数据进行科学研究。平台上的一切交易用通证来结算，通过经济激励使参与各方都能够从数字资产获益，全面加速对人类遗传信息宝库的探索。
We are establishing a new ecosystem in gene industry with users as the core, gene sequencing companies, gene product and service providers and project parties. We use distributed storage and encryption technology to solve the gene data privacy and security issues. We and other third-party genetic testing companies can develop a variety of gene applications on the platform for nutritional diet, exercise, skin care, health management, drug development, parental recognition, and scientific research, allowing individuals to obtain the benefits of digital assets by Token stimulus while accelerating the exploration of genetic technology. With the rapid development of genome sequencing technology, the cost of personal genome sequencing is rapidly decreasing, and personal genome data will become an important digital asset for everyone. After an individual has ownership of personal genomic data and is free and easy to control personal genomic data, economic and social value will be realized for individuals and businesses.

### 媒体报道：
中国日报网：HGBC在迅雷链完成全链条部署，基因+区块链将迎快速发展    
http://cn.chinadaily.com.cn/2018qklfnzl/2018-11/22/content_37299466.htm
耳朵财经：HGBC打造国内首家落地基因区块链项目  
http://www.iterduo.com/posts/40524
搜狐财经：HGBC亮相迅雷区块链生态及新品发布会  
https://www.sohu.com/a/233162593_100179423
看基因：基因区块链HGBC发行“健康积分”，并正式上线链克口袋
http://www.kanjiyin.com/p910/20180816/34622.html
凤凰网：基因区块链HGBC—让基因数据成为你的数字资产
http://wemedia.ifeng.com/60831504/wemedia.shtml
创头条：达尔文星球上线！看HGBC团队如何用区块链重塑基因行业
http://www.ctoutiao.com/900114.html
36氪：基因测序+区块链想象空间有多大？基因价值链HGBC要平台也要做服务商
https://36kr.com/p/5160898

收录的交易所：
转账所需 Gas Limit（对 ERC-20 项目方）：（默认为 60000）

Recommended Gas Limit (For ERC-20 project teams) for transaction: (Default is 60,000)

### CODE REVIEW

**Comment by tstt** [comment]
https://github.com/consenlabs/token-profile/blob/master/tutorial/erc20-tutorial.zh-CN.md#%E5%85%B7%E4%BD%93%E5%A6%82%E4%BD%95%E6%93%8D%E4%BD%9C

image

**Comment by tstt** [comment]
image

**Comment by hgbc-io** [comment]
I hava checksum pass

**Comment by tstt** [comment]
image

**Comment by hgbc-io** [comment]
@tstt delete 0x286f0322164f532f388dac8bce2a5101d92a3475.png done

**Comment by tstt** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 管理资产。

**Pull request merged**
