### PR TITLE
Add USDH Token

### PR DESCRIPTION
**Pull request by chronosone**
**项目资料：**

官方公告
https://twitter.com/thehonestnode/status/1173539381400834050
https://www.facebook.com/thehonestnode/posts/522712108484165

团队背景：
HonestNode 团队兼具互联网、金融、区块链的经验和背景，由数位成功的连续创业者以及来自腾讯、Uber、鼎晖、瑞银、哈佛、北大、清华等公司或学校的成员构成。

项目基本情况：
HonestCoin 是合规且可自由兑换的美元稳定币，是真正的区块链上的美元，定位于应用在现实世界的场景中，解决现实世界的问题。通过 HonestCoin ，我们希望让世界各地的资产可以安全、高效、低成本的流通，冲破各种外界的限制，去除所有不必要的中间环节，让资产的拥有者真正掌控自己的财富。

媒体报道：
http://www.bizleader.cn/renwu/201907236440.html
https://finance.sina.com.cn/stock/relnews/us/2019-06-25/doc-ihytcitk7583049.shtml
https://news.huoxing24.com/20190614140957121200.html
http://shilian.com/zixun/kuaixun/30236.html
https://medium.com/@honestnode123/the-first-bch-based-regulated-stable-coin-honestcoin-goes-live-142358fa4e56

收录的交易所：
暂无

转账所需 Gas Limit（对 ERC-20 项目方）：
60000

---
**Project background:**

Official announcement:
https://twitter.com/thehonestnode/status/1173539381400834050
https://www.facebook.com/thehonestnode/posts/522712108484165

Project team background:
The HonestNode team combines experience and background in the Internet, finance, and blockchain, and is comprised of several successful serial entrepreneurs and members of companies or schools from Tencent, Uber, CDH, UBS, Harvard, Peking University, and Tsinghua University.

Project basic information:
HonestCoin is a U.S. Dollar-backed stablecoin that is fully regulated and has no limitation in redemption. It is created for real world scenarios to solve real world problems.

HonestCoin aims at enabling capital around the world to move safely and efficiently with low cost, eliminating unnecessary restrictions, and bypass costly intermediaries, so that asset holders can truly have total control over their global asset.

Media publications:
http://www.bizleader.cn/renwu/201907236440.html
https://finance.sina.com.cn/stock/relnews/us/2019-06-25/doc-ihytcitk7583049.shtml
https://news.huoxing24.com/20190614140957121200.html
http://shilian.com/zixun/kuaixun/30236.html
https://medium.com/@honestnode123/the-first-bch-based-regulated-stable-coin-honestcoin-goes-live-142358fa4e56

Tradeable exchanges:
None available yet

Recommended Gas Limit (For ERC-20 project teams) for transaction: 
60000

### CODE REVIEW

**Comment by sfsy520** [comment]
为确保资料提交的真实性，请在贵方官网或其他经过认证的社交媒体渠道发布公告，并将此公告链接附于「官方公告」。推荐文案：
#imToken# #1636# 我们正在完善 XXX 在 imToken 中的代币相关资料。完成后，大家可以在 imToken 里看到 logo，更方便地管理 XXX，同时能看到更多代币信息。
注：
* 1636 为 pr 序号，如 https://github.com/consenlabs/token-profile/pull/1636 的序号为 1636，这是帮助 imToken 判断 pr 真实性的关键。
* #imToken #1636 标签及其展示形式可自行调整。
* 若未提供「官方公告」，则无法显示代币信息

**Comment by chronosone** [comment]
官方公告

**Comment by chronosone** [comment]
官方公告
https://twitter.com/thehonestnode/status/1173539381400834050
https://www.facebook.com/thehonestnode/posts/522712108484165
@sfsy520

**Comment by sfsy520** [comment]
由于贵方是稳定币项目，请提供更权威的媒体报道。

**Pull request merged**
