### PR TITLE
Add Coinway Token

### PR DESCRIPTION
**Pull request by coinwaycan**
**.json and .png document checklists**
- [x] logo dimensions: 120*120 px
- [x] logo background: Transparent
- [x] At least one transaction on the token contract
- [x] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [x] Same document name for both .json and .png (Including capitalization)

**Project background:**

Coinway has a unique concept for Network & Creative Marketing
and will change how it is done for good, through the use of
blockchain technology based eco-system of tools and services
designed for the world.
As you are aware the crypto world has taken the planet by storm
over the last few years and is developing into one of the world's
major players within finance, business and investment.
Official announcement:https://coinwaycan.com
Project team background:https://www.coinwaygroups.com
Media publications:https://www.reddit.com/user/Coinway_Official
Tradeable exchanges:https://exchange.bitsten.com/market/can_usdt
Recommended Gas Limit 60000

### CODE REVIEW

**Comment by coinwaycan** [comment]
Announcement link :https://github.com/coinwaycan/Iam-Token-/blob/master/README.md
Etherscan link :https://etherscan.io/token/0x917FD2f7378FF479419dCB56C5cbB445fBbF902A

**Comment by sfsy520** [comment]
请在官网添加可以跳转至官方公告的链接

**Comment by coinwaycan** [comment]
Official announcement :https://twitter.com/COINWAYCAN/status/1316303574108864512?s=08

**Comment by sfsy520** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 ，imToken 支持比特币, 以太坊, Comos, EOS, 波场, Nervos, 比特币现金, 莱特币，波卡等资产管理；同时支持去中心化币币兑换功能 Tokenlon；转账页面支持 ETH, USDT, EOS, BTC OTC 功能；另外对于没有 ETH 矿工费的用户，也提供 ETH 手续费充值功能。

**Pull request merged**
