### PR TITLE
Add PZS token

### PR DESCRIPTION
**Pull request by alexengy**
Official announcement: https://pizzaswap.info/
Project team background:
PZS's core technical team and investors are from various well-known areas of blockchain. The core technology comes from Singapore's professional blockchain technology. The team is composed of a group of senior blockchain technicians, all of whom have many years of blockchain development experience. Many of them come from well-known universities in the United States and have participated in many Development of blockchain projects.
Project basic information:
PizzaSwap is a standardized, market-oriented, and decentralized digital financial platform with embedded Defi modules such as DEX, NFT, liquidity mining, two-way lending, and convenient payment.PZS is used in the construction of the important core basic link of Pizza Swap exchange ecology, and its stable value and circulation attributes are suitable for diversified ecological applications. PZS is open to the PZ mining pool. PZS can be mined through PZS single pledge, and rewards for early ecological development contributors are pizza (PIZZA)! In the future, PZS will rely on PizzaSwap's powerful new Defi application ecosystem (DEX, NTF, liquid mining) Mining, two-way pledge mining, exchange mainstream currency, secondary trading market), establish a strong liquidity consensus and stable value.
Recommended Gas Limit (For ERC-20 project teams) for transaction: 60,000

### CODE REVIEW

**Comment by sfsy520** [comment]
Logo不符合要求

**Comment by alexengy** [comment]
Logo已修改，麻烦重新审核一下，谢谢！

**Comment by sfsy520** [comment]
非常抱歉，若未取得商务合作，请移除官网WALLET PARTNERS中「imToken」信息

**Comment by alexengy** [comment]
不好意思，已经移除了「imToken」信息，麻烦重新审核一下，谢谢！

**Comment by sfsy520** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 ，imToken 支持比特币, 以太坊, Comos, EOS, 波场, Nervos, 比特币现金, 莱特币，波卡等资产管理；同时支持去中心化币币兑换功能 Tokenlon；转账页面支持 ETH, USDT, EOS, BTC OTC 功能；另外对于没有 ETH 矿工费的用户，也提供 ETH 手续费充值功能。

**Pull request merged**
