### PR TITLE
Add coinway token

### PR DESCRIPTION
**Pull request by coinwaycan**
**.json and .png document checklists**
- [✔️ ] logo dimensions: 120*120 px
- [✔️ ] logo background: Transparent
- [✔️ ] At least one transaction on the token contract
- [✔️ ] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [ ✔️] Same document name for both .json and .png (Including capitalization)

Coinway has a unique concept for Network & Creative Marketing
and will change how it is done for good, through the use of
blockchain technology based eco-system of tools and services
designed for the world.
As you are aware the crypto world has taken the planet by storm
over the last few years and is developing into one of the world's
major players within finance, business and investment.
Official announcement:https://coinwaycan.com
Project team background:https://www.coinwaygroups.com
Media publications:https://www.reddit.com/user/Coinway_Official
Tradeable exchanges:https://exchange.bitsten.com/market/can_usdt
Recommended Gas Limit 60000

### CODE REVIEW

**Comment by coinwaycan** [comment]
Announcement link :https://github.com/coinwaycan/Iam-Token-

**Comment by sfsy520** [comment]
请检查合约checksum格式。

**Comment by coinwaycan** [comment]
https://etherscan.io/token/0x917FD2f7378FF479419dCB56C5cbB445fBbF902A verified on etherscan also please update it

**Comment by sfsy520** [comment]
请检查合约checksum格式，图片名称也需要检查。

**Comment by coinwaycan** [comment]
> 请检查合约checksum格式，图片名称也需要检查。

**Pull request closed without merging**
