### PR TITLE
XSGD token

### PR DESCRIPTION
**Pull request by liewjiajun**
### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [X] logo dimensions: 120*120 px
- [X] logo background: Transparent
- [X] At least one transaction on the token contract
- [X] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [X] Same document name for both .json and .png (Including capitalization)

**Project background:**

Official announcement:
Project team background:
Project basic information: StraitsX is the stablecoin initiative for Southeast Asia.
Media publications: https://www.techinasia.com/xfers-launch-pilot-stablecoin https://blog.crypto.com/xsgd-the-singapore-dollar-stablecoin-listed-on-crypto-com/
Tradeable exchanges: crypto.com
Recommended Gas Limit (For ERC-20 project teams) for transaction: (Default is 60,000)

### CODE REVIEW

**Comment by liewjiajun** [comment]
The token 0x08773191272aBB2d7229271D644C90764e0E72cd is causing TravisCI to fail because it has USDT in the initial price.

**Comment by sfsy520** [comment]
由于贵方为稳定比项目，请提供更多权威报道。

**Comment by liewjiajun** [comment]
@sfsy520 关于稳定币的报道我们才刚开始不久所以不多，总公司（Xfers）的报道我有：

https://blog.crypto.com/xsgd-the-singapore-dollar-stablecoin-listed-on-crypto-com/
https://www.techinasia.com/xfers-launch-pilot-stablecoin
https://www.coindesk.com/exchange-behemoth-binance-opens-singapore-branch
https://www.straitstimes.com/singapore/payment-company-xfers-wins-police-award-for-fighting-cybercrime
https://techcrunch.com/2016/01/06/xfers-seed/
https://www.techinasia.com/xfers-gets-mas-approval

**Comment by liewjiajun** [comment]
@sfsy520 帮忙审核一下，谢谢！

**Comment by sfsy520** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 管理资产。

**Pull request merged**
