### PR TITLE
Add OTU token

### PR DESCRIPTION
**Pull request by onetimeutil1**
### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [x] logo dimensions: 120*120 px
- [x] logo background: Transparent
- [x] At least one transaction on the token contract
- [ ] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [x] Same document name for both .json and .png (Including capitalization)

**Project background:**

Official announcement: https://otutil.com/

Project team background:
OTU (One Time Utility) allows you to receive EMAIL without an account.
And all received EMAIL will be deleted after 1 hour.
The key values ​​of the received EMAIL is stored in the OTU blockchain.

Tradeable exchanges: https://bloks.io/account/onetimeutil1

https://dappradar.com/eos/1237/onetimeutility

Alll EOS accounts can claim to airgrab 1,000 OTU
https://www.otutil.com/myotu.php

### CODE REVIEW

**Comment by onetimeutil1** [comment]
Official announcement: https://otutil.com/

Project team background:
OTU (One Time Utility) allows you to receive EMAIL without an account.
And all received EMAIL will be deleted after 1 hour.
The key values ​​of the received EMAIL is stored in the OTU blockchain.

https://dappradar.com/eos/1237/onetimeutility

Alll EOS accounts can claim to airgrab 1,000 OTU 
https://www.otutil.com/myotu.php

**Comment by sfsy520** [comment]
Logo像素不符合要求，以及需要参考教程丰富json内容

**Comment by onetimeutil1** [comment]
Update official announcement
https://otutil.com/

**Comment by sfsy520** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 管理资产。

**Pull request merged**
