### PR TITLE
add JASMY

### PR DESCRIPTION
**Pull request by ttetokt**
### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [x] logo dimensions: 120*120 px
- [x] logo background: Transparent
- [x] At least one transaction on the token contract
- [x] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [x] Same document name for both .json and .png (Including capitalization)

**Project background:**

Official announcement:
Project team background:
Project basic information:
--> Please refer the whitepaper. : https://jasmy.co.jp/images/whitepaper20200618_eng.pdf

Media publications: https://jasmy.co.jp/en_info.html
Tradeable exchanges: Huobi global(https://www.huobi.com) 
Recommended Gas Limit (For ERC-20 project teams) for transaction: 60,000

Official announcemen: https://jasmy.io/news/2020/10/000085.html

### CODE REVIEW

**Comment by sfsy520** [comment]
Symbol不正确，另外请附上官方公告链接。

**Comment by ttetokt** [comment]
Modified Symbol.
Add Official announcemen: https://jasmy.io/news/2020/10/000085.html

**Comment by ttetokt** [comment]
Updated.

**Comment by sfsy520** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 ，imToken 支持比特币, 以太坊, Comos, EOS, 波场, Nervos, 比特币现金, 莱特币，波卡等资产管理；同时支持去中心化币币兑换功能 Tokenlon；转账页面支持 ETH, USDT, EOS, BTC OTC 功能；另外对于没有 ETH 矿工费的用户，也提供 ETH 手续费充值功能。

**Comment by sfsy520** [comment]
Json格式不正确导致merge后未显示，请重新提交。

**Pull request merged**
