### PR TITLE
add goofy token

### PR DESCRIPTION
**Pull request by goofytoken**
### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

**.json 及 .png 文件检查项**
- [x] logo 尺寸：120*120 px
- [x] logo 背景：透明
- [x] 代币有至少一笔成功的转账记录
- [x] 此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
- [x] .json 和 .png 文件名一致（包括大小写）

**项目资料：**
官方公告：
https://twitter.com/GoofyToken/status/1394935385994629122?s=20
团队背景：
Goofy团队利用其由创意人员、开发人员和加密行业专业人士组成的完整跨国团队，将Goffytoken.com平台从概念和私募引入功能构建。我们目前的团队拥有多年的合作经验，公司预计2022年将有20多名人才加入到团队中，以确保其新的基于区块链的环境中的每个领域都有专家覆盖。
项目基本情况：
参与goofytoken的每个人都拥有同样的权利，同样的所有人都是平等的，一切从零开始，发行总量达到1000万亿。最初取消了900万亿美元，剩下的100万亿美元一次全部释放到uniswap中，形成交易对。

比特币和以太坊，曾经被宣传为“反精英”，现在变得越来越“只为精英服务”（而且越来越贵）。比特币已经成为华尔街和鲸鱼的游戏，而以太坊生态系统已经成为科学家的天堂。不懂金融和编码的散户和小投资者根本无法融入社区。Goofytoken来了。再次高举真正去中心化的旗帜，让每个人都能真正成为越来越依赖区块链技术的新兴世界的公民。
收录的交易所：
Uniswap
转账所需 Gas Limit（对 ERC-20 项目方）：（默认为 60000）

---

### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [x] logo dimensions: 120*120 px
- [x] logo background: Transparent
- [x] At least one transaction on the token contract
- [x] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [x] Same document name for both .json and .png (Including capitalization)

**Project background:**
Official announcement: 
https://twitter.com/GoofyToken/status/1394935385994629122?s=20
Project team background:
The Goofy team leveraged it’s full multinational team of creatives, developers and crypto industry professionals to bring the Goffytoken.com platform from concept and Private Placement on to functional build-out. Our current team has years ofexperience working together and the company forecasts 20+ talent additions to its team in 2022 to ensure specialist coverage for every area in its new blockchain based environment.
Project basic information:
Everyone involved in goofytoken holds the same right, the same-all being equal, everything starts from scratch, with a total issuance of 1000 trillion. With an initial elimination of 900 trillion.The remaining 100 trillion all at once released into uniswap to create trading pairs.

Bitcoin and Ethereum, which once advertised as "Anti-elite", are becoming more and more "solely for the elites" (and more and more expensive). Bitcoin has become a game of Wall Street and whales, while the Ethereum ecosystem has become a paradise for scientists. Retail and small investors who do not understand finance and coding simply cannot integrate into the community. Goofytoken came. Once again raise the banner of true decentralization, so that everyone can truly become a citizen in an emerging  world which is more and more relying on blockchain Technology.

Tradeable exchanges:
Uniswap

Recommended Gas Limit (For ERC-20 project teams) for transaction: (Default is 60,000)

### CODE REVIEW

**Comment by goofytoken** [comment]
-Bitcoin and Ethereum, which once advertised as "Anti-elite", are becoming more and more "solely for the elites" (and more and more expensive). Bitcoin has become a game of Wall Street and whales, while the Ethereum ecosystem has become a paradise for scientists. Retail and small investors who do not understand finance and coding simply cannot integrate into the community. Goofytoken came. Once again raise the banner of true decentralization, so that everyone can truly become a citizen in an emerging  world which is more and more relying on blockchain Technology.

**Comment by goofytoken** [comment]
-Goofytoken ensures that a project starts from scratch and grows in a purely decentralized way with the implementation of blockchain technology.

**Comment by goofytoken** [comment]
已提交

**Comment by Leo2021zzz** [comment]
Incorrect json format, check it. :(

**Comment by goofytoken** [comment]
已修改json

**Comment by goofytoken** [comment]
已修改

**Comment by Leo2021zzz** [comment]
你好，
将合并此 PR，欢迎在社区中推荐使用 imToken 管理 GOOFY 资产。

**Pull request merged**
