### PR TITLE
Add AOM token

### PR DESCRIPTION
**Pull request by China-tao**
### 团队背景：
DFBTC团队里有业内享有声望且已经有成功项目经验的开发者，有已在目标行业内沉浸多年的资深运营者及专家。DFBTC团队是一个专注于区块链行业做基础和落地应用的团队，现在已有规模近50人的区块链研究、技术和商务团队。随著DFBTC的发展与应用市场份额的增大，DFBTC将会以开放的态度吸纳愿意为社区做出贡献的人才。

### 项目基本情况：
AOM是DFBTC跨链的一个重要收益组成，通过技术解决比特币的零息资产而产生的，DFBTC通过跨链锚定技术锚定BTC在ETH网络，提供更高的流动性。AOM未来将打造更多的优质资产收益方式，后期将会跨链到其他优质主链提供增加更大价值。

更多关于AOM 的信息:

- website：https://www.dfbtc.org
- Docs: https://docs.dfbtc.org
- Medium: https://dfbtc.medium.com/
- Twitter:  https://twitter.com/DFBTC
- Telegram: https://t.me/DFBTC_Commmunity

### 媒体报道: 

- https://www.chainnews.com/articles/459554542489.htm

### 官方公告: 

- https://twitter.com/DFBTC/status/1392520502053277697

### gas limit：60000

### CODE REVIEW

**Comment by Leo2021zzz** [comment]
In order to ensure the authenticity of the information submitted, please publish an announcement on your website or official social media channels and attach the corresponding link in “Official announcement”. We recommended a format similar to the following:
#imToken #1636 We are providing XXX token’s information on imToken. After completion, you can see the logo and full information inside imToken’s Token Manager.
Memo:
* 1636 is the PR number, as in: https://github.com/consenlabs/token-profile/pull/1636 This number is the key to verify yourself as the rightful editor of the information to imToken.
* The token information can only be changed after the official verification

**Comment by DFBTCice** [comment]
The official announcement: https://twitter.com/DFBTC/status/1392520502053277697

**Comment by DFBTCice** [comment]
The official announcement: https://twitter.com/DFBTC/status/1392520502053277697

**Comment by DFBTCice** [comment]
> In order to ensure the authenticity of the information submitted, please publish an announcement on your website or official social media channels and attach the corresponding link in “Official announcement”. We recommended a format similar to the following:
> #imToken #1636 We are providing XXX token’s information on imToken. After completion, you can see the logo and full information inside imToken’s Token Manager.
> Memo:
> 
> * 1636 is the PR number, as in: [https://github.com/consenlabs/token-profile/pull/1636 This](https://github.com/consenlabs/token-profile/pull/1636%C2%A0This) number is the key to verify yourself as the rightful editor of the information to imToken.
> * The token information can only be changed after the official verification


> 为了确保所提交信息的真实性，请在您的网站或官方社交媒体渠道上发布公告，并在“官方公告”中附加相应的链接。我们建议使用类似于以下格式：[#](https://github.com/consenlabs/token-profile/pull/1636)
> imToken [＃1636](https://github.com/consenlabs/token-profile/pull/1636)我们在imToken上提供XXX令牌的信息。完成后，您可以在imToken的令牌管理器中看到徽标和完整信息。
> 备忘录：
> 
> * PR编号为1636，例如：[https](https://github.com/consenlabs/token-profile/pull/1636%C2%A0This) :  [//github.com/consenlabs/token-profile/pull/1636该](https://github.com/consenlabs/token-profile/pull/1636%C2%A0This)编号是验证您自己是imToken信息的正确编辑者的关键。
> * 令牌信息只能在经过官方验证后才能更改
The official announcement: https://twitter.com/DFBTC/status/1392520502053277697

**Comment by DFBTCice** [comment]
> In order to ensure the authenticity of the information submitted, please publish an announcement on your website or official social media channels and attach the corresponding link in “Official announcement”. We recommended a format similar to the following:
> #imToken #1636 We are providing XXX token’s information on imToken. After completion, you can see the logo and full information inside imToken’s Token Manager.
> Memo:
> 
> * 1636 is the PR number, as in: [https://github.com/consenlabs/token-profile/pull/1636 This](https://github.com/consenlabs/token-profile/pull/1636%C2%A0This) number is the key to verify yourself as the rightful editor of the information to imToken.
> * The token information can only be changed after the official verification

The official announcement: https://twitter.com/DFBTC/status/1392520502053277697

**Comment by China-tao** [comment]
> In order to ensure the authenticity of the information submitted, please publish an announcement on your website or official social media channels and attach the corresponding link in “Official announcement”. We recommended a format similar to the following:
> #imToken #1636 We are providing XXX token’s information on imToken. After completion, you can see the logo and full information inside imToken’s Token Manager.
> Memo:
> 
> * 1636 is the PR number, as in: [https://github.com/consenlabs/token-profile/pull/1636 This](https://github.com/consenlabs/token-profile/pull/1636%C2%A0This) number is the key to verify yourself as the rightful editor of the information to imToken.
> * The token information can only be changed after the official verification

The official announcement: https://twitter.com/DFBTC/status/1392520502053277697

**Comment by Leo2021zzz** [comment]
We've merged your PR. We'd love to have you share imToken with your community!

**Pull request merged**
