### PR TITLE
Add TGX token

### PR DESCRIPTION
**Pull request by defix2021**
**项目资料：**

官方公告:
【官方网站】
https://www.defix.finance
【官方客服】
Wechat ID：tgxxiaozhushou
【官方微博】
https://weibo.com/u/5896409521
【Telegram英文】
https://t.me/defixfinance
【Telegram中文】
https://t.me/defixcn
【Telegram韩文】
https://t.me/defixkorea
【Telegram日文】
http://t.me/defixjapan
【Twitter】
https://twitter.com/DeFiXFinance
【Medium】
https://defixfinance.medium.com/
【Instagram】
https://www.instagram.com/defixfinance
【Linkedin】
https://www.linkedin.com/in/jorgedefix/

团队背景:
Jorge Sebastião  乔治·赛巴斯蒂安 
DeFi-X 首席技术官
DeFi-X CTO

DeFi-X首席技术官，在AI，区块链，云计算，网络安全，灾难恢复，大数据等领域具有丰富的经验。Jorge专注于商业价值变现，曾为多个项目提供ICO、STO等全套咨询方案，全面了解由人工智能和区块链技术驱动的创新破坏效应。他创建了安全性流程A6：评估，架构师，应用，管理，意识和敏捷性。Jorge曾在众多国际会议上担任演讲嘉宾，主题包括：区块链，人工智能，云计算，网络安全，大数据等。
Jorge (Jorge. Sebastian) is the CTO of DeFi-X. He has extensive experience in blockchain, cybersecurity, artificial intelligence, 5G, and financial investments, and has written papers on the underlying blockchain design mechanism. He has been involved in the founding of several top blockchain technology companies focused on the underlying blockchain R&D. He is a very experienced entrepreneur, product geek and investor, and financial analyst.

Herbert Sim   赫伯特·辛
DeFi-X 超级节点
DeFi-X Supernode

赫伯特·辛（Herbert Sim）的风险投资基金-TheBitcoinMan.com于2016年成立而被悉知，后被人们敬称为比特币侠，是比特币链的标志性人物；赫伯特还是加密链大学的创始人，该大学成立于2010年，是世界上第一个区块链和加密研究论文储存库；赫伯特还兼任FortuneZ.com-加密货币和iGaming外汇新闻出版物的董事长。
Herbert Sim's venture capital fund - TheBitcoinMan.com - was founded in 2016 and became known to the public. Herbert is also the founder of Crypto Chain University, the world's first repository of blockchain and cryptographic research papers, founded in 2010. In addition, Herbert is also the chairman of FortuneZ.com - cryptocurrency and iGaming forex news publications.
赫伯特还是多个区块链项目的天使投资人— FortuneZ、Future1Exchange、TaoDust、Karuschain、GLBrain、TEVEL。
埃里克·休斯（Eric Hughes）的著作《数字朋克宣言》（CypherpunkManifesto.com），赫伯特是全球最早推行并营销的合作商之一。也是SuperHacker.com绰号的社区成长行销商。
Herbert is also an angel investor in several blockchain projects such as FortuneZ, Future1Exchange, TaoDust, Karuschain, GLBrain, and TEVEL.
Eric Hughes' book CypherpunkManifesto.com, Herbert is the author of One of the first partners in the world to implement and market it. Also known as SuperHacker.com, it is a community growth marketer.

Daniel Hoffmann
首席产品官
CPO

Daniel是物理学和数学爱好者。 他以前是Google的高级工程师，在开发预测性拍卖产品和风险投资方面拥有丰富的经验。 Daniel拥有麻省理工学院的博士学位，在那里他进行了ME和CS以及统计学和计算机工程方面的研究。
Daniel is a physics and math enthusiast. He was previously a senior engineer at Google and has extensive experience in developing predictive auction products and venture capital. Daniel holds a PhD from MIT, where he conducted research in ME and CS as well as statistics and computer engineering.

Hermann Simons
工程师/产品架构师
Engineer/Product Architect

赫尔曼（Hermann）在甲骨文（Oracle）的搜索排名和机器智能部门工作了5年，后来在Uber的排名和相关性团队中工作。他喜欢系统、数据和情报的交集。拥有斯坦福大学的计算机科学学士学位和硕士学位。
Hermann spent 5 years in Oracle's Search Ranking and Machine Intelligence group, and later worked on Uber's Ranking and Relevance team. He holds a B.S. and M.S. in Computer Science from Stanford University.

Armin D. Jason
科学家/后端负责人
Scientist/backend manager

Armin D. Jason曾在Google工作了5年，其中有4年属于“搜索索引”和“搜索排名”组。他对计算机科学的热情始于高中的竞争性编程，并在国际信息学奥林匹克竞赛中获得金奖。Armin拥有卡耐基梅隆大学的计算机工程学士学位。
Ahmed has worked at Google for 5 years, including 4 years in the "Search Index" and "Search Ranking" groups. His passion for computer science began with competitive programming in high school, where he won a gold medal in the International Informatics Olympiad. Armin holds a bachelor's degree in computer engineering from Carnegie Mellon University.

Nithin Amoli
工程师/后端
Engineer/back-end

Nithin之前在南加州大学（USC）工作，是IRDS / IMSC实验室的研究工程师，致力于将机器学习应用于交通预测、推荐系统、内容分析和文本挖掘等大数据问题。他的硕士论文专注于开发新颖的算法，以保护用户免受位置数据的侵害。Nithin拥有印度理工学院的计算机科学硕士学位。
Nithin previously worked at the University of Southern California (USC) as a research engineer in the IRDS / IMSC lab, where he worked on applying machine learning to big data problems such as traffic prediction, recommendation systems, content analysis, and text mining. His master's thesis focused on developing novel algorithms to protect users from location data. Nithin holds a Master's degree in Computer Science from the Indian Institute of Technology.

Jessica Mason
品牌经理 / PR
Brand Manager/ PR

杰西卡（Jessica）喜欢在技术与人文学科的交汇处工作。她拥有创意写作硕士学位和莱斯大学文学学士学位。
Jessica enjoys working at the intersection of technology and the humanities. She holds an MFA in Creative Writing and a BA from Rice University.

Jason Woodman
商务拓展
Business Development

贾森（Jason）在纽约工作了4年，担任顾问，领导了JP Morgan和Mastercard等多个客户的十几个项目。2017年，他收拾行装，开始了在洛杉矶的全职加密之旅。Jason喜欢滑雪、Buffalo Bills、音乐和诗歌。他拥有耶鲁大学经济学学士学位。
Jason worked in New York for 4 years as a consultant, leading over a dozen projects for a variety of clients including JP Morgan and Mastercard. In 2017, he embarked on a full-time encryption journey in Los Angeles.Jason enjoys skiing, Buffalo Bills, music, and poetry. He holds a B.A. in Economics from Yale University.

Steve Iverson
增长运营官
Growth Operations Officer

史蒂夫（Steve）领导了增长计划，并帮助Uniswap进入了世界顶级去中心化交易所。史蒂夫（Steve）对加密货币充满热情，并帮助其实现了主流采用。他拥有宾夕法尼亚大学历史学士学位，在那里他踢过足球和曲棍网兜球。
Steve was responsible for leading the growth initiatives and helping Uniswap enter the world's top decentralized exchange. Steve is passionate about cryptocurrencies and has helped bring them to mainstream adoption. 

项目基本情况:
DeFi-X是基于以太坊的去中心化合成资产发行协议。这些合成资产由DeFi-X网络通证(TGX)担保，只要将TGX在智能合约中锁定，即可发行合成资产 (XTokens)。DeFi-X将会给传统金融行业打开新的流量入口，将借贷类资产、保险、DEX、预言机等前沿数字资产技术和产品进行聚合，并且可以通过合成资产来解决介质问题。

媒体报道:
去中心化新物种，合成资产DeFi-X的原理
https://cointelegraphcn.com/press-releases/the-principle-of-defi-x

DeFi-X致力打造以太坊上的Synthetix+Uniswap+YFI 
https://www.sohu.com/a/425098725_120001234

疫情再爆发 你的主业还好吗 TGX（泰格币）来助力您的稳定收入
https://www.jinse.com/news/blockchain/893219.html

基于以太坊的DeFi 生态项目DeFi-X（泰格币）正在冲击亿万美金市场，全面打开全球支付市场
https://blog.csdn.net/marketvalue/article/details/110430597

DeFi-X CTO Jorge Sebastiao ：DeFi比传统金融更透明，一定会是未来的趋势
https://www.shenliancaijing.com/a/58163.html

基于以太坊的DeFi 生态项目DeFi-X正在冲击亿万美金市场，全面打开全球支付市场
https://zhuanlan.zhihu.com/p/296801052?utm_source=wechat_session

DeFi凉了？还是已经洗牌进入了下一个阶段？
https://news.huoxing24.com/20201106175539899452.html

DeFi新物种DeFi-X飞速发展，进入泰国市场
https://i.bishijie.com/detail/1363922

ETH2.0时代，合成资产DeFi-X的机遇与挑战
https://www.fromgeek.com/daily/1044-364263.html
https://m.sohu.com/a/435720274_120911203/?pvid=000115_3w_a
https://bihu.com/article/1428259056
https://www.chainnode.com/post/501693

一文读懂合成资产DeFi-X的原理以及生态布局
https://c.m.163.com/news/a/FSPVO7AK05314MDS.html?spss=adap_pc&referFrom=&spssid=a2eaa148d182d6fd0e8c1e47ac401a05&spsw=1&isFromH5Share=article

收录的交易所：
Uniswap
https://info.uniswap.org/pair/0x318be2aa088ffb991e3f6e61afb276744e36f4ae
转账所需 Gas Limit（对 ERC-20 项目方）：（默认为 60000）

### CODE REVIEW

**Comment by sfsy520** [comment]
为确保资料提交的真实性，请在贵方官网或其他经过认证的社交媒体渠道发布公告，并将此公告链接附于「官方公告」。推荐文案：
#imToken# #1636# 我们正在完善 XXX 在 imToken 中的代币相关资料。完成后，大家可以在 imToken 里看到 logo，更方便地管理 XXX，同时能看到更多代币信息。
注：
* 1636 为 pr 序号，如 https://github.com/consenlabs/token-profile/pull/1636 的序号为 1636，这是帮助 imToken 判断 pr 真实性的关键。
* #imToken #1636 标签及其展示形式可自行调整。
* 若未提供「官方公告」，则无法显示代币信息。

**Comment by defix2021** [comment]
> 为确保资料提交的真实性，请在贵方官网或其他经过认证的社交媒体渠道发布公告，并将此公告链接附于「官方公告」。推荐文案：
> #imToken# #1636# 我们正在完善 XXX 在 imToken 中的代币相关资料。完成后，大家可以在 imToken 里看到 logo，更方便地管理 XXX，同时能看到更多代币信息。
> 注：
> 
> * 1636 为 pr 序号，如 [https://github.com/consenlabs/token-profile/pull/1636 的序号为](https://github.com/consenlabs/token-profile/pull/1636%C2%A0%E7%9A%84%E5%BA%8F%E5%8F%B7%E4%B8%BA) 1636，这是帮助 imToken 判断 pr 真实性的关键。
> * #imToken #1636 标签及其展示形式可自行调整。
> * 若未提供「官方公告」，则无法显示代币信息。

已在推特发布公告，地址 https://twitter.com/defixfinance/status/1336183871948410881?s=21

**Comment by defix2021** [comment]
已在推特发布公告，地址 https://twitter.com/defixfinance/status/1336183871948410881?s=21

**Comment by sfsy520** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 ，imToken 支持比特币, 以太坊, Comos, EOS, 波场, Nervos, 比特币现金, 莱特币，波卡等资产管理；同时支持去中心化币币兑换功能 Tokenlon；转账页面支持 ETH, USDT, EOS, BTC OTC 功能；另外对于没有 ETH 矿工费的用户，也提供 ETH 手续费充值功能。

**Pull request merged**
