### PR TITLE
Update add CER token

### PR DESCRIPTION
**Pull request by sunnycn2013**
### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

**.json 及 .png 文件检查项**
- [x] logo 尺寸：120*120 px
- [x] logo 背景：透明
- [x] 代币有至少一笔成功的转账记录
- [x] 此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
- [x] .json 和 .png 文件名一致（包括大小写）

**项目资料：**

项目资料：

官方公告：
我们正在完善cer在 imToken中的代币相关资料。完成后，大家就可以在imToken里看到logo，更方便地管理cer了，还能看到更多代币信息。http://exrelay.org/index_cn.html
团队背景：
Exrelay 是典型的小而美技术精悍、纯粹的区块链开发团队，并在早期获得知名资本，创世资本的股权
投资，有10 名工程师，2 个以太坊魔术师开发组成员，致力于用最好的技术去优化去中心化兑汇业务应用
体验，用户体验永远第一，推动dapp 落地。
项目基本情况：
ExRelay 是一个基于 以太坊资产去中心化撮合交易而建立的分布式、无任何授权、可扩展、开放式、共享订单薄的交易中继节点网络， 业务覆盖于，兑汇、杠杆、法币、期货、期权，数据撮合交易等。
媒体报道：暂无
收录的交易所：暂无
转账所需 Gas Limit（对 ERC-20 项目方）：不需要

---

### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [x] logo dimensions: 120*120 px
- [x] logo background: Transparent
- [x] At least one transaction on the token contract
- [x] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [x] Same document name for both .json and .png (Including capitalization)

**Project background:**

Project background:

Official announcement: 
We are improving CERs token information in imToken. After completion, you can see logo in imToken, which makes it easier to manage cers, and you can also see more token information. Http://exrelay.org/index_cn.html
Project team background:
Exrelay is a typical small, technologically sophisticated, pure block chain development team, and acquired well-known capital in the early stage, the equity of founding capital.
Invest, with 10 engineers and 2 members of the development team of Etherfang Magicians, dedicated to optimizing the application of decentralized exchange business with the best technology Experience, user experience will always be the first, promoting the DAPP landing.
Project basic informationt:
ExRelay is a distributed, non-authorized, scalable, open and thin-order transaction relay network based on the de-centralized transaction of ETF assets. Its business covers exchange, leverage, French currency, futures, options and data matching transactions.
Media publications: not yet available
Tradeable exchanges: not yet
Gas Limit for Transfer Requirements (for ERC-20 Projects): No

### CODE REVIEW

**Comment by sunnycn2013** [comment]
@PLAYFUNIO 你好，请问一下为什么这么久了还没合并进入主干

**Comment by tstt** [comment]
还缺少「官方公告」，具体说明参考以下：

https://github.com/consenlabs/token-profile/blob/master/tutorial/erc20-tutorial.zh-CN.md#%E8%B5%84%E6%96%99%E7%9A%84%E5%AE%8C%E6%95%B4%E5%92%8C%E5%87%86%E7%A1%AE

image

**Comment by sunnycn2013** [comment]
@tstt 你好，已经修改过了，请验收！！

**Comment by tstt** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 管理资产。

**Pull request merged**
