### PR TITLE
Melt token

### PR DESCRIPTION
**Pull request by TheMeltProject**
### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [ X] logo dimensions: 120*120 px
- [ X] logo background: Transparent
- [ X] At least one transaction on the token contract
- [ X] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [ X] Same document name for both .json and .png (Including capitalization)

**Project background:**

Project team background:
Melt's team is made up of people with experience in the Blockchain technology sector. This team is made up of individuals from different parts of the world with a shared trait. We all love crypto

Project basic information:
MELT is a 1% deflatory token, every time MELT is transferred, 1% of sent amount is burned, this embedded functionality increases scarcity over time. MELT is based on original BOMB

Recommended Gas Limit (For ERC-20 project teams) for transaction: 60000

### CODE REVIEW

**Comment by TheMeltProject** [comment]
Link to Twitter Status
[https://twitter.com/project_melt/status/1149205467979288576](https://twitter.com/project_melt/status/1149205467979288576)

**Comment by TheMeltProject** [comment]
We're still building some announcements like [BTCTalk](https://bitcointalk.org/index.php?topic=5163700)

**Comment by tstt** [comment]
https://github.com/consenlabs/token-profile/blob/master/tutorial/erc20-tutorial.zh-CN.md#%E5%85%B7%E4%BD%93%E5%A6%82%E4%BD%95%E6%93%8D%E4%BD%9C

image

**Comment by TheMeltProject** [comment]
Added checksum to our branch

**Comment by tstt** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 管理资产。

**Pull request merged**
