### PR TITLE
Hct token

### PR DESCRIPTION
**Pull request by junkiet**
**项目资料：**

官方公告：https://herohelpme.io
团队背景： Jkey, Jimmy, Patrik, Nick, Lee
Jkey 是创办人
Jimmy 负责销售部门
Patrik 负责手机应用程序部门
Nick 负责投资部门
Lee 负责IT部门

项目基本情况：
HeroHelpMe Platform 《随身救星》，以独有的区块链去中心化技术所呈现的多元化商业生态圈，在“产业多元化、产品差异化、布局全球、资产通证化”的发展战略指引下，稳健发展，不断创新，创造了巨大的社会价值。

其它资料:
Website：herohelpme.io
Facebook: fb.com/HeroHelpMe

转账所需 Gas Limit（对 ERC-20 项目方）：60000

---
**Project background:**
Official announcement: https://herohelpme.io
Project team background: Jkey, Jimmy, Patrik, Nick, Lee
Jkey is Co-Founder of HCT
Jimmy is a head of sales department
Patrik is a head of Mobile App
Nick is our head of Investor department
Lee is our head of IT department

Project basic information:
HeroHelpMe Platform, it is based on the unique blockchain decentralized technology, and is divided into “industrial diversification, product differentiation and global distribution”. Under the guidance of the development strategy of “certification of assets”, it has developed steadily and constantly innovated, creating tremendous social value.

More Information:
Website：herohelpme.io
Facebook: fb.com/HeroHelpMe

Recommended Gas Limit: 60,000

### CODE REVIEW

**Comment by sfsy520** [comment]
请检查合约checksum格式

**Comment by junkiet** [comment]
> 请检查合约checksum格式

已经发送，请检查！

**Comment by junkiet** [comment]
> 请检查合约checksum格式

检查到怎么样了？

**Comment by junkiet** [comment]
> 请检查合约checksum格式

Hello, 我的怎么了？

**Pull request closed without merging**
