### PR TITLE
Add MAY token

### PR DESCRIPTION
**Pull request by 1542510067**
### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

**.json 及 .png 文件检查项**
- [x] logo 尺寸：120*120 px
- [x] logo 背景：透明
- [x] 代币有至少一笔成功的转账记录
- [x] 此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
- [x] .json 和 .png 文件名一致（包括大小写）

**项目资料：**

官方公告：http://www.btcmay.cc/#notice
团队背景：
项目基本情况：MAY为MAY Token的简称，全名为五月全球通证，MAY是基于以太坊的去中心化数字资产，由MAY数字资产交易平台发行。MAY可在MAY交易生态体系下的多场景中使用。MAY应用到MAY交易所全球业务与全球生态体系的各类应用中。持有者享受MAY全生态的相应权益。并得到生态子通证奖励，以及享受MAY持续回购销毁带来的稀缺性价值提升。
媒体报道：
收录的交易所：
转账所需 Gas Limit（对 ERC-20 项目方）：（默认为 60000）

---

### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [ ] logo dimensions: 120*120 px
- [x] logo background: Transparent
- [x] At least one transaction on the token contract
- [x] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [x] Same document name for both .json and .png (Including capitalization)

**Project background:**

Official announcement:http://www.btcmay.cc/#notice
Project team background:
Project basic information:MAY is the abbreviation of MAY Token, whose full name is MAY global certificate. MAY is a decentralized digital asset based on ethereum, issued by MAY digital asset trading platform. MAY can be used in multiple scenarios within the MAY trading ecosystem. MAY applies to a variety of applications in MAY exchange's global business and global ecosystem. The holder shall enjoy the corresponding rights of the whole ecology of MAY. In addition, I was awarded the zoon certificate and enjoyed the increase of scarcity value brought by MAY's continuous buyback and destruction.
Media publications:
Tradeable exchanges:
Recommended Gas Limit (For ERC-20 project teams) for transaction: (Default is 60,000)

### CODE REVIEW

**Comment by sfsy520** [comment]
存在问题：
1.请检查checksum

**Comment by 1542510067** [comment]
@sfsy520 如何检查

**Comment by 1542510067** [comment]
@sfsy520 已经修改checksum，请求合并

**Comment by 1542510067** [comment]
@sfsy520 你好，请问还有其他问题吗？可以申请合并吗？

**Pull request merged**
