### PR TITLE
add INT (0x001a5197F36db5bB492e32b9FB792B3F4Dbf7A17)

### PR DESCRIPTION
**Pull request by microcai**
add INT (0x001a5197F36db5bB492e32b9FB792B3F4Dbf7A17)

1）团队背景
Andy Li早期任职于知名互联网企业，主导过百万级用户移动应用的研发工作，有超过 20 年的互联 网经验。2014 年开始接触区块链行业，经过几年经验的积累，于 2017 年开始筹备 INTIMACY 的开发，iChat 是区块链 Token 经济与即时通讯相结合的一项创新应用，也是从事互联网和 区块链行业多年智慧的结晶。
Andy Li was previously known for his job at a recognized internet big-name company. Having had over 20 years of service time, Andy conducted several successful mobile application use cases. Since 2014, he's been immersed in the blockchain industry and through these years' experience, in 2017, Andy began to prime for the development of INTIMACY. iChat, the application powered by INTIMACY, is an innovative application merging blockchain's toekn economy and instant messaging. iChat is a brainchild of Andy's full-on experience in internet and blockchain industry.

2）项目基本情况
中文简介：
INT Token（以下简称 INT），是基于以太坊智能合约 ERC20 开发的数字货币。聊天即挖矿，是基于 iChat 应用和 INTIMACY 社交网络的发展愿景所衍生出的一种独特激励机制。

英文简介：
INT token (Ticker: INT) is an Ethereum ERC20 token. Chatting as Mining is a unique incentive system birthed from the development vision of iChat app and INTIMACY social network.

INT初始价格：2CNY、0.36USDT、0.00003BTC
INT官网：http://int.ren
3）媒体报道：无
4）收录的交易所：
币易Coinyee：www.coinyee.pro

转账所需 Gas Limit：60000

### CODE REVIEW

**Comment by microcai** [comment]
官方 推特消息 : https://twitter.com/INTOfficial1/status/1149153485729878017?c=4483

**Comment by tstt** [comment]
请确保发送官方公告的 twitter 可从贵方官网直接跳转。

**Comment by microcai** [comment]
官网已经改好了.

**Comment by tstt** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 管理资产。

**Pull request merged**
