### PR TITLE
ADD FEB Token

### PR DESCRIPTION
**Pull request by henryzu**
### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

**.json 及 .png 文件检查项**
- [x] logo 尺寸：120*120 px
- [x] logo 背景：透明
- [x] 代币有至少一笔成功的转账记录
- [x] 此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
- [x] .json 和 .png 文件名一致（包括大小写）

**项目资料：**

官方公告：
团队背景：Jack Fu FEB项目CEO，具有8年传统投资经验，曾担任美国CapitalOneFinancialCorp高级分析师、加拿大BrookfieldAssetManagement高级经理。硅谷区块链协会副会长；区块链天使投资人、布道者；NEO、波场早期投资人。 
项目基本情况：FEB（Fair Efficient Business），中文名，飞币。其将颠覆传统大数据产业模式，建立一个先进、安全、独特的去中心化数大据产业生态，FEB希望通过一系列公开公正的规则标准，促进整个产业信息快速流动变更，优化当前产业结构组成、对资源进行合理分配，最终实现利用区块链技术形成以FEB协议为节点的去中心化平台，最终打造成为一个服务全球的顶级大数据产业平台。
媒体报道：https://www.bishijie.com/kuaixun_441926
https://mxc-exchange.zendesk.com/hc/zh-cn/articles/360035685391-MXC平台即将首发上线FEB并举行充值大赛的公告
收录的交易所：抹茶 https://www.mxc.co/
转账所需 Gas Limit（对 ERC-20 项目方）：（默认为 60000）

---

### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [x] logo dimensions: 120*120 px
- [x] logo background: Transparent
- [x] At least one transaction on the token contract
- [x] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [x] Same document name for both .json and .png (Including capitalization)

**Project background:**

Official announcement:
Project team background:Jack Fu CEO of FEB project, with 8 years of traditional investment experience, served as senior analyst of Capital One Financial Corp and senior manager of Brookfield Asset Management. Vice President of the Silicon Valley Blockchain Association; blockchain angel investors, evangelists; Early investors of NEO and Tron.
Project basic information:FEB (Fair Efficient Business) will subvert the traditional big data industry model and establish an advanced, safe and unique decentralized data industry ecology. Through open rules and clear standards, FEB aims to accelerate the flow of industrial information, optimize the current industrial structure, rationally allocate resources, and finally realize to form a decentralized platform based on the FEB protocol. 
Media publications:https://www.bishijie.com/kuaixun_441926
https://mxc-exchange.zendesk.com/hc/zh-cn/articles/360035685391-MXC平台即将首发上线FEB并举行充值大赛的公告
Tradeable exchanges:MXC   https://www.mxc.co/
Recommended Gas Limit (For ERC-20 project teams) for transaction: (Default is 60,000)

### CODE REVIEW

**Comment by sfsy520** [comment]
请检查Checksum

**Comment by henryzu** [comment]
> 请检查Checksum
已经改完

**Comment by henryzu** [comment]
已经更改完毕&nbsp;










------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"sfsy520"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月4日(星期一) 晚上6:44
收件人:&nbsp;"consenlabs/token-profile"<token-profile@noreply.github.com&gt;;
抄送:&nbsp;"酒无月，独酌"<867038050@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [consenlabs/token-profile] ADD FEB Token (#5206)




请检查Checksum

**Comment by sfsy520** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 管理资产。

**Pull request merged**
