### PR TITLE
add RXCC Token

### PR DESCRIPTION
**Pull request by RXcryptofreedom**
Request Add RXCC token

A. project background and team
The RXCC team is located in Singapore, Indonesia and Malaysia, the RXCC team has three and four years experience in the world of crypto and development, the RXCC team is divided into ERC20 experience, technical, programming and web, data processing and handling, management, service and planning in the project RXCC

B. More about RXCC
RXCC's goal is made for middle-class tokens by making innovations and a strong foundation for RXCC crypto, which will be able to compete with high-class tokens, simple RXCC tokens, which can run normally.

C. RXCC public media
site : https://cryptofreedom.ml/
https://twitter.com/RXCCrypto
https://t.me/cryptofreedomchannel
https://t.me/cryptofreedomgroup
https://medium.com/@RXCCcryptofreedom
https://bitcointalk.org/index.php?topic=5086671.0
https://github.com/RXcryptofreedom
https://cryptofreedom.ml/files/2018/11/RXCC.pdf
https://www.coingecko.com/en/coins/rxccryptofreedomtoken

D. RXCC Exchange
https://www.coinchangex.com/#!/trade/RXCC-ETH
https://www.etherflyer.com/trade.html?pairs=RXCC-ETH

gas limit: 60000

### CODE REVIEW

**Comment by RXcryptofreedom** [comment]
please, add the RXCC Token, in the ImToken application, thank you

**Comment by tstt** [comment]
I'll add the token profile only if your pr is right. 
I've suggested you to cooperate with your fellow to finish the pr job.

**Comment by RXcryptofreedom** [comment]
we have run PR with this example https://github.com/consenlabs/token-profile/pull/1636 . 
Sorry, we are not experienced in this field. tell us our problem, where the error of our request, we only have experience in crypto traders, and make crypto projects for many people

**Comment by RXcryptofreedom** [comment]
we have run PR with this example #1636 .
Sorry, we are not experienced in this field. tell us our problem, where the error of our request, we only have experience in crypto traders, and make crypto projects for many people

**Comment by RXcryptofreedom** [comment]
> I'll add the token profile only if your pr is right.
> I've suggested you to cooperate with your fellow to finish the pr job.
is this wrong ? (pr)
Request Add RXCC token

A. project background and team
The RXCC team is located in Singapore, Indonesia and Malaysia, the RXCC team has three and four years experience in the world of crypto and development, the RXCC team is divided into ERC20 experience, technical, programming and web, data processing and handling, management, service and planning in the project RXCC

B. More about RXCC
RXCC's goal is made for middle-class tokens by making innovations and a strong foundation for RXCC crypto, which will be able to compete with high-class tokens, simple RXCC tokens, which can run normally.

C. RXCC public media
site : https://cryptofreedom.ml/
https://twitter.com/RXCCrypto
https://t.me/cryptofreedomchannel
https://t.me/cryptofreedomgroup
https://medium.com/@RXCCcryptofreedom
https://bitcointalk.org/index.php?topic=5086671.0
https://github.com/RXcryptofreedom
https://cryptofreedom.ml/files/2018/11/RXCC.pdf
https://www.coingecko.com/en/coins/rxccryptofreedomtoken

D. RXCC Exchange
https://www.coinchangex.com/#!/trade/RXCC-ETH
https://www.etherflyer.com/trade.html?pairs=RXCC-ETH

gas limit: 60000

**Comment by tstt** [comment]
yea totally wrong, do not change the template.json.
copy it and then edit.

**Pull request closed without merging**
