### PR TITLE
Add OTRC token

### PR DESCRIPTION
**Pull request by otrfirms**
**Project background:**

Official announcement: 
[https://twitter.com/otrfirms/status/1149612653788065793](https://twitter.com/otrfirms/status/1149612653788065793)

Project team background: 
OTR Firms, CO. is an S-Corporation technology consulting company. Established January 2015, the company is continuing to maximize new telecommunications opportunities. We have built a rapport with sponsors, advertising, and suppliers such as Apple and Google. With technology constantly evolving, we profit from all new development. The telecommunications market is volatile and it’s been good for business. 

Project basic information:
OTR Coin is an IAP billing based token project.
We provide users the ability to purchase cryptocurrency through carrier billing.
This allows consumers to obtain holdings on the blockchain without spending on-hand capital.
Created on the Ethereum blockchain, OTR Coin is to be used within the bank holding & mining browser mobile application: OTR DApp

Media publications:

- Bitcoin Talk: 
[https://bitcointalk.org/index.php?topic=5155525.0](https://bitcointalk.org/index.php?topic=5155525.0)
- WeFunder: 
[https://wefunder.com/otrcoin](https://wefunder.com/otrcoin)
- Cracked.To:
[https://cracked.to/Thread-ICO-OTR-Coin](https://cracked.to/Thread-ICO-OTR-Coin)

Recommended Gas Limit (For ERC-20 project teams) for transaction: (Default is 60,000):
85000

Tradeable exchanges:

### CODE REVIEW

**Comment by otrfirms** [comment]
Cool!

**Comment by otrfirms** [comment]
block.cc Link: (wont verify my phone number to finish application)
Token Symbol: OTRC
Token Contract Address: 0x53eF7eA7574D7d3fb15dE17aA92EBeDbF7220522
Etherscan Link: https://etherscan.io/token/0x53eF7eA7574D7d3fb15dE17aA92EBeDbF7220522

**Comment by tstt** [comment]
> block.cc Link: (wont verify my phone number to finish application)
> Token Symbol: OTRC
> Token Contract Address: 0x53eF7eA7574D7d3fb15dE17aA92EBeDbF7220522
> Etherscan Link: https://etherscan.io/token/0x53eF7eA7574D7d3fb15dE17aA92EBeDbF7220522

if you want to show the token's price in the imToken asset tab, block.cc link is needed.

**Comment by tstt** [comment]
The logo is not qualified.
image

**Comment by otrfirms** [comment]
• Application for block.cc is finished. Not sure how to get them push a verify through to my number. I have tried to contact them

• Why is the logo ineligible?

**Comment by otrfirms** [comment]
Does anyone have contact on block.cc?
Not sure why it wont send my phone the verification code.

**Comment by otrfirms** [comment]
ive been stuck on this last page for a few days now.
even if i close out the application it has my data cached.
but for some reason i keep getting this error code and no text:

[https://i.imgur.com/3ZyffWg.png](url)

**Comment by tstt** [comment]
1. about the logo, do you sure your logo is right now?
image
2. about the block.cc issue, we cannot provide more information.

**Comment by otrfirms** [comment]
1. kind of like it being cut on the sides now.

2. is it because my phone number american? i see it working for other people with tokens

**Comment by tstt** [comment]
> 1. kind of like it being cut on the sides now.
> 2. is it because my phone number american? i see it working for other people with tokens

1. you are suggested to adjust the logo；
2. I'm not sure of this issue, you may need to contact block.cc official.

**Comment by otrfirms** [comment]
> > 1. kind of like it being cut on the sides now.
> > 2. is it because my phone number american? i see it working for other people with tokens
> 
> 1. you are suggested to adjust the logo；
> 2. I'm not sure of this issue, you may need to contact block.cc official.

1. logo changed.
2. will attempt to contact them again. not sure what contact information I'm supposed to use.
not getting any responses.

**Comment by tstt** [comment]
logo still unqualified, it's asked to be 120*120, not 250*250

**Comment by otrfirms** [comment]
fixed

**Comment by otrfirms** [comment]
can you post our profile and we set the price up later?

**Comment by tstt** [comment]
we can set the price later.

Welcome to recommend imToken 2.0 to your token holders to manage their token.

**Comment by otrfirms** [comment]
still no response from mifencha(block.cc), there's no way to post the price through the application admins?

**Pull request merged**
