### PR TITLE
Add smartfund token

### PR DESCRIPTION
**Pull request by fergus789**
**.json and .png document checklists**
- [X] logo dimensions: 120*120 px
- [X] logo background: Transparent
- [X] At least one transaction on the token contract
- [X] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [X] Same document name for both .json and .png (Including capitalization)

**Project background:**

Official announcement:#imToken #4198 We are providing $F token’s information on imToken. After completion, you can see the logo and full information inside imToken’s Token Manager.

Project team background:The $mart fund team is located at Singapore. The core members have more than 10 years of experience in Internet product development, and they are also a technical team in the field of early research blockchain. At present, there are more than a dozen members of the team, which gathers the core technology development elites of the wallets, BPs, mining, trading, etc., and has experience in operating LBTC Block Producer.

Project basic information:The $mart fund is a set of smart contracts and tokens running on Ethereum. The $mart investment ecosystem consists of a $mart Fund and a number of DAPP projects invested, the core goal is to use the smart contract to achieve a digital currency decentralized investment in the DAPP projects with clear profit model. The democratic vote participates in the investment decision and automatically distributes the project revenue in real time.

Tradeable exchanges:https://coinxexchange.github.io

Recommended Gas Limit (For ERC-20 project teams) for transaction: 60000

### CODE REVIEW

**Comment by tstt** [comment]
The problem has been figured out in the label, please refer to the tutorial to adjust.

**Comment by fergus789** [comment]
@tstt The problem has been solved, please help verify it again. thank you~

**Comment by tstt** [comment]
https://github.com/consenlabs/token-profile/blob/master/tutorial/erc20-tutorial.zh-CN.md#%E8%B5%84%E6%96%99%E7%9A%84%E5%AE%8C%E6%95%B4%E5%92%8C%E5%87%86%E7%A1%AE

image

**Comment by fergus789** [comment]
Here is the announcement，visit https://1smartfund.github.io

**Comment by fergus789** [comment]
@tstt Please help me with it.

**Comment by tstt** [comment]
Welcome to recommend imToken 2.0 to your token holders to manage their token.

**Pull request merged**
