### PR TITLE
Add Logo and Info for Razor Network (RAZOR) token

### PR DESCRIPTION
**Pull request by ankit5902**
## Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [x] logo dimensions: 120*120 px
- [x] logo background: Transparent
- [x] At least one transaction on the token contract
- [x] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [x] Same document name for both .json and .png (Including capitalization)

**Project Background:**

Project basic information: Razor Network is a decentralized oracle network, which connects smart contracts with real-world off-chain data in a fast, robust and secure way. The core of Razor Network is a set of smart contracts that can run on any Ethereum compatible blockchain. Razor Network is blockchain agnostic and will be integrated with multiple blockchains.

CoinMarketCap page: https://coinmarketcap.com/currencies/razor-network/
CoinGecko page: https://www.coingecko.com/en/coins/razor-network
Etherscan Page: https://etherscan.io/token/0x50DE6856358Cc35f3A9a57eAAA34BD4cB707d2cd

Media publications:
1. https://www.coindesk.com/razor-network-oracles-funding-round
2. https://www.chainnews.com/news/315117639788.htm
3. https://news.yahoo.com/razor-network-raises-3-7m-140021836.html
4. https://www.nasdaq.com/articles/razor-network-raises-%243.7m-to-prove-theres-room-for-more-oracles-in-defi-2020-11-04
5. https://www.youtube.com/watch?v=98oPxBdLIsE
6. https://www.facebook.com/watch/live/?v=140544520842010&ref=watch_permalink

Tradeable exchanges: Uniswap, Balancer, MXC, Gate.io, Hoo

Recommended Gas Limit (For ERC-20 project teams) for a transaction: 60,000

### CODE REVIEW

**Comment by ankit5902** [comment]
@sfsy520 All checks passed. Please check and let me know if there's still anything missing.

**Comment by ankit5902** [comment]
@sfsy520 All checks passed. Please check and let me know if there's still anything missing.

**Comment by sfsy520** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 ，imToken 支持比特币, 以太坊, Comos, EOS, 波场, Nervos, 比特币现金, 莱特币，波卡等资产管理；同时支持去中心化币币兑换功能 Tokenlon；转账页面支持 ETH, USDT, EOS, BTC OTC 功能；另外对于没有 ETH 矿工费的用户，也提供 ETH 手续费充值功能。

**Comment by ankit5902** [comment]
Hey @sfsy520 by when can I expect it to be added and the logo and info to be reflected on the App?

**Comment by ankit5902** [comment]
Hey @sfsy520 by when can I expect it to be added and the logo and info to be reflected on the App?

嘿，@ sfsy520何时可以添加，徽标和信息会在应用程序上反映出来？

**Pull request merged**
