### PR TITLE
Add EMPT token

### PR DESCRIPTION
**Pull request by emptteam**
### EMPT 
**Team Information**

The EMPT team was newly established in 2020.
Our team is currently in Seoul and consists mostly of competent members with more than 5 to 10 years of experience.
The detailed department consists of a development team and legal team and communication team, etc.

**EMPT project**

EMPT is consented and mined from a mobile device. And the block chain data is stored on the mobile device.
It's a project that started with the goal of a mobile-based network.
Systematical cluster of devices enable to minimize resource use and it is possible to secure a lot of nodes by the widely distributed mobile devices.
The network of EMPT is a very large network vertically with high availability, high data reliability. Also continuous scale-up is possible.

Web Site : http://empt.dev
White Paper(chinese) : https://empt.dev/cn_whitepaper_v1.pdf
White Paper(english) : https://empt.dev/en_whitepaper_v1.pdf 
White Paper(korean) : https://empt.dev/whitepaper_v1.pdf

### EXCHANGE
foblgate(korea) : https://www.foblgate.com/

### COMMUNITY
telegram : https://t.me/empt_officialcommunity

### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [x] logo dimensions: 120*120 px
- [x] logo background: Transparent
- [x] At least one transaction on the token contract
- [x] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [x] Same document name for both .json and .png (Including capitalization)

### CODE REVIEW

**Comment by sfsy520** [comment]
请检查checksum格式

**Comment by emptteam** [comment]
謝謝. 已修改，请重新审核

**Comment by sfsy520** [comment]
In order to ensure the authenticity of the information submitted, please publish an announcement on your website or official social media channels and attach the corresponding link in “Official announcement”. We recommended a format similar to the following:
#imToken #1636 We are providing XXX token’s information on imToken. After completion, you can see the logo and full information inside imToken’s Token Manager.
Note:
* 1636 is the PR number, as in: https://github.com/consenlabs/token-profile/pull/1636 This number is the key to verify yourself as the rightful editor of the information to imToken.
* The token information can only be changed after the official verification

**Comment by brand1313** [comment]
Thank you, sfsy520!

We published official announcement as pop up in our official web site https://empt.dev/

could you please check it? Bye

**Comment by sfsy520** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 ，imToken 支持比特币, 以太坊, Comos, EOS, 波场, Nervos, 比特币现金, 莱特币，波卡等资产管理；同时支持去中心化币币兑换功能 Tokenlon；转账页面支持 ETH, USDT, EOS, BTC OTC 功能；另外对于没有 ETH 矿工费的用户，也提供 ETH 手续费充值功能。

**Pull request merged**
