### PR TITLE
add ltr info - labtorum

### PR DESCRIPTION
**Pull request by labtorum**
please add labtorum info to imtoken app

### CODE REVIEW

**Comment by labtorum** [comment]
Now our token info is fixed and correct

**Comment by labtorum** [comment]
we have replaced our contract, because first contract there is code causing the error.

**Comment by wenyanwang** [comment]
你好，请提供主流区块链媒体报道，和logo信息，谢谢。

**Comment by labtorum** [comment]
please dont use chinese language

**Pull request closed without merging**
