### PR TITLE
Add ZNC token (We have improved)

### PR DESCRIPTION
**Pull request by zioncointeam**
**Project background:**

- Official announcement:http://zionc.info/blog/
- Project team background: The ZNC R&D team is from Silicon Valley, USA, and has more than 40 engineers including the C++ language. 
- Project basic information:ZionCoin's design philosophy is to use profit incentive mechanism to construct a fast, low cost, efficient, safe and reliable public blockchain ecosystem which satisfies large-scale daily business needs. These requirements include, but are not limited to, trading and clearance of various types of assets, as well as redundant storage of information.
- Media publications:https://twitter.com/CoinZion
- Tradeable exchanges: July transaction
- Recommended Gas Limit (For ERC-20 project teams) for transaction: (Default is 60,000)

### CODE REVIEW

**Comment by tstt** [comment]
https://github.com/consenlabs/token-profile/blob/master/tutorial/erc20-tutorial.zh-CN.md#%E8%B5%84%E6%96%99%E7%9A%84%E5%AE%8C%E6%95%B4%E5%92%8C%E5%87%86%E7%A1%AE

image

**Comment by zioncointeam** [comment]
Understand, this is our announcement：
https://zionc.info/blog/2019/7/3/imtoken-support/

**Comment by zioncointeam** [comment]
https://zionc.info/blog/2019/7/3/imtoken-support/

**thanks**

**Comment by tstt** [comment]
Welcome to recommend imToken 2.0 to your token holders to manage their token.

**Pull request merged**
