### PR TITLE
Please ADD VERDICT TOKEN

### PR DESCRIPTION
**Pull request by Qtdeejay**

### CODE REVIEW

**Comment by Qtdeejay** [comment]
Why is it taking too long for adding VERDICT since yesterday I had to delete it and read submit for quicker response, but it doesn't seems to get the attention. Am I getting anything wrong here

**Comment by makoshan** [comment]
Please provide more info about the token.

**Comment by Qtdeejay** [comment]
Done

**Comment by makoshan** [comment]
Please attach the token logo image, and refer to the [template](https://github.com/consenlabs/token-profile/blob/master/erc20/%24template.json)

**Pull request closed without merging**
