### PR TITLE
Add ELS token

### PR DESCRIPTION
**Pull request by DemonElves**
Official announcement:https://twitter.com/ElvesDemon/status/1243777292720934913?s=20
Project team background:It was created by the Demon Elves Team, whose mission is to serve ELS market participants,
Including financial market technology developers, financial market institutions, and financial market trading parties, the establishment of the next generation of decentralized and open financial infrastructure.
Project basic information:An independent, decentralized governance mechanism to stimulate and coordinate development. An open, intelligent privacy blockchain with an atomic interoperability multi-chain architecture. A service and ecosystem around decentralized financial service providers, ELS projects, distributed applications.
Media publications:https://twitter.com/ElvesDemon
Tradeable exchanges:ElvesDemon
Recommended Gas Limit (For ERC-20 project teams) for transaction: 60000

### CODE REVIEW

**Comment by sfsy520** [comment]
请检查json中Checksum格式。

**Comment by DemonElves** [comment]
> 请检查json中Checksum格式。
The json file has been updated

**Comment by sfsy520** [comment]
Logo不符合要求

**Comment by DemonElves** [comment]
I resized the logo

**Comment by laoma6** [comment]
white paper, website construction, security audit report. The lowest price in the whole network! If you need ，please add the wechat ：laoma1145, please delete it if you are disturbed, thank you.

**Comment by sfsy520** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 管理资产。

**Pull request merged**
