### PR TITLE
add new erc20 token  Lcr

### PR DESCRIPTION
**Pull request by ShangXoL**
name:Loocar 
symbol:Lcr
contract address:0xD4bDBBB9c3d221Ef59624Eb25F3eE84970E713e2

### CODE REVIEW

**Comment by ShangXoL** [comment]
thank you

**Comment by makoshan** [comment]
Please provide more info about the token.

**Comment by ShangXoL** [comment]
help      What does it contain of  more info about the token

**Comment by ShangXoL** [comment]
@makoshan  please

**Pull request closed without merging**
