### PR TITLE
Add CNHC token

### PR DESCRIPTION
**Pull request by nnnggel**
## Project team background:
CNHC team is based in different countries such as China, Singapore, the United States, Brazil and Japan. Core team members are mostly from top Wall Street hedge funds, leading blockchain investment institutions, etc, with over 10 years of experience in the Internet, foreign trade and financial industries. Currently, Cnhc Group has launched a digital currency linked to offshore RMB.

## Project basic information:
CNHC is a crypto currency that is CNH-pegged. Each CNHC is backed by 1 offshore RMB (CNH), in compliance with regulated U.S. trust and banks for fund custody. Audit reports will be published by an independent audit firm on a regular basis. CNHC is supported by top international investment institutions and Internet giants, and will be promoted globally, including but not limited to application scenarios such as international payment, global trade, and decentralized finance.

* Website: [https://www.cnhc.to/](https://www.cnhc.to/)
* Medium: [https://medium.com/@cnhcto](https://medium.com/@cnhcto)
* Facebook: [https://www.facebook.com/CNHCto](https://www.facebook.com/CNHCto)
* Twitter: [https://twitter.com/CNHC93231472](https://twitter.com/CNHC93231472)

### CODE REVIEW

**Comment by sfsy520** [comment]
为确保资料提交的真实性，请在贵方官网或其他经过认证的社交媒体渠道发布公告，并将此公告链接附于「官方公告」。推荐文案：
#imToken# #1636# 我们正在完善 XXX 在 imToken 中的代币相关资料。完成后，大家可以在 imToken 里看到 logo，更方便地管理 XXX，同时能看到更多代币信息。
注：
* 1636 为 pr 序号，如 https://github.com/consenlabs/token-profile/pull/1636 的序号为 1636，这是帮助 imToken 判断 pr 真实性的关键。
* #imToken #1636 标签及其展示形式可自行调整。
* 若未提供「官方公告」，则无法显示代币信息。

**Review by SatoshiNakamotogmx — APPROVED** [review]

**Comment by nnnggel** [comment]
https://twitter.com/CNHC_TO/status/1368772515082866690

**Comment by sfsy520** [comment]
非常抱歉，该官方公告Twitter与官网中账号不一致。

**Comment by nnnggel** [comment]
> 非常抱歉，该官方公告Twitter与官网中账号不一致。

sorry, updated.

**Pull request closed without merging**
