### PR TITLE
Add AeroToken

### PR DESCRIPTION
**Pull request by aerotoken**
### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

**.json 及 .png 文件检查项**
- [ ] logo 尺寸：120*120 px
- [ ] logo 背景：透明
- [ ] 代币有至少一笔成功的转账记录
- [ ] 此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
- [ ] .json 和 .png 文件名一致（包括大小写）

**项目资料：**

官方公告：
团队背景：
项目基本情况：
媒体报道：
收录的交易所：
转账所需 Gas Limit（对 ERC-20 项目方）：（默认为 60000）

---

### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [ ] logo dimensions: 120*120 px
- [ ] logo background: Transparent
- [ ] At least one transaction on the token contract
- [ ] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [ ] Same document name for both .json and .png (Including capitalization)

**Project background:**

Official announcement: https://twitter.com/aero_token/status/1171382333552959490
https://medium.com/@aerotoken328/official-announcement-56b7f6e312fe

Project team background: For the security and safety of the high profile team members who will be handling very sensitive information about the project, the team is undisclosed for the safety of the project and the team members.
Project basic information: Aerotoken token (AET) is an inflationary crypto-token, operating on the Ethereum blockchain (ERC-20 standard token) which can be used as a currency, a store of value or an investment. Each time an AET is transferred, 1% of the transaction is increased. AeroToken (AET) has a total supply of 500,000 only and is divisible up to 18 zeroes after decimal point (18 decimal), ensuring great stability and long term use of the asset. The transfer fee is low and transfer confirmations happen in less than a minute.
Media publications: https://www.twitter.com/aero_token
https://medium.com/@aerotoken328
Tradeable exchanges: Not yet listed on any exchange
Recommended Gas Limit: (Default is 60,000)

### CODE REVIEW

**Comment by sfsy520** [comment]
存在的问题：
1.请检查Checksum格式
2.为确保资料提交的真实性，请在贵方官网或其他经过认证的社交媒体渠道发布公告，并将此公告链接附于「官方公告」。推荐文案：
#imToken# #1636# 我们正在完善 XXX 在 imToken 中的代币相关资料。完成后，大家可以在 imToken 里看到 logo，更方便地管理 XXX，同时能看到更多代币信息。
注：
* 1636 为 pr 序号，如 https://github.com/consenlabs/token-profile/pull/1636 的序号为 1636，这是帮助 imToken 判断 pr 真实性的关键。
* #imToken #1636 标签及其展示形式可自行调整。
* 若未提供「官方公告」，则无法显示代币信息

**Comment by aerotoken** [comment]
项目背景：

官方公告：https：//twitter.com/aero_token/status/1171382333552959490
https://medium.com/@aerotoken328/official-announcement-56b7f6e312fe

项目团队背景：为了处理关于项目的非常敏感信息的高知名团队成员的安全性和安全性，团队对项目和团队成员的安全性不了解。
项目基本信息：Aerotoken令牌（AET）是一种通胀加密令牌，在以太坊区块链（ERC-20标准令牌）上运行，可用作货币，价值存储或投资。每次转移AET时，交易的1％都会增加。 AeroToken（AET）的总供应量仅为500,000，在小数点后（小数点后18位）最多可分为18个零，确保了资产的稳定性和长期使用。转账费用低，转账确认在不到一分钟的时间内完成。
媒体出版物：https：//www.twitter.com/aero_token
https://medium.com/@aerotoken328
可交易的交易所：尚未在任何交易所上市
推荐的气体限制:(默认为60,000）

**Comment by aerotoken** [comment]
Official announcement: https://twitter.com/aero_token/status/1171382333552959490
https://medium.com/@aerotoken328/official-announcement-56b7f6e312fe

Project team background: The AeroToken team itself is composed of a group of senior financial people and early virtual currency enthusiasts, contributing to the experience of rolling in the market for many years; also because it is the user of major trading platforms, so it is based on the perspective of the user operating platform. Through self-familiarity with the overall trading process, when creating an inflationary token focus on improving some of the use problems of deflationary and minting and fully optimize, diversify models, and create an environment for friendly novice players to provide users with safer, More time-saving and more convenient services, the AeroToken team is committed to leading a financial revolution like never before in the history of cryptocurrency. AERO IS THE FUTURE
Project basic information: Aerotoken token (AET) is an inflationary crypto-token, operating on the Ethereum blockchain (ERC-20 standard token) which can be used as a currency, a store of value or an investment. Each time an AET is transferred, 1% of the transaction is increased. AeroToken (AET) has a total supply of 500,000 only and is divisible up to 18 zeroes after decimal point (18 decimal), ensuring great stability and long term use of the asset. The transfer fee is low and transfer confirmations happen in less than a minute.
Media publications: https://twitter.com/aero_token/status/1171382333552959490
https://medium.com/@aerotoken328/official-announcement-56b7f6e312fe
Tradeable exchanges: Not yet listed on any exchange
Recommended Gas Limit: (Default is 60,000)

**Comment by sfsy520** [comment]
存在的问题：
1.请检查Checksum格式
2.为确保资料提交的真实性，请在贵方官网或其他经过认证的社交媒体渠道发布公告，并将此公告链接附于「官方公告」。推荐文案：
#imToken# #1636# 我们正在完善 XXX 在 imToken 中的代币相关资料。完成后，大家可以在 imToken 里看到 logo，更方便地管理 XXX，同时能看到更多代币信息。
注：

1636 为 pr 序号，如 https://github.com/consenlabs/token-profile/pull/1636 的序号为 1636，这是帮助 imToken 判断 pr 真实性的关键。
#imToken #1636 标签及其展示形式可自行调整。
若未提供「官方公告」，则无法显示代币信息

**Comment by aerotoken** [comment]
Team background:

The AeroToken team itself is composed of a group of senior financial people and early virtual currency enthusiasts, contributing to the experience of rolling in the market for many years. When creating an inflationary token we focus on improving some of the use problems of deflationary and minting and fully optimize, diversify models, and create an environment for friendly novice players to provide users with safer, more time-saving and more convenient services, the AeroToken team is committed to leading a financial revolution like never before in the history of cryptocurrency. AEROTOKEN IS THE FUTURE

Basic information of the project:

Aerotoken token (AET) is the first inflationary crypto-token, operating on the Ethereum blockchain (ERC-20 standard token) which can be used as a currency, a store of value or an investment. Each time an AET is transferred, 1% of the transaction is increased. AeroToken (AET) has a total supply of 500,000 only and is divisible up to 18 zeroes after decimal point (18 decimal), ensuring great stability and long term use of the asset. The transfer fee is low and transfer confirmations happen in less than a minute.

More about AeroToken

    Official website: https://aerotoken.org
    Telegram: https://t.me/aero_token
    Twitter: https://twitter.com/aero_token
    Medium: https://medium.com/aerotoken328

Media Publications

https://twitter.com/aero_token/status/1171382333552959490
https://medium.com/@aerotoken328/official-announcement-56b7f6e312fe

Tradeable exchanges: Not yet listed on any exchange
Recommended Gas Limit:   60,000

**Pull request closed without merging**
