### PR TITLE
Add BLC token

### PR DESCRIPTION
**Pull request by nightcp**
### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

**.json 及 .png 文件检查项**
- [x] logo 尺寸：120*120 px
- [x] logo 背景：透明
- [x] 代币有至少一笔成功的转账记录
- [x] 此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
- [x] .json 和 .png 文件名一致（包括大小写）

**项目资料补充：**

团队背景：BLC是由Bole基金会发行的全球通用商业代币，BLC初期是基于以太坊ERC20协议发行的商业应用代币，BLC发行总量限定5.2 亿枚，未来会转移到自研的公有链Bolecoin之上。
项目基本情况：BLC基金会与Bole mall、Bole pay、Bole Chat将建立战略合作关系，把BLC建成Bole生态中重要的组成部分。应用在Bole平台的各生态链之中，共享和透明是区块链的核心理念，Bole推出价值共享计划，将BLC全球通用商业代币通过伯乐支付平台余额兑换给Bole用户，让每一位用户参与平台的建设和发展，共建共享Bole区块链生态系统的商业价值。
媒体报道：暂无
收录的交易所：暂无
转账所需 Gas Limit（对 ERC-20 项目方）：60000

---

### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [x] logo dimensions: 120*120 px
- [x] logo background: Transparent
- [x] At least one transaction on the token contract
- [x] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [x] Same document name for both .json and .png (Including capitalization)

**Project background details:**

Team background:BLC is a global commercial token issued by the Bole Foundation. BLC was originally based on the Ethereum ERC20 agreement. The total number of BLC is limited to 520 million. In the future, it will be transferred to the self-developed public chain Bolecoin.
Current situation of the project:The BLC Foundation will establish strategic partnerships with Bole Mall, Bole pay, and Bole Chat to build the BLC into an important part of the Bole ecosystem. Applied in the various ecological chains of the Bole platform, sharing and transparency is the core concept of the blockchain. Bole launches a value sharing plan to convert BLC global commercial tokens to Bole users through the Bole payment platform balance, so that each user Participate in the construction and development of the platform and jointly build the commercial value of the Bole blockchain ecosystem.
Media exposures:No.
Tradeable exchanges:No.
Recommended Gas Limit (For ERC-20 project teams) for transaction:60000

### CODE REVIEW

**Comment by tstt** [comment]
问题已在标签中指明，按教程检查调整

**Comment by nightcp** [comment]
> 问题已在标签中指明，按教程检查调整

问题已解决

**Comment by nightcp** [comment]
> no checksum 的问题还在，参考教程

问题已改，请检查

**Comment by tstt** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 管理资产。

**Pull request merged**
