### PR TITLE
Add seor

### PR DESCRIPTION
**Pull request by sealoracle**
**Project background:**

Official announcement:
[https://medium.com/@SEOR](https://twitter.com/SEOR001)

Project team background:

SEOR team members mainly bring together top technology developers from the blockchain industry and people who have been engaged in financial research for a long time. The team members have been deeply studied in the blockchain industry for more than 7 years, focusing on the research of blockchain technologies such as cross-chain protocols, Oracle protocols, the development and deployment of underlying public chain technologies, and smart contracts, and have accumulated rich industry experience. SEOR team has gathered members who have participated in the development of well-known cryptocurrency exchanges, and members who have participated in multiple blockchain public chain projects. They are proficient in encryption algorithms and various programming languages, and are good at dAPP product design and development.

Project basic information:

SEOR is the next generation of decentralized Web 3.0 application technology development infrastructure, which aims to provide users and developers of Web 3.0 with an easy-to-use blockchain technology development platform. The Low Code Development Platform (LCDP) of SEOR has adopted the self-developed unified protocol family and the customization of contracts for different blockchain systems. It currently supports the deployment of code-free contracts of the EVM compatible chain and the unified code access of some public chains, which can quickly solve the problem of unified interaction of multi-chain smart contracts. Moreover, it provides a customized presentation method of Web 3.0, as well as unified access in the form of cloud services, and unified deployment on the business chain.

SEOR Network combines lightweight Oracle network (LON) and conventional oracle protocol, which can provide flexible data customization. It can not only provide accurate and reliable data on the chain for traditional enterprises and Web 3.0 developers, but also provide data support for breaking the barriers of traditional Internet and the blockchain world. At the same time, it can also provide a unified general data protocol for off-chain data for different blockchain applications, such as GameFi, SocialFi, Tools and other dApps.

As the asset and information exchange bridge of the blockchain system, with SEOR Network’s data protocol family as the core, it provides a comprehensive cross-chain solution that is compatible with different assets and data protocols on each chain, allowing assets on different chains to support Cross-chain transfer and exchange.

Media publications:
https://zycrypto.com/seor-network-the-web-3-0-worlds-infrastructure-and-trust-framework/

Tradeable exchanges:
Bybit

Recommended Gas Limit (For ERC-20 project teams) for transaction: (Default is 60,000)

### CODE REVIEW

**Comment by kaiko1203** [comment]
Missing official announcement: (see details for completeness and accuracy of information)

**Comment by sealoracle** [comment]
> Missing official announcement: (see details for completeness and accuracy of information)

https://twitter.com/SEOR001/status/1548975584919035906?s=20&t=ud-3tgrn2UfcUfBJ3LFNow

please kindly check the link as shown above

**Comment by wens111** [comment]
1. Supplementary description of project background in Chinese
2. Submit the correct address, 0 x800a25741a414ea6e6e2b382435081a479a8cc3c address is not a contract address

**Comment by sealoracle** [comment]
> * Supplementary description of project background in Chinese
> * Submit the correct address, 0 x800a25741a414ea6e6e2b382435081a479a8cc3c address is not a contract address

-Chinese version has been added.
-Our address is base on BSC, and here's the link: (https://bscscan.com/address/0x800a25741a414ea6e6e2b382435081a479a8cc3c)

**Comment by makoshan** [comment]
Currently, this project only handles Ethereum Erc-20 token.BSC chain token is cooperated with debank. If debank already supports it, it will automatically appear in the user's wallet

**Pull request closed without merging**
