### PR TITLE
Add KROM Token

### PR DESCRIPTION
**Pull request by snnicketh**
Please check the following to ensure a successful verification of Token Profile
.json and .png document checklists

 logo dimensions: 120*120 px
 logo background: Transparent
 At least one transaction on the token contract
 For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
 Same document name for both .json and .png (Including capitalization)
Project background:

Project Basics
KROMATIKA is a decentralized crypto trading protocol enabling users to trade crypto assets with ZERO swap fees, NO Front running bots and NO Price Slippage.

KROM token is a non-mintable ERC20 utiliity token, having a 100 millions of total supply EVER.

KROM token is used as a utility token on the platform allowing users to: *Trade cryptoassets. *Receive rewards for securing the other's users trades. *Save on gas fees when trading on Ethereum blockchain.

KROMATIKA consists of:

*Audited smart contracts for creating trades and processing them, all powered by Uniswap. *UI for interacting with KROMatika smart contracts . *Off-chain decentralized processing services, responsible for active processing of the trades, powered by Chainlink Keepers. *KROM token — utility ERC20 token used for paying the service fee. This fee is paid by the users and is used to cover the cost of the processing services (Keepers).

Team Background
The core team is based in Macedonia but has decided to not share any further details as they wish to keep their personal lives private, and not bring any attention onto themselves. However, they are very dedicated to this project's long-term vision. Each and every team member on board has various education and/or experience in field that supports their specific role in which they are bringing to this project. The Dev team members have 9+ years of experience working in both solidity and multiple front-end development languages and have worked on other blockchain related projects.

Media
Official Website: https://kromatika.finance
Twitter: https://twitter.com/KromatikaFi
Medium: https://kromatika-finance.medium.com/
Discord: https://discord.gg/rnmZhcCzn3

### CODE REVIEW

**Comment by evelyn2331** [comment]
Please send us the official statement to get listed in imToken and the logo dimensions should be 120*120 px.

**Comment by sNnickK** [comment]
What official statement ?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by evelyn2331** [comment]
such as this official announcement: (see details in [Completeness and Accuracy of the information](https://github.com/consenlabs/token-profile/blob/master/tutorial/erc20-tutorial.en.md#completeness-and-accuracy-of-the-information))

**Comment by sNnickK** [comment]
Project background:

Project Basics
KROMATIKA is a decentralized crypto trading protocol enabling users to trade crypto assets with ZERO swap fees, NO Front running bots and NO Price Slippage.

KROM token is a non-mintable ERC20 utiliity token, having a 100 millions of total supply EVER.

KROM token is used as a utility token on the platform allowing users to: *Trade cryptoassets. *Receive rewards for securing the other's users trades. *Save on gas fees when trading on Ethereum blockchain.

KROMATIKA consists of:

*Audited smart contracts for creating trades and processing them, all powered by Uniswap. *UI for interacting with KROMatika smart contracts . *Off-chain decentralized processing services, responsible for active processing of the trades, powered by Chainlink Keepers. *KROM token — utility ERC20 token used for paying the service fee. This fee is paid by the users and is used to cover the cost of the processing services (Keepers).

Team Background
The core team is based in Macedonia but has decided to not share any further details as they wish to keep their personal lives private, and not bring any attention onto themselves. However, they are very dedicated to this project's long-term vision. Each and every team member on board has various education and/or experience in field that supports their specific role in which they are bringing to this project. The Dev team members have 9+ years of experience working in both solidity and multiple front-end development languages and have worked on other blockchain related projects.

Media
Official Website: https://kromatika.finance
Twitter: https://twitter.com/KromatikaFi
Medium: https://kromatika-finance.medium.com/
Discord: https://discord.gg/rnmZhcCzn3

**Comment by kaiko1203** [comment]
Please use the official Twitter feed to post information about the imToken to prove that you are the official

**Pull request closed without merging**
