### PR TITLE
Add Matic Token 

### PR DESCRIPTION
**Pull request by vidyaakrishna**
**Project Team Background:**
The full team list is available on our website here: https://matic.network/about/
1. Jaynti Kanani- Co-founder & CEO
• Laying out vision for Matic. Leading tech and research. Wears many hats to push Matic forward the goal of making it best scalability solution for blockchains
• Contributor to Web3.js, Plasma, WalletConnect
Email: jaynti@matic.network
Work experience & photo: https://www.linkedin.com/in/jdkanani

2. Sandeep Nailwal- Co-founder & COO
• Leading Marketing, Branding, Adoption and Operations at Matic
• Partnering with key stakeholders to push Matic
• Leading community interfacing for Matic
Email: sandeep@matic.network
Work experience & photo: https://www.linkedin.com/in/sandeep-nailwal-60709a33

3. Anurag Arjun- Co-founder & CPO
• Leading products at Matic
• Laying out long term vision for Matic products ‘
• Managing product development and roll outs
Email: anurag@matic.network
Work experience & photo: https://www.linkedin.com/in/anuragarjun

**Project Basic Info:**
Matic Network is a Layer 2 scaling solution backed by Binance and Coinbase that aims to provide a generalized Layer 2 platform, enabling Ethereum developers to scale their DApps for large-scale usage. For the initial phase, Matic has launched its hybrid PoS+Plasma sidechain on top of Ethereum which is already gaining huge traction – making Matic one of the fastest growing DApp platforms in the space.
Essentially, Matic aims to provide the infrastructure to overcome the traditional performance bottlenecks of the blockchain ecosystem, to allow all types of DApps to be able to handle large volumes of users.
Layer-2 scaling solution Matic Network with its high performance and low transaction cost sidechain has allowed Ethereum developers, globally the largest blockchain developer community, to build highly scalable Dapps and rich user experiences.
Matic Network is a Layer-2 scaling solution with high performance and low transaction cost sidechains that allows Ethereum developers to build highly scalable Dapps and rich user experiences.

**Matic's key strengths are:**
- L2 transactions secured by Plasma
- Zero effort deployment for existing Ethereum programmers
- Extremely low-cost transactions
- High throughput
- Fast (~1second) confirmation times

**Media Publications:**

We have been featured in more than 50+ articles, please see below for links to some significant stories.
Notable media coverage examples:
https://www.newsbtc.com/2019/06/20/why-binance-and-coinbase-are-betting-on-this-indian-startup/
https://finance.yahoo.com/news/matic-network-first-token-sale-160052658.html
https://m.investing.com/analysis/ieos-have-raised-14b-this-year-heres-how-the-best-ones-performed-so-far-200433157
https://ethereumworldnews.com/could-this-indian-startup-solve-ethereums-main-problem/
https://ambcrypto.com/with-this-startups-mainnet-release-ethereum-scalability-might-soon-become-a-reality/
https://www.crypto-news-flash.com/2020s-crypto-shakeup-is-creating-some-big-winners-and-losers/
https://www.coinspeaker.com/matic-public-staking-testnet/
https://www.coindesk.com/matic-network-mainnet-rollout
https://cointelegraph.com/news/staking-coming-to-matic-on-june-15

**Supported Exchanges**

Binance, Binance US, Bitrabbit, Bitrue, BW, Bilaxy, Huobi, Gate.io, Poloniex, Dcoin, BitForex, BitMax, Coinsuper, Hotbit, HitBTC, Omgfin, Coinone, WazirX, Bitcoin.com Exchange, Cat.Ex, COSS, Binance DEX, CoinEx, Swyftx, KyberSwap, Bitbns, BKEX, Indodax, ProBit, CoinDCX, ZebPay

**Gas Limit:** 21000

### CODE REVIEW

**Comment by vidyaakrishna** [comment]
Announcement: https://docs.matic.network/docs/develop/wallets/getting-started/#wallets

**Comment by sfsy520** [comment]
json文件中overview字段请勿换行

**Comment by vidyaakrishna** [comment]
Change have been done.

**Comment by sfsy520** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 ，imToken 支持比特币, 以太坊, Comos, EOS, 波场, Nervos, 比特币现金, 莱特币，波卡等资产管理；同时支持去中心化币币兑换功能 Tokenlon；转账页面支持 ETH, USDT, EOS, BTC OTC 功能；另外对于没有 ETH 矿工费的用户，也提供 ETH 手续费充值功能。

**Pull request merged**
