### PR TITLE
Add Obee Network-token

### PR DESCRIPTION
**Pull request by T-Rande**
### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

**.json 及 .png 文件检查项**
- [ ] logo 尺寸：120*120 px
- [ ] logo 背景：透明
- [ ] 代币有至少一笔成功的转账记录
- [ ] 此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
- [ ] .json 和 .png 文件名一致（包括大小写）

**项目资料：**

Obee Network官网：https://obee.top
Obee Network 产品：https://www.obee.vip
Obee Network项目白皮书：https://obee.top/whitepaper/OBEE-Whitepaper-cn.pdf 
Obee Network 安卓下载链接：https://obee.top/package/ObeeNetwork-en.apk
Obee Network 详细介绍：https://bbs.nuls.io/t/obee-network-information-links-obee-network/2219?u=obeenetwork

项目介绍：
Obee Network社交平台将是普通用户进入区块链时代的第一款社交产品，是基于区块链社交的激励平台，构建了一套完整的去中心化的社交网络。
让用户在Obee Network上看见全球用户的创作，论坛、热帖、应用和电影。让社交没有边界性，随时随地都可以和其他用户分享精彩的瞬间。
Obee Network是激励型社交平台，Obee Network社交平台具备内容发布系统，评论转发，账户体系，商品，账户体系，新闻博客，活动等模块。

团队背景：技术团队拥有区块链开发专家，对智能合约开发、跨链机制有深入的研究。开发团队成员都拥有3年以上的区块链架构和社交产品开发经验，负责Obee Network生态的技术开发和部署。产品团队曾就职Facebook，Tencent等企业，拥有深度分析能力、资源整合、创新等能力，负责Obee Network生态的功能设计。

媒体报道：
Twitter: https://twitter.com/ObeeNetwork; 
Telegram: https://t.me/ObeeNetwork; 
Reddit: https://www.reddit.com/user/ObeeNetwork/; 
Medium: https://medium.com/@ObeeNetwork/

收录的交易所：Uniswap
https://uniswap.info/token/0x3678d8cc9eb08875a3720f34c1c8d1e1b31f5a11
Uniswap 流动性奖励声明：https://bbs.nuls.io/t/obee-network/2195?u=obeenetwork
转账所需 Gas Limit（对 ERC-20 项目方）:（默认为 60000）

---

### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [ ] logo dimensions: 120*120 px
- [ ] logo background: Transparent
- [ ] At least one transaction on the token contract
- [ ] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [ ] Same document name for both .json and .png (Including capitalization)

**Project Background:**

Obee Network website: https://obee.top
Obee Network products: https://www.obee.vip
Obee Network Android download link: https://obee.top/package/ObeeNetwork-en.apk
Obee Network project white paper: https://obee.top/whitepaper/OBEE-Whitepaper-en.pdf
Obee Network detailed introduction: https://bbs.nuls.io/t/obee-network-information-links-obee-network/2219?u=obeenetwork

Project Introduction:
The Obee Network social platform will be the first social product for ordinary users to enter the era of blockchain. It is an incentive platform based on blockchain social interaction and has built a complete decentralized social network.
Let users see the creations, forums, hot posts, applications, and movies of users from all over the world on Obee Network. Let social without boundaries, you can share wonderful moments with other users anytime, anywhere.
Obee Network is an incentive-based social platform. The Obee Network social platform has modules such as content publishing systems, comment forwarding, account system, products, account system, news blogs, and events.

Project team background: The technical team has blockchain development experts and has in-depth research on smart contract development and cross-chain mechanisms. The members of the development team have more than 3 years of experience in blockchain architecture and social product development and are responsible for the technical development and deployment of the Obee Network ecosystem. The product team has worked on Facebook, Tencent, and other companies, has in-depth analysis capabilities, resource integration, innovation, and other capabilities, and is responsible for the functional design of the Obee Network ecosystem.

Media publications:
Twitter: https://twitter.com/ObeeNetwork; 
Telegram:https://t.me/ObeeNetwork; 
Reddit:https://www.reddit.com/user/ObeeNetwork/; 
Medium:https://medium.com/@ObeeNetwork/

Tradeable exchanges:
Uniswap
https://uniswap.info/token/0x3678d8cc9eb08875a3720f34c1c8d1e1b31f5a11
Uniswap liquidity reward statement：https://bbs.nuls.io/t/about-obee-networks-reward-statement-for-liquidity-providers/2196?u=obeenetwork
Recommended Gas Limit (For ERC-20 project teams) for the transaction: (Default is 60,000)

### CODE REVIEW

**Comment by T-Rande** [comment]
Thx

**Comment by T-Rande** [comment]
为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：
.json 及 .png 文件检查项

 logo 尺寸：120*120 px
 logo 背景：透明
 代币有至少一笔成功的转账记录
 此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
 .json 和 .png 文件名一致（包括大小写）
项目资料：

Obee Network官网：https://obee.top
Obee Network 产品：https://www.obee.vip
Obee Network项目白皮书：https://obee.top/whitepaper/OBEE-Whitepaper-cn.pdf
Obee Network 安卓下载链接：https://obee.top/package/ObeeNetwork-en.apk
Obee Network 详细介绍：https://bbs.nuls.io/t/obee-network-information-links-obee-network/2219?u=obeenetwork



官方公告：https://obee.top/cn-notice.html#
项目介绍：
Obee Network社交平台将是普通用户进入区块链时代的第一款社交产品，是基于区块链社交的激励平台，构建了一套完整的去中心化的社交网络。
让用户在Obee Network上看见全球用户的创作，论坛、热帖、应用和电影。让社交没有边界性，随时随地都可以和其他用户分享精彩的瞬间。
Obee Network是激励型社交平台，Obee Network社交平台具备内容发布系统，评论转发，账户体系，商品，账户体系，新闻博客，活动等模块。

团队背景：技术团队拥有区块链开发专家，对智能合约开发、跨链机制有深入的研究。开发团队成员都拥有3年以上的区块链架构和社交产品开发经验，负责Obee Network生态的技术开发和部署。产品团队曾就职Facebook，Tencent等企业，拥有深度分析能力、资源整合、创新等能力，负责Obee Network生态的功能设计。

媒体报道：
Twitter: https://twitter.com/ObeeNetwork;
Telegram: https://t.me/ObeeNetwork;
Reddit: https://www.reddit.com/user/ObeeNetwork/;
Medium: https://medium.com/@ObeeNetwork/

收录的交易所：Uniswap
https://uniswap.info/token/0x3678d8cc9eb08875a3720f34c1c8d1e1b31f5a11
Uniswap 流动性奖励声明：https://bbs.nuls.io/t/obee-network/2195?u=obeenetwork
转账所需 Gas Limit（对 ERC-20 项目方）:（默认为 60000）

Please check the following to ensure a successful verification of Token Profile
.json and .png document checklists

 logo dimensions: 120*120 px
 logo background: Transparent
 At least one transaction on the token contract
 For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
 Same document name for both .json and .png (Including capitalization)
Project Background:

Obee Network website: https://obee.top
Obee Network products: https://www.obee.vip
Obee Network Android download link: https://obee.top/package/ObeeNetwork-en.apk
Obee Network project white paper: https://obee.top/whitepaper/OBEE-Whitepaper-en.pdf
Obee Network detailed introduction: https://bbs.nuls.io/t/obee-network-information-links-obee-network/2219?u=obeenetwork


Official Announcement ：https://obee.top/notice.html

Project Introduction:
The Obee Network social platform will be the first social product for ordinary users to enter the era of blockchain. It is an incentive platform based on blockchain social interaction and has built a complete decentralized social network.
Let users see the creations, forums, hot posts, applications, and movies of users from all over the world on Obee Network. Let social without boundaries, you can share wonderful moments with other users anytime, anywhere.
Obee Network is an incentive-based social platform. The Obee Network social platform has modules such as content publishing systems, comment forwarding, account system, products, account system, news blogs, and events.

Project team background: The technical team has blockchain development experts and has in-depth research on smart contract development and cross-chain mechanisms. The members of the development team have more than 3 years of experience in blockchain architecture and social product development and are responsible for the technical development and deployment of the Obee Network ecosystem. The product team has worked on Facebook, Tencent, and other companies, has in-depth analysis capabilities, resource integration, innovation, and other capabilities, and is responsible for the functional design of the Obee Network ecosystem.

Media publications:
Twitter: https://twitter.com/ObeeNetwork;
Telegram:https://t.me/ObeeNetwork;
Reddit:https://www.reddit.com/user/ObeeNetwork/;
Medium:https://medium.com/@ObeeNetwork/

Tradeable exchanges:
Uniswap
https://uniswap.info/token/0x3678d8cc9eb08875a3720f34c1c8d1e1b31f5a11
Uniswap liquidity reward statement：https://bbs.nuls.io/t/about-obee-networks-reward-statement-for-liquidity-providers/2196?u=obeenetwork
Recommended Gas Limit (For ERC-20 project teams) for the transaction: (Default is 60,000)

**Comment by T-Rande** [comment]
@sfsy520

**Comment by T-Rande** [comment]
thank you very much

**Comment by sfsy520** [comment]
非常抱歉，此token已经有代币信息，如需修改，请重新提交PR

**Pull request closed without merging**
