### PR TITLE
Add Oldtimer (OLD) Token

### PR DESCRIPTION
**Pull request by oldtimersoffer**
### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

**.json 及 .png 文件检查项**
- [x] logo 尺寸：120*120 px
- [x] logo 背景：透明
- [x] 代币有至少一笔成功的转账记录
- [x] 此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
- [x] .json 和 .png 文件名一致（包括大小写）

项目资料：https://www.oldtimersoffer.com/wp-content/uploads/whitepaper/oldtimer_whitepaper.pdf

官方公告：https://www.oldtimersoffer.com/
团队背景：https://www.oldtimersoffer.com/about-us/
项目基本情况：https://www.oldtimersoffer.com/wp-content/uploads/photos/RoadMap.jpg
媒体报道：https://www.instagram.com/Oldtimers.Offer/

---

### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [x] logo dimensions: 120*120 px
- [x] logo background: Transparent
- [x] At least one transaction on the token contract
- [x] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [x] Same document name for both .json and .png (Including capitalization)

Project background: https://www.oldtimersoffer.com/wp-content/uploads/whitepaper/oldtimer_whitepaper.pdf

Official announcement: https://www.oldtimersoffer.com/
Project team background: https://www.oldtimersoffer.com/about-us/
Project basic information: https://www.oldtimersoffer.com/wp-content/uploads/photos/RoadMap.jpg
Media publications: https://www.instagram.com/Oldtimers.Offer/

### CODE REVIEW

**Comment by oldtimersoffer** [comment]
0x6e514de4c2675feeb51d759977b4222dc65556af

**Comment by tstt** [comment]
问题已在标签中注明，另外，请确保贵方官网可正常访问。

**Comment by oldtimersoffer** [comment]
Dear,



Our main office is located in Bay of Kotor
<https://en.wikipedia.org/wiki/Bay_of_Kotor>(Adriatic Sea). The Bay of
Kotor is one of the most beautiful bays in the world.



We do not follow the traditional methods used by other de-centralized
projects. Oldtimers Offer Team, have chosen to stay anonymous. Regardless
of anonymity – with strong work ethics and peerless innovation, Oldtimers
Offer will strive with an aim to deliver industry leading product of the
highest quality possible.



We bring classic car/motorcycle sellers, buyers and mechanics on one
platform and allow them to interact without the interference of third
parties. To ensure the smooth functioning and to resolve the age-old
problems of the vintage vehicle industry, we provide an environment where
everyone gets their due share.



We hope that you will add our token.

Thank you for your time and cooperation,



Kindly regards,

Oldtimers Offer Team,

https://www.oldtimersoffer.com/

oldtimersoffer@gmail.com

**Comment by tstt** [comment]
I think there is no influence to keep your team stay anonymous when providing official annoucement.

https://github.com/consenlabs/token-profile/blob/master/tutorial/erc20-tutorial.en.md#completeness-and-accuracy-of-the-information

image

**Comment by tstt** [comment]
> https://github.com/consenlabs/token-profile/blob/master/tutorial/erc20-tutorial.en.md#completeness-and-ac

where is the announcement link？

**Comment by oldtimersoffer** [comment]
Dear,

The announcement link:
https://www.oldtimersoffer.com/old-token/

Thank you for your time,
Best regards,
Oldtimers Offer Team

**Comment by tstt** [comment]
Welcome to recommend imToken 2.0 to your token holders to manage their token.

**Comment by oldtimersoffer** [comment]
Dear,

We will, our favorite wallet is imToken btw

Best Regards

**Pull request merged**
