### PR TITLE
Added TAL Token

### PR DESCRIPTION
**Pull request by lavimalik**
### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [x] logo dimensions: 120*120 px
- [x] logo background: Transparent
- [x] At least one transaction on the token contract
- [x] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [x] Same document name for both .json and .png (Including capitalization)

**Project background:**

Official announcement: 
https://twitter.com/TokenThaler/status/1163492710310961152

Project team background:
The team details can be found on the Team Details page and linkedin company page https://www.thalertoken.com/about-the-team

Project basic information:
Thaler is a bridge creator between our community and large investors.The idea of crypto mass education will lead our token to mass adoption.Thaleris a peer-to-peer digital currency which encourages growth within theblockchain technology community. It aims to strengthen the path towards mass adoption ofcryptocurrency technology through investing inunique innovations.Thaleris fully decentralized and by definition the most trustable coin on the market!

Media publications:
https://youtu.be/JShCKMWjLOE

Tradeable exchanges: https://token.store/eth/trade/0x375a08ce3a460f20bbafd282be1e3579a2c31f41

Recommended Gas Limit (For ERC-20 project teams) for transaction: (Default is 60,000)

### CODE REVIEW

**Comment by tstt** [comment]
about official announcement:
https://github.com/consenlabs/token-profile/blob/master/tutorial/erc20-tutorial.zh-CN.md#%E8%B5%84%E6%96%99%E7%9A%84%E5%AE%8C%E6%95%B4%E5%92%8C%E5%87%86%E7%A1%AE

image

**Comment by lavimalik** [comment]
https://twitter.com/TokenThaler/status/1163492710310961152

Here is the official confirmation

**Comment by lavimalik** [comment]
image

**Comment by lavimalik** [comment]
@tstt please confirm the official announcement here and please add the TAL token to imToken wallet!

https://twitter.com/TokenThaler/status/1163492710310961152

**Comment by lavimalik** [comment]
https://twitter.com/TokenThaler/status/1163492710310961152

@tstt verification official announcement has been published, awaiting your response

**Comment by lavimalik** [comment]
@tstt please inform us if there are any more steps we need to take or if there are any more questions for us!

**Comment by lavimalik** [comment]
@tstt it would be very much appreciated if we can get a response from you and if you can verify the official announcement here: https://twitter.com/TokenThaler/status/1163492710310961152

**Comment by lavimalik** [comment]
@tstt I hope you're doing well!

Is there any comments on this pull request or anything I need to know which may speed up the listing process?

Thanks!

**Comment by tstt** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 管理资产。

**Pull request merged**
