### PR TITLE
Add AWO token

### PR DESCRIPTION
**Pull request by aworldvc**
Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [x] logo dimensions: 120*120 px
- [x] logo background: Transparent
- [x] At least one transaction on the token contract
- [x] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [x] Same document name for both .json and .png (Including capitalization)

**Project background:**

Official announcement:
#imToken #6491 We are providing AWO token’s information on imToken. After completion, you can see the logo and full information inside imToken’s Token Manager.  https://twitter.com/Aworldvc/status/1329380537278943233

Project team background:
The founder of Aworld Blockchain LTD, Mr.Lukasik is a seasoned tech entrepreneur, with over 30 years in the ICT field and extensive experience, research and development, financial analysis, and operations management.
In 2010, he founded Hotspot network airbone access, which was acquired by PLDT in 2018. Now, he forcus in blockchain field, founded Aworld blockchain LTD and launched the Aworld platform token AWO in 2020.
Mr. Lukasik is considered be one of the pioneers and thought leaders of UK tech startup scene. He regularly speaks at local and international forums on the UK startup ecosystem such as the Harvard business conference in London, with the Global Innovation Gathering at the annual public conference in Berlin, and regional startup conferences in Asia.

Project basic information:
Aworld wants to be a fully community driven decentralized exchange, with community users holding 100% of the platform token AWO.
The establishment of Aworld will become the only innovative company in the decentralized financial DeFi world. We creatively solve the problems in the existing DeFi market. Through strong experience in intelligent contract interaction and risk management, we use the advanced technology of blockchain to combine a series of intelligent protocols, which bring excellent participation experience and one-stop high income for investors, and constantly capture the growth price of DeFi At the same time, it also gives investors more economic value.

Media publications:
Official Website: https://www.aworld.vc
Twitter: https://twitter.com/Aworldvc
Telegram: https://t.me/Aworldvc
Medium: https://aworldvc.medium.com/

Tradeable exchanges:80000

### CODE REVIEW

**Comment by sfsy520** [comment]
为确保资料提交的真实性，请在贵方官网或其他经过认证的社交媒体渠道发布公告，并将此公告链接附于「官方公告」。推荐文案：
#imToken# #1636# 我们正在完善 XXX 在 imToken 中的代币相关资料。完成后，大家可以在 imToken 里看到 logo，更方便地管理 XXX，同时能看到更多代币信息。
注：
* 1636 为 pr 序号，如 https://github.com/consenlabs/token-profile/pull/1636 的序号为 1636，这是帮助 imToken 判断 pr 真实性的关键。
* #imToken #1636 标签及其展示形式可自行调整。
* 若未提供「官方公告」，则无法显示代币信息。

**Comment by aworldvc** [comment]
Please check the following to ensure a successful verification of Token Profile

.json and .png document checklists

 logo dimensions: 120*120 px
 logo background: Transparent
 At least one transaction on the token contract
 For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
 Same document name for both .json and .png (Including capitalization)
Project background:

Official announcement:
#imToken #6491 We are providing AWO token’s information on imToken. After completion, you can see the logo and full information inside imToken’s Token Manager. https://twitter.com/Aworldvc/status/1329380537278943233

Project team background:
The founder of Aworld Blockchain LTD, Mr.Lukasik is a seasoned tech entrepreneur, with over 30 years in the ICT field and extensive experience, research and development, financial analysis, and operations management.
In 2010, he founded Hotspot network airbone access, which was acquired by PLDT in 2018. Now, he forcus in blockchain field, founded Aworld blockchain LTD and launched the Aworld platform token AWO in 2020.
Mr. Lukasik is considered be one of the pioneers and thought leaders of UK tech startup scene. He regularly speaks at local and international forums on the UK startup ecosystem such as the Harvard business conference in London, with the Global Innovation Gathering at the annual public conference in Berlin, and regional startup conferences in Asia.

Project basic information:
Aworld wants to be a fully community driven decentralized exchange, with community users holding 100% of the platform token AWO.
The establishment of Aworld will become the only innovative company in the decentralized financial DeFi world. We creatively solve the problems in the existing DeDi market. Through strong experience in intelligent contract interaction and risk management, we use the advanced technology of blockchain to combine a series of intelligent protocols, which bring excellent participation experience and one-stop high income for investors, and constantly capture the growth price of DeFi At the same time, it also gives investors more economic value.

Media publications:
Official Website: https://www.aworld.vc
Twitter: https://twitter.com/Aworldvc
Telegram: https://t.me/Aworldvc
Medium: https://aworldvc.medium.com/

Tradeable exchanges:80000

**Comment by aworldvc** [comment]
> 为确保资料提交的真实性，请在贵方官网或其他经过认证的社交媒体渠道发布公告，并将此公告链接附于「官方公告」。推荐文案：
> #imToken# #1636# 我们正在完善 XXX 在 imToken 中的代币相关资料。完成后，大家可以在 imToken 里看到 logo，更方便地管理 XXX，同时能看到更多代币信息。
> 注：
> 
> * 1636 为 pr 序号，如 [https://github.com/consenlabs/token-profile/pull/1636 的序号为](https://github.com/consenlabs/token-profile/pull/1636%C2%A0%E7%9A%84%E5%BA%8F%E5%8F%B7%E4%B8%BA) 1636，这是帮助 imToken 判断 pr 真实性的关键。
> * #imToken #1636 标签及其展示形式可自行调整。
> * 若未提供「官方公告」，则无法显示代币信息。

Hi, we just resubmitted 3 days before, please check it out as soon as possible, thanks.

**Comment by sfsy520** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 ，imToken 支持比特币, 以太坊, Comos, EOS, 波场, Nervos, 比特币现金, 莱特币，波卡等资产管理；同时支持去中心化币币兑换功能 Tokenlon；转账页面支持 ETH, USDT, EOS, BTC OTC 功能；另外对于没有 ETH 矿工费的用户，也提供 ETH 手续费充值功能。

**Pull request merged**
