### PR TITLE
Add LKK token

### PR DESCRIPTION
**Pull request by RootttAndy**
### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

**.json 及 .png 文件检查项**
- [ ] logo 尺寸：120*120 px
- [ ] logo 背景：透明
- [ ] 代币有至少一笔成功的转账记录
- [ ] 此项对于 ERC-20 项目方：0xb28D389f751f669fe5e5539aE905d37C24C4c17C
- [ ] .json 和 .png 文件名一致（包括大小写）

**项目资料：**

官方公告：https://www.mosaicfantasy.io/community/news/29
团队背景：MOSAIC团队成立于2020年，由来自美国和新加坡的20多名核心成员组成，包括加密货币领域、银行金融、风险投资、游戏开发、计算机开发、市场营销等领域的精英。
项目基本情况：MF（MosaicFantasy）是一款基于BSC（Binance Smart Chain）的大型区块链游戏，允许玩家“玩赚钱”。MF通过自营生态经济，创造了一个独立而精致的虚拟世界，其中生活着各种拥有超能力的神奇生物——马赛克。在这个神奇的世界里，玩家可以通过参与冒险、战斗等生态贡献来获得和升级不同种类的马赛克。
媒体报道：
收录的交易所：
转账所需 Gas Limit（对 ERC-20 项目方）：（默认为 60000）

---

### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [ ] logo dimensions: 120*120 px
- [ ] logo background: Transparent
- [ ] At least one transaction on the token contract
- [ ] For ERC-20 project teams: 0xb28D389f751f669fe5e5539aE905d37C24C4c17C
- [ ] Same document name for both .json and .png (Including capitalization)

**Project background:**

Official announcement:https://www.mosaicfantasy.io/community/news/29
Project team background:The MOSAIC team was established in 2020 and is composed of more than 20 core members from the United States and Singapore, including the cryptocurrency field, banking and finance, venture capital, game development, computer development, marketing and other fields Elite.
Project basic information:MF (MosaicFantasy) is a massive blockchain game based on BSC (Binance Smart Chain) which allows the gamers to “Play to Earn”. With self-operating ecological economy, MF creates an independent and sophisticated virtual world in which lives various fantastic creatures holding superpower-Mosaic. In this amazing world, players are able to obtain and upgrade different kinds of Mosaic by taking part in the adventure, battles and other ecological contribution.
Media publications:
Tradeable exchanges:
Recommended Gas Limit (For ERC-20 project teams) for transaction: (Default is 60,000)

### CODE REVIEW

**Comment by RootttAndy** [comment]
It's OK？

**Comment by kaiko1203** [comment]
Didn't see your company profile

**Comment by RootttAndy** [comment]
> 没有看到您的公司资料

What is the specific content?

**Comment by RootttAndy** [comment]
Sorry,What is the specific content?Please 从 Windows 版邮件发送 发件人: kaiko1203发送时间: 2022年3月3日 14:20收件人: consenlabs/token-profile抄送: RootttAndy; Author主题: Re: [consenlabs/token-profile] Add LKK token (PR #7326) Didn't see your company profile—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by RootttAndy** [comment]
What is the specific content? 
What should I do?

**Comment by RootttAndy** [comment]
> 没有看到您的公司资料



> Didn't see your company profile

updated,is't right?

**Comment by RootttAndy** [comment]
> Didn't see your company profile

Updated,is't right?

**Comment by RootttAndy** [comment]
Updated 从 Windows 版邮件发送 发件人: kaiko1203发送时间: 2022年3月3日 14:20收件人: consenlabs/token-profile抄送: RootttAndy; Author主题: Re: [consenlabs/token-profile] Add LKK token (PR #7326) Didn't see your company profile—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by kaiko1203** [comment]
hello, you are missing Chinese introduction and project introduction

**Comment by RootttAndy** [comment]
> hello, you are missing Chinese introduction and project introduction

Updated,is't OK?

**Comment by kaiko1203** [comment]
1. Parsing error in line 1
2. Please provide the contract address, the one you are submitting is not the contract address
3.Your PR is missing project information

**Comment by RootttAndy** [comment]
> 1. Parsing error in line 1
> 2. Please provide the contract address, the one you are submitting is not the contract address
>    3.Your PR is missing project information

update，0xb28D389f751f669fe5e5539aE905d37C24C4c17C
anything else?Please be more specific

**Pull request merged**
