### PR TITLE
Add EPK token

### PR DESCRIPTION
**Pull request by msSj7svHwsdlKt0G**
### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

**.json 及 .png 文件检查项**
- [ ] logo 尺寸：120*120 px
- [ ] logo 背景：透明
- [ ] 代币有至少一笔成功的转账记录
- [ ] 此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
- [ ] .json 和 .png 文件名一致（包括大小写）

**项目资料：**

官方公告：https://ethplayer.io/
团队背景：
项目基本情况：风云令（EPK）是ETH Player链上游戏系统内的通行令牌，总量10亿，其中9亿锁仓于合约地址，仅在项目重启时自动补偿给玩家；剩余1亿的中2100万用于创世兑换，7900万将根据市场发展而逐步流通。用户在解锁账号、领取收益消耗的EPK将1:1销毁，直至EPK市场流通量恒定1000万枚。
媒体报道：
收录的交易所：
转账所需 Gas Limit（对 ERC-20 项目方）：（默认为 60000）

---

### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [ ] logo dimensions: 120*120 px
- [ ] logo background: Transparent
- [ ] At least one transaction on the token contract
- [ ] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [ ] Same document name for both .json and .png (Including capitalization)

**Project background:**

Official announcement:https://ethplayer.io/
Project team background:
Project basic information:EPK is the utility token within ETH Player. The total supply of EPK is 1 billion, of which 900 million is locked by the inherent smart contract which, if needed, is released only to compensate the players when the project is restarted. As for the remaining 100 million, 21 million is open for public offer during the genesis stage, and 79 million is the overall market circulation at first. All the EPK used to unlock accounts and pay profits withdraw fees will be burned until the market circulation of EPK is reduced to 10 million.
Media publications:
Tradeable exchanges:
Recommended Gas Limit (For ERC-20 project teams) for transaction: (Default is 60,000)

### CODE REVIEW

**Comment by tstt** [comment]
其他没问题，但不要改动模版的内容：
image

**Comment by msSj7svHwsdlKt0G** [comment]
> 其他没问题，但不要改动模版的内容：
> image

已经用[https://raw.githubusercontent.com/consenlabs/token-profile/master/erc20/%24template.json](url)覆盖了误修改的模版文件

**Comment by tstt** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 管理资产。

**Pull request merged**
