### PR TITLE
add ftbb token

### PR DESCRIPTION
**Pull request by AceLuodan**
### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

**.json 及 .png 文件检查项**
- [x] logo 尺寸：120*120 px
- [x] logo 背景：透明
- [x] 代币有至少一笔成功的转账记录
- [x] 此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
- [x] .json 和 .png 文件名一致（包括大小写）

**项目资料：**

官方公告：https://twitter.com/FBTT6
团队背景：我们是新加坡、悉尼、墨尔本等多地远程协作构建的一个团队，我们洞察到外汇交易行业，存在丰厚利润的同时，有着较高的风险，普通大众并不能够轻易的获得利润并以此为生，我们团队内有多位外汇交易、金融行业的专家，将致力于解决这个问题，为普通用户带来获得稳定盈利的能力。
项目基本情况：在项目开始以前，已经与多家外汇券商有实际业务合作，通过社群和社区方式汇聚了5W+的外汇行业用户，行业急需解决的问题，在技术上已经有多项完成攻克，且有几个项目已经开始产品即服务的形式进行商业化，为了将商业效果最大化，通过本项目整合资源，借助区块链的特性，加速项目商业化的同时，扩大受众和潜在受众群体规模，提升大数据的深度挖掘价值，带来更高的估值，促进行业更健康的发展。
媒体报道：
收录的交易所：
转账所需 Gas Limit（对 ERC-20 项目方）：60000

---

### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [x] logo dimensions: 120*120 px
- [x] logo background: Transparent
- [x] At least one transaction on the token contract
- [x] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [x] Same document name for both .json and .png (Including capitalization)

**Project background:**

Official announcement: https://twitter.com/FBTT6
Project team background:We are a team built by remote cooperatives in Singapore, Sydney, Melbourne, etc. We have an insight into the foreign exchange trading industry, which has a high profit and a high risk. The general public cannot easily make profits and make a living. There are a number of experts in the foreign exchange trading and financial industry within our team who will work to solve this problem and bring ordinary users the ability to obtain stable profits.
The basic situation of the project: Before the start of the project, it has already had actual business cooperation with a number of foreign exchange brokers, and has gathered 5W+ foreign exchange industry users through community and community methods. The problems urgently needed to be solved in the industry have been overcome in technology. And several projects have begun to commercialize the form of product as a service. In order to maximize the commercial effect, integrate resources through the project, and use the characteristics of the blockchain to accelerate the commercialization of the project while expanding the audience and potential audience size. To enhance the depth of big data mining, bring higher valuations, and promote healthier development of the industry
Project basic information:Before the start of the project, it has already had actual business cooperation with a number of foreign exchange brokers. The 5W+ foreign exchange industry users have been gathered through the community and community. The problems that the industry urgently needs to solve have been solved in technology, and there are several The project has begun to commercialize the form of product as a service. In order to maximize the commercial effect, integrate resources through the project, and accelerate the commercialization of the project with the help of the characteristics of the blockchain, expand the size of the audience and potential audience, and enhance the big data. The depth of the excavation value, bring higher valuations, and promote the healthier development of the industry.
Media publications:
Tradeable exchanges:
Recommended Gas Limit (For ERC-20 project teams) for transaction: 60000

### CODE REVIEW

**Comment by AceLuodan** [comment]
why not merge？

**Comment by tstt** [comment]
两个问题：
1. https://github.com/consenlabs/token-profile/blob/master/tutorial/erc20-tutorial.zh-CN.md#%E8%B5%84%E6%96%99%E7%9A%84%E5%AE%8C%E6%95%B4%E5%92%8C%E5%87%86%E7%A1%AE

image

2. 
image

**Comment by AceLuodan** [comment]
updated，please  merge

**Comment by tstt** [comment]
请确保发布官方公告的 twitter 可从贵方官网跳转。

**Comment by AceLuodan** [comment]
好的

**Comment by AceLuodan** [comment]
官网这几天上线，上线之后肯定是可以从官网跳转过去的

**Comment by AceLuodan** [comment]
> 请确保发布官方公告的 twitter 可从贵方官网跳转。

官网这几天上线，上线之后肯定是可以从官网跳转过去的

**Comment by AceLuodan** [comment]
> 请确保发布官方公告的 twitter 可从贵方官网跳转。

请问下要怎么验证？

**Comment by AceLuodan** [comment]
> 请确保发布官方公告的 twitter 可从贵方官网跳转。

已可以跳转，

**Comment by AceLuodan** [comment]
image

**Comment by AceLuodan** [comment]
http://fbtt.org/

**Comment by tstt** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 管理资产。

**Pull request merged**
