### PR TITLE
OnlyChain_commit

### PR DESCRIPTION
**Pull request by onlychain**

### CODE REVIEW

**Comment by onlychain** [comment]
OnlyChain NEWS:

**Comment by onlychain** [comment]
OnlyChain NEWS（OnlyChain新闻报道）:
http://www.stoutiao.vip/e/action/ShowInfo.php?classid=26&id=4646

http://shilian.com/huiyi/2018/0709/8547.html

https://www.jinse.com/bitcoin/211292.html

http://wemedia.ifeng.com/68504161/wemedia.shtml

**Comment by onlychain** [comment]
请问什么时候开始审核

**Comment by angara79** [comment]
https://github.com/armors

**Pull request merged**
