### PR TITLE
Add came token

### PR DESCRIPTION
**Pull request by CrazyMiner-came**
###  Project team background:

Martin Wei
CEO
Chinese American, Ph.D. in computer science from Massachusetts Institute of technology, former senior product manager of Google, activist of encryption community in Silicon Valley, early investor of bitcoin and Ethereum, has founded mobile game platform, with users covering dozens of countries and regions around the world. It has rich industry resources and a wide range of contacts in the field of science and technology and investment, and has experience in Entrepreneurship and management of operation projects.

Williams LEE
CTO
Chinese-American, Doctor of Computer Science, Massachusetts Institute of Technology, USA. He has worked in DELL, Facebook and Amazon successively. He has more than 10 years'experience in software development. Later, he jointly founded Block Chain Technology Research and Development Company in the United States to expand the global Block Chain technology business. He has served as a technical consultant for several Block Chain projects, and is also the core of many well-known open source projects in Github. Sender, with rich experience in Internet and block chain industry technology research and development.

### Project basic information:

"Crazy Miner" is the first blockchain game aggregation platform in the world. It drives the ecological value with innovative games and will become the Steam of the blockchain game industry in the future.

- Website : [https://app.cames.io/](https://app.cames.io/)
- Telegram: [https://t.me/CrazyMinerenglish](https://t.me/CrazyMinerenglish)
- Twitter: [https://twitter.com/CrazyMiner8](https://twitter.com/CrazyMiner8)

### Media publications:

- 金色财经 : [https://www.jinse.com/blockchain/529373.html](https://www.jinse.com/blockchain/529373.html)
- 雷电财经 : [http://www.okabcd.com/news/201911/2161178.html](http://www.okabcd.com/news/201911/2161178.html)

### Recommended Gas Limit  for transaction: 60000

### CODE REVIEW

**Comment by sfsy520** [comment]
PR文件重复，请检查

**Comment by CrazyMiner-came** [comment]
> PR文件重复，请检查

麻烦删除第一个

**Comment by CrazyMiner-came** [comment]
> PR文件重复，请检查

哪个文件重复呢？

**Comment by sfsy520** [comment]
非常抱歉，由于该PR长时间未更新，我们先关闭这个PR
如果仍需提交，请参考教程重新提交：
https://github.com/consenlabs/token-profile#token-profile-guideline

**Pull request closed without merging**
