### PR TITLE
Add ISLAMI token

### PR DESCRIPTION
**Pull request by ISLAMIBLOCKCHAIN**
---

### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [x] logo dimensions: 120*120 px
- [x] logo background: Transparent
- [x] At least one transaction on the token contract
- [x] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [x] Same document name for both .json and .png (Including capitalization)

**Project background:**

Official announcement:
Project team background:
Project basic information:
Media publications:
Tradeable exchanges:
Recommended Gas Limit (For ERC-20 project teams) for transaction: (Default is 60,000)

### CODE REVIEW

**Comment by evelyn2331** [comment]
please give us more information about your project, you can follow this tutorial:https://github.com/consenlabs/token-profile/blob/master/tutorial/erc20-tutorial.en.md

**Comment by ISLAMIBLOCKCHAIN** [comment]
Official announcement: https://islamicoin.finance
Project team background: https://islamicoin.finance/#team  Our founder is a certified Solidity developer & Blockchain expert
Project basic information: ISLAMICOIN a cryptocurrency for the global Muslim community
Media publications:
Telegram News: https://t.me/islamicoin1
Telegram group: https://t.me/islamicoinchat
Facebook: https://facebook.com/islamicoin
Twitter: https://twitter.com/islamicoin
YouTube: https://www.youtube.com/c/ISLAMICOIN
Whitepaper: https://secureservercdn.net/160.153.137.40/mmc.19a.myftpupload.com/wp-content/uploads/2021/09/islamicoinE.pdf
Polygonscan: https://polygonscan.com/address/0x9c891326fd8b1a713974f73bb604677e1e63396d

Tradeable exchanges: DoDoex.io
Project is on Polygon POS 
Recommended Gas Limit (For ERC-20 project teams) for transaction: (Default is 60,000)

**Comment by ISLAMIBLOCKCHAIN** [comment]
> Official announcement: https://islamicoin.finance Project team background: https://islamicoin.finance/#team Our founder is a certified Solidity developer & Blockchain expert Project basic information: ISLAMICOIN a cryptocurrency for the global Muslim community Media publications: Telegram News: https://t.me/islamicoin1 Telegram group: https://t.me/islamicoinchat Facebook: https://facebook.com/islamicoin Twitter: https://twitter.com/islamicoin YouTube: https://www.youtube.com/c/ISLAMICOIN Whitepaper: https://secureservercdn.net/160.153.137.40/mmc.19a.myftpupload.com/wp-content/uploads/2021/09/islamicoinE.pdf Polygonscan: https://polygonscan.com/address/0x9c891326fd8b1a713974f73bb604677e1e63396d
> 
> Tradeable exchanges: DoDoex.io Project is on Polygon POS Recommended Gas Limit (For ERC-20 project teams) for transaction: (Default is 60,000)

Official announcement: https://islamicoin.finance
Project team background: https://islamicoin.finance/#team Our founder is a certified Solidity developer & Blockchain expert
Project basic information: ISLAMICOIN a cryptocurrency for the global Muslim community
Media publications:
Telegram News: https://t.me/islamicoin1
Telegram group: https://t.me/islamicoinchat
Facebook: https://facebook.com/islamicoin
Twitter: https://twitter.com/islamicoin
YouTube: https://www.youtube.com/c/ISLAMICOIN
Whitepaper: https://secureservercdn.net/160.153.137.40/mmc.19a.myftpupload.com/wp-content/uploads/2021/09/islamicoinE.pdf
Polygonscan: https://polygonscan.com/address/0x9c891326fd8b1a713974f73bb604677e1e63396d

Tradeable exchanges: DoDoex.io
Project is on Polygon POS
Recommended Gas Limit (For ERC-20 project teams) for transaction: (Default is 60,000)

**Comment by ISLAMIBLOCKCHAIN** [comment]
> please give us more information about your project, you can follow this tutorial:https://github.com/consenlabs/token-profile/blob/master/tutorial/erc20-tutorial.en.md

Please inform me if more information is required. Thank you so much.

**Comment by ISLAMIBLOCKCHAIN** [comment]
> please give us more information about your project, you can follow this tutorial:https://github.com/consenlabs/token-profile/blob/master/tutorial/erc20-tutorial.en.md

Dear @evelyn2331 
hope you are doing well, please tell me how can we proceed? 

Thank you

**Comment by kaiko1203** [comment]
1. You are missing the English description
2. Your logo is not clear, please submit a logo picture of 120*120 size
3. The first line of code parsing error

**Comment by ISLAMIBLOCKCHAIN** [comment]
> 1. You are missing the English description
> 2. Your logo is not clear, please submit a logo picture of 120*120 size
> 3. The first line of code parsing error
>    4.Please provide the contract address, the address you are providing is not the contract address（0x9c891326Fd8b1a713974f73bb604677E1E63396D ）


Good day,
1. English Description: ISLAMICOIN is the largest global Islamic financial project, aiming to achieve financial independence for individuals, businesses, and humanitarian and charitable organizations for the global Muslim community. Built and devised based on the latest blockchain technology developed by Polygon Network, ISLAMICOIN is a token created to establish and launch a secure and reliable TRUSTED Islamic currency that facilitates commerce exchanges and financial transactions around the world.
2. Will upload a new file
3. checking it after this comment
4. This is our contract address on Polygon Pos Chain
0x9c891326Fd8b1a713974f73bb604677E1E63396D
Link: https://polygonscan.com/token/0x9c891326fd8b1a713974f73bb604677e1e63396d

**Comment by kaiko1203** [comment]
Please upload your logo

**Comment by ISLAMIBLOCKCHAIN** [comment]
550 x 500 px

**Comment by ISLAMIBLOCKCHAIN** [comment]
256 logo

**Comment by ISLAMIBLOCKCHAIN** [comment]
logo

**Comment by ISLAMIBLOCKCHAIN** [comment]
> Please upload your logo

Thank you, Please check the logo uploaded here, I don't know why I didn't get a notification on my email when you sent me this message, am really sorry for the delay. Thank you so much.

**Comment by ISLAMIBLOCKCHAIN** [comment]
> Please upload your logo

@kaiko1203
Please note that the logo is also found in files of this pull request and below I will share its link:
https://github.com/consenlabs/token-profile/pull/7311/files#diff-2861be2effddf3f494530a86203688eb9f2a0c96f7702b8ba909b0501477e70a

Thank you
Best regards

**Comment by zengbing15** [comment]
The project is no longer maintained.

**Comment by ISLAMIBLOCKCHAIN** [comment]
> The project is no longer maintained.

Please do you have any advise how we can achieve adding ISLAMI logo to dodoex 

Thank you

**Comment by zengbing15** [comment]
Hi，imToken currently only supports the submission of ERC20 and EOS Token Profile, I'm afraid this is not ERC20 or  EOS token. @ISLAMIBLOCKCHAIN

**Comment by ISLAMIBLOCKCHAIN** [comment]
> Hi， currently imTokenonly supports the submission of ERC20 and EOS Token Profile, I'm afraid this is not ERC20 or EOS token. @ISLAMIBLOCKCHAIN

Our token is ERC20 on polygon PoS chain, polygon is supported on DoDo and many other dex.

Thank you
Best Regards

**Comment by YJN1024** [comment]
0x87F555Eba5B7Ab9Ea53867BabC23921F85DBa567

**Comment by YJN1024** [comment]
0x87F555Eba5B7Ab9Ea53867BabC23921F85DBa567

**Comment by makoshan** [comment]
Currently, this project only handles Ethereum Erc-20 token. Polygon token is cooperated with debank. If debank already supports it, it will automatically appear in the user's wallet.

**Pull request closed without merging**
