### PR TITLE
BTCF

### PR DESCRIPTION
**Pull request by BitcoinFast**
Project basic information:

Bitcoin Fast describes itself as a decentralized Internet-of-value protocol for global payments. Applications include peer-to-peer transactions and exchange platforms. Users can reportedly enjoy instant, secure and nearly free global financial transactions of any size. 

Media publications: 
http://cryptocoindaddy.com/bitcoin-fast-btcf-brings-bitcoin-features-to-stellar-blockchain/
https://bitcointalk.org/index.php?topic=5189149.0

Tradeable exchanges:
https://www.etherflyer.com/trade.html?pairs=BTCF-ETH
https://www.saturn.network/token/ETH/BTCF
https://dexdelta.github.io/#!/trade/BTCF-ETH

Recommended Gas Limit (For ERC-20 project teams) for transaction: 60,000

### CODE REVIEW

**Comment by sfsy520** [comment]
为确保资料提交的真实性，请在贵方官网或其他经过认证的社交媒体渠道发布公告，并将此公告链接附于「官方公告」。推荐文案：
#imToken# #1636# 我们正在完善 XXX 在 imToken 中的代币相关资料。完成后，大家可以在 imToken 里看到 logo，更方便地管理 XXX，同时能看到更多代币信息。
注：
* 1636 为 pr 序号，如 https://github.com/consenlabs/token-profile/pull/1636 的序号为 1636，这是帮助 imToken 判断 pr 真实性的关键。
* #imToken #1636 标签及其展示形式可自行调整。
* 若未提供「官方公告」，则无法显示代币信息。

**Comment by BitcoinFast** [comment]
Done https://bitcfast.com/imtoken/

**Comment by sfsy520** [comment]
Welcome to recommend imToken 2.0 to your token holders to manage their token.

**Comment by BitcoinFast** [comment]
Definitely
 We will make an announcement soon. Can you make wallet fetch price as
well? BTCF is on coinmarketcap and even etherscan shows its price.

Andy

**Pull request merged**
