### PR TITLE
Add ETH2x-FLI token

### PR DESCRIPTION
**Pull request by bford21**
**Project background:**

Official announcement: https://pulseinc.medium.com/introducing-the-flexible-leverage-index-5ec90f2381ce
Project team background: https://defipulse.com/
Project basic information: https://gov.indexcoop.com/t/iip-13-flexible-leverage-index/717
Media publications: N/a
Tradeable exchanges: Uniswap
Recommended Gas Limit (For ERC-20 project teams) for transaction: (Default is 60,000)

### CODE REVIEW

**Comment by sfsy520** [comment]
请检查合约checksum格式。

**Comment by Lumos-yiqun** [comment]
缺少官方公告
地址未 checksun 校验
logo 像素不符合要求
请检查后重新提交

**Comment by bford21** [comment]
> 缺少官方公告
> 地址未 checksun 校验
> logo 像素不符合要求
> 请检查后重新提交

Is there anything else you need from us to get this merged?

**Comment by sfsy520** [comment]
非常抱歉，由于该PR长时间未更新，我们先关闭这个PR
如果仍需提交，请参考教程重新提交：
https://github.com/consenlabs/token-profile#token-profile-guideline

**Pull request closed without merging**
