### PR TITLE
Add gbt token

### PR DESCRIPTION
**Pull request by EnterprisesDigitalToken**
为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

.json 及 .png 文件检查项

logo 尺寸：120*120 px
logo 背景：透明
代币有至少一笔成功的转账记录
此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
.json 和 .png 文件名一致（包括大小写）
项目资料补充：

团队背景：
项目基本情况：Global Blockchain Economy Exchange，简称 GBEX 全球通证中心。注册于塞 舌尔共和国，国际中心设在新加坡，亚太中心设在菲律宾，国际网络中心设在中国 海南, 由美国区块链专家领导的国际顶尖技术团队创建。
媒体报道：无
收录的交易所：GBEX
转账所需 Gas Limit（对 ERC-20 项目方）：（默认为 60000）

Please check the following to ensure a successful verification of Token Profile

.json and .png document checklists

logo dimensions: 120*120 px
logo background: Transparent
At least one transaction on the token contract
For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
Same document name for both .json and .png (Including capitalization)
Project background details:

Team background:Dr. Danton Timmy, CEO of the platform, is responsible for the research and development of the technology platform by Dr. Google Phil, Facebook King Haisheng Senior Algorithmic Engineer and Microsoft Michelle Senior Engineer. The Wells team of the new generation of digital currency exchange runs the project.
Current situation of the project:Global Blockchain Economy Exchange, referred to as GBEX Global Communications Center. Registered in the Republic of Seychelles, the International Center is located in Singapore, the Asia-Pacific Center is located in the Philippines, and the International Network Center is located in Hainan, China.
Media exposures:
Tradeable exchanges:
Recommended Gas Limit (For ERC-20 project teams) for transaction: (Default is 60,000)

### CODE REVIEW

**Comment by tstt** [comment]
问题已在标签中注明，请按教程检查修改

**Comment by tstt** [comment]
问题还在，参考教程，补充了 checksum 转换的工具。

**Comment by tstt** [comment]
同样的问题还在，参考教程，补充了 checksum 转换的工具。

**Comment by EnterprisesDigitalToken** [comment]
When can we check and confirm?

**Pull request merged**
