### PR TITLE
Add DRC token

### PR DESCRIPTION
**Pull request by Cryptographr**
DRC-token

### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

**.json 及 .png 文件检查项**
- [x] logo 尺寸：120*120 px
- [x] logo 背景：透明
- [x] 代币有至少一笔成功的转账记录
- [x] 此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
- [x] .json 和 .png 文件名一致（包括大小写）

**项目资料：**

官方公告：
https://twitter.com/DRCToken/status/1335569595026071554?s=19

团队背景：
linkedin.com/in/maximnurov/

项目基本情况：
数字储备货币（DRC）旨在成为去中心化的数字价值储藏，其供应有限且通货膨胀率为零。它是在新冠病毒危机期间创建的，因为当时财政和货币政策暴露了目前金融体系中的严重漏洞。数字储备货币的概念是由专门从事比特币市场的华盛顿特区数字金融公司创始人马克西姆·努罗夫（Maxim Nurov）提出的。

媒体报道：
- https://finance.yahoo.com/news/digital-currency-drc-set-become-014000436.html
- https://hackernoon.com/bitcoin-demonstrating-the-need-for-a-fully-decentralized-financial-system-maxim-nurov-sg3b31zl

收录的交易所：
https://www.coinpark.com/fullExchange?coinPair=DRC_ETH

转账所需 Gas Limit（对 ERC-20 项目方）：60000

---

### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [x] logo dimensions: 120*120 px
- [x] logo background: Transparent
- [x] At least one transaction on the token contract
- [x] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [x] Same document name for both .json and .png (Including capitalization)

**Project background:**

Official announcement:
https://twitter.com/DRCToken/status/1335569595026071554?s=19

Project team background:
linkedin.com/in/maximnurov/

Project basic information: 
Digital Reserve Currency was designed to become a decentralized digital store of value with a limited supply and a zero inflation rate. It was created during the COVID-19 crisis when fiscal and monetary policies have exposed serious vulnerabilities in the current financial system. The concept of the Digital Reserve Currency was developed by Maxim Nurov, founder of Digital Finance, Washington, DC, financial company that specializes exclusively in the Bitcoin market.

Media publications: 
- https://finance.yahoo.com/news/digital-currency-drc-set-become-014000436.html
- https://hackernoon.com/bitcoin-demonstrating-the-need-for-a-fully-decentralized-financial-system-maxim-nurov-sg3b31zl

Tradeable exchanges: 
https://www.coinpark.com/fullExchange?coinPair=DRC_ETH

Recommended Gas Limit (For ERC-20 project teams) for transaction: 60,000

### CODE REVIEW

**Comment by sfsy520** [comment]
Logo像素不正确

**Comment by Cryptographr** [comment]
Logo updated to be 120x120

**Comment by Cryptographr** [comment]
> Logo像素不正确

Logo updated to be 120x120

**Comment by sfsy520** [comment]
请修改json文件中的state字段，Normal 或 Locked

**Comment by Cryptographr** [comment]
> 请修改json文件中的state字段，Normal 或 Locked

Updated state to be NORMAL

**Comment by sfsy520** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 ，imToken 支持比特币, 以太坊, Comos, EOS, 波场, Nervos, 比特币现金, 莱特币，波卡等资产管理；同时支持去中心化币币兑换功能 Tokenlon；转账页面支持 ETH, USDT, EOS, BTC OTC 功能；另外对于没有 ETH 矿工费的用户，也提供 ETH 手续费充值功能。

**Pull request merged**
