### PR TITLE
Add 99X token

### PR DESCRIPTION
**Pull request by Xinshu1314**
------------------------zh-------------------------------
**团队背景：**
99X 基金会是由广州心术科技有限公司一手创办的，在早期区块链领域有颇多的研究。在2019年5月份正式规划区块链服务，用优质技术服务用户，在2020年1月份，基金会提出为用户着想打造生态健康技术，即刻推出代表Natasha Plan的通行证。
**项目基本情况：**
99X 是Natasha 计划的通行证，确保用户在参加Natasha 计划获取的权益，目前渠道暂未开放。同时基金会决定在2020年8月8日正式启动Natasha Plan，同时完善兑换机制，Dapp生态，游戏探索。提供用户的生态共识。99X发行总量恒定：4200000枚，永不增发。
  更多关于 99X 的信息
APP下载地址：https://www.99xin.xin
99X官网地址：https://www.xinshulnc.xin
telegram：https://t.me/Xinshu1314
Twitter:https://twitter.com/Xinshu1314
**媒体报道：**
币乎：https://bihu.com/article/1989310226
金色：https://www.jinse.com/member/344929
**建议Gas Limit：60000**
------------------------en-------------------------------
**Team background：**
99x foundation was founded by Guangzhou Xinshu Technology Co., Ltd. and has a lot of research in the field of early blockchain. In May 2019, the blockchain service was officially planned to serve users with high-quality technology. In January 2020, the foundation proposed to create ecological health technology for users, and immediately launched a pass on behalf of Natasha plan.
**Basic information of the project：**
99X is the pass of Natasha plan, which ensures the rights and interests of users in participating in Natasha plan. At present, the channel is not open. At the same time, the foundation decided to officially launch Natasha plan on August 8, 2020, while improving the exchange mechanism, DAPP ecology and game exploration. Provide users with ecological consensus. The total number of 99x issuances is constant: 4200000, never increasing.
   More about the 99X：
APP DownLoad：https://www.99xin.xin
99X Website：https://www.xinshulnc.xin
telegram：https://t.me/Xinshu1314
Twitter:https://twitter.com/Xinshu1314
**media coverage：**
Bihu：https://bihu.com/article/1989310226
Jinse：https://www.jinse.com/member/344929
**proposal Gas Limit:60000**

### CODE REVIEW

**Comment by Xinshu1314** [comment]
Add 99X token

**Comment by Xinshu1314** [comment]
-----------zh-----------
www.xinshulnc.xin 域名涉及到项目方安排 暂时无法访问
请访问ip地址：http://154.8.217.135/
-----------en-----------
www.xinshulnc.xin 
The domain name involves the arrangement of the project party, which is temporarily inaccessible
Please visit IP address：http://154.8.217.135/

**Comment by Xinshu1314** [comment]
-----------zh-----------
关于imtoken #5646 文章已发布在官方文章链接中 请审核
-----------en-----------
About imtoken, the article has been published in the official article link, please check

**Comment by Xinshu1314** [comment]
-----------zh-----------
官网公告关于imtoken #5646 Add 99X token 将在官网中间，官网涉及项目方安排，请访问：http://154.8.217.135/
-----------en-----------
The official website announced that imtoken ේ add 99x token will be in the middle of the official website. The official website involves the arrangement of project parties. Please visit:http://154.8.217.135/

**Comment by Xinshu1314** [comment]
0xe8684d50f7784377ae15cad936f263f348aaa6ab

**Comment by laoma6** [comment]
区块链技术服务，imtoken提交，发行代币，白皮书，网站建设，安全审计报告。全网最低价！需要的加微信laoma1145，如有打扰请删除，谢谢。

**Comment by sfsy520** [comment]
非常抱歉，由于该PR长时间未更新，我们先关闭这个PR
如果仍需提交，请参考教程重新提交：
https://github.com/consenlabs/token-profile#token-profile-guideline

**Pull request closed without merging**
