### PR TITLE
Add Crypto.com Chain (CRO) to ERC20 token profile

### PR DESCRIPTION
**Pull request by CeruleanAtMonaco**
### Project team background:
https://crypto.com/en/about.html
### Project current situation:
Crypto.com Chain will be a high performing native
blockchain solution, which will make the transaction flows between
crypto users and merchants accepting crypto seamless, cost-efficient
and secure. It will be the best way to pay and be paid in crypto, anywhere, any crypto, for free.
Find out more in main website: https://www.crypto.com/en/chain

### More:
    twitter: https://twitter.com/cryptocom
    telegram: https://t.me/CryptoComOfficial
    facebook: https://www.facebook.com/CryptoComOfficial
    reddit: https://www.reddit.com/r/Crypto_com
    medium: https://medium.com/@Crypto.com
    discord: https://discord.gg/B6cZahJ
    instagram: https://www.instagram.com/cryptocomofficial

### Media publications:
1. Announcement: https://medium.com/@Crypto.com/crypto-com-announces-new-public-chain-with-airdrop-to-mco-token-holders-b272e76a8369
2. Consultation paper: https://medium.com/@Crypto.com/crypto-com-chain-consultation-paper-2d5ef68ed8e5

### Listed exchange/platform: 
1. Crypto.com Wallet & Card App: https://www.crypto.com/en/wallet.html
2. Digifinex: https://www.digifinex.com/trade/BTC/CRO

### CODE REVIEW

**Comment by tstt** [comment]
hi, the logo is not qualified, the size should be 120*120

**Comment by CeruleanAtMonaco** [comment]
@tstt Hi, thanks for the feedback, just fixed the logo to fit the size.

**Comment by tstt** [comment]
hi, we are willing to merge your pr, but the logo is still not qualified, should like this:
image

**Comment by tstt** [comment]
Welcome to recommend imToken 2.0 to your token holder to manage your token.
imToken Brand Board: https://projects.invisionapp.com/boards/GE3L46DWK2C

**Pull request merged**
