### PR TITLE
Add NDN token

### PR DESCRIPTION
**Pull request by Alanshaw2048**
# Project team background:

NDN Link was founded in January 2019, by a group of entrepreneurs, engineers and expertise’ experience in decentralized technology. Our core team is consists of technical advisor and consultants, many of them was working in Google, Nokia, Qualcomm and Cisco,etc. 

# Project basic information:

NDN Link aims to build a content-centric next generation of network technology with a mission of promoting the development of a next-generation of Internet applications and services. NDN Link combines NDN (Named Data Networking) and blockchain technology to achieve breakthroughs in many directions such as data naming as a whole, proof of work on data routing. Hence, it builds a content-centric next-generation internet communication technology infrastructure to commercialize NDN technology and return to the beginning vision of the Internet.

More about NDN

+ Official website:  [www.ndn.link](https://www.ndn.link/#/)
+ Telegram:  [https://t.me/ndnlinkglobal](https://t.me/ndnlinkglobal)
+ Twitter:  [https://twitter.com/ndnlink](https://twitter.com/ndnlink)
+ Facebook:  [https://www.facebook.com/ndnlink/](https://www.facebook.com/ndnlink/)
+ Medium:  [https://medium.com/ndn-link-official](https://medium.com/ndn-link-official)
+ Youtube:  [https://www.youtube.com/channel/UCftktrI67XQBv6ucNTRT1Vg](https://www.youtube.com/channel/UCftktrI67XQBv6ucNTRT1Vgl)

# Media publications:
+ NEWSBTC [NDN Link (NDN) Becomes the 13th Token Sale Project on OKEx JumpStart](https://www.newsbtc.com/2020/05/11/ndn-link-ndn-becomes-the-13th-token-sale-project-on-okex-jumpstart/)
+ coinspeaker [ICN/NDN: Enhancing Data Transmission in IPFS](https://www.coinspeaker.com/icn-ndn-data-transmission-ipfs/)
+ publish0x [ICN enhance data transmission network in IPFS ](https://www.publish0x.com/icnndnenhancing-data-transmission-in-ipfs/icnndnenhancing-data-transmission-in-ipfs-xlljrnx)

# Tradeable exchanges:

[OKEX](https://www.okex.com/spot/trade/ndn-usdt)

# Recommended Gas Limit : 60000

### CODE REVIEW

**Comment by sfsy520** [comment]
请检查合约checksum格式

**Comment by Alanshaw2048** [comment]
We have updated the contract checksum format

**Comment by Alanshaw2048** [comment]
We have updated contract address in json file name

**Comment by sfsy520** [comment]
为确保资料提交的真实性，请在贵方官网或其他经过认证的社交媒体渠道发布公告，并将此公告链接附于「官方公告」。推荐文案：
#imToken# #1636# 我们正在完善 XXX 在 imToken 中的代币相关资料。完成后，大家可以在 imToken 里看到 logo，更方便地管理 XXX，同时能看到更多代币信息。
注：
* 1636 为 pr 序号，如 https://github.com/consenlabs/token-profile/pull/1636 的序号为 1636，这是帮助 imToken 判断 pr 真实性的关键。
* #imToken #1636 标签及其展示形式可自行调整。
* 若未提供「官方公告」，则无法显示代币信息。

**Comment by Alanshaw2048** [comment]
https://ndnlink.zendesk.com/hc/en-us/articles/360049445094-Regarding-imtoken-5804-

**Comment by sfsy520** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 管理资产。

**Pull request merged**
