### PR TITLE
Add PlotX (PLOT) Info and Logo

### PR DESCRIPTION
**Pull request by ankit5902**
### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [x] logo dimensions: 120*120 px
- [x] logo background: Transparent
- [x] At least one transaction on the token contract
- [x] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [x] Same document name for both .json and .png (Including capitalization)

**Project Background:**

Project basic information: PlotX is a non-custodial prediction market protocol that enables users to earn rewards on high-yield prediction markets. Dubbed as the Uniswap of Prediction Markets, PlotX uses an Automated Market Making algorithm to settle markets and distribute rewards on the Ethereum Blockchain without any counterparty risk. Markets are focused on crypto-pairs like BTC-USD & ETH-USD and created in intervals of 4h, 1d, and 1w.

Project current situation: Beta on Ethereum Mainnet: https://app.plotx.io/

CoinMarketCap page: https://coinmarketcap.com/currencies/plotx/
CoinGecko page: https://www.coingecko.com/en/coins/plotx
Etherscan Page: https://etherscan.io/token/0x72F020f8f3E8fd9382705723Cd26380f8D0c66Bb

Media publications:
1. https://www.coindesk.com/investors-india-defi-scene-central-bank-ban
2. https://cointelegraph.com/news/looks-like-defi-is-coming-to-prediction-markets
3. https://www.newsbtc.com/all/former-nexus-mutual-and-govblocks-developers-launch-uniswap-for-prediction-market/
4. https://blockonomi.com/plotx-guide/

Tradeable exchanges: Uniswap, BitMax

Recommended Gas Limit for the transaction: 60,000

 Website: https://plotx.io
Twitter: https://twitter.com/TryPlotX 
Telegram: https://t.me/plotx_official

### CODE REVIEW

**Comment by sfsy520** [comment]
Logo需背景透明

**Comment by ankit5902** [comment]
> Logo需背景透明

Okay. I’ll get it fixed.

**Comment by ankit5902** [comment]
@sfsy520 I have updated the Logo to the Transparent Background.

**Comment by ankit5902** [comment]
@sfsy520 All checks passed. Please check and let me know if there's still anything missing.

**Comment by sfsy520** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 ，imToken 支持比特币, 以太坊, Comos, EOS, 波场, Nervos, 比特币现金, 莱特币，波卡等资产管理；同时支持去中心化币币兑换功能 Tokenlon；转账页面支持 ETH, USDT, EOS, BTC OTC 功能；另外对于没有 ETH 矿工费的用户，也提供 ETH 手续费充值功能。

**Pull request merged**
