### PR TITLE
硬币EOC添加

### PR DESCRIPTION
**Pull request by EOCbox**
0x7ab2174c7151cb84f91bb818e07a72a5420a37e

### CODE REVIEW

**Comment by EOCbox** [comment]
怎么提交才可以在imtoken显示再记得代币

**Comment by EOCbox** [comment]
{
     "symbol": "EOC",
     "address": "0x7ab2174c7151cb84f91bb818e07a72a5420a37e",
     "overview": {
     "Project description":"Energy video box EOCThe foundation was established in Singapore in 2018. The EOC is based on the basic encrypted currency of the Etifang ERC20 network. It has a total circulation of 26 million pieces and is an extremely rare currency. It can circulate throughout the Etifang block chain network. EOC is based on the decentralized film and television application developed by ERC20. It is promoted, mined, and purchased by the users of the decentralized application(energy box), and is used in the application to generate value through recharging VIP, in-mall item trading, and mining. And as the number of transactions decreases, the market value can continue to increase."
     "Team background": "Founded in Singapore in 2018, the Energy Box EOC Foundation has an average of more than 10 years of Internet product development experience. It is a technical team in the field of early research blocks in foreign countries. The EOC is committed to building a value discovery platform for connecting trading platforms, block chain companies, and investors. Committed to building the world's leading block chain film application"
     },
[Token.zip](https://github.com/consenlabs/token-profile/files/2630210/Token.zip)

**Comment by wenyanwang** [comment]
你好，请按照要求提交信息

为了加速显示进度，请尽可能向我们提供完善的项目资料，以及知名区块链媒体报道，包括但不限于以下内容，以便 imToken 团队更了解你们的项目。

团队背景：
项目基本情况:
媒体报道：
推荐用户转账所使用的 Gas 数量（没有提供，我们默认值 60000）
PR 示例：
 [https://github.com/consenlabs/token-profile/pull/1636](https://github.com/consenlabs/token-profile/pull/1636)

**Comment by EOCbox** [comment]
中文名：能量影盒
符号：EOC
合约地址0x7ab2174c7151cb84f91bb818e07a72a5420a37e
团队背景：能源盒EOC基金会于2018年在新加坡成立，平均拥有超过10年的互联网产品开发经验。它是国外早期研究区块的技术团队.EOC是致力于建立一个价值发现平台，用于连接交易平台，区块链公司和投资者。致力于构建世界领先的区块链电影应用程序
项目基本情况:能源视频盒EOC该基金会于2018年在新加坡成立.EOC基于Etifang ERC20网络的基本加密货币。总发行量为2600万件，是极为罕见的货币。 EOC可以在整个Etifang区块链网络中流通.EOC基于ERC20开发的分散式电影和电视应用程序。
媒体报道：
推荐用户转账所使用的 Gas 数量（没有提供，我们默认值 60000）

**Pull request closed without merging**
