### PR TITLE
UCT

### PR DESCRIPTION
**Pull request by wakakajp**
已经收录的交易所DCE：https://www.dce.cash

### CODE REVIEW

**Comment by devs86** [comment]
I see you have trouble updating tokens on github, do I need my services

**Comment by wakakajp** [comment]
> I see you have trouble updating tokens on github, do I need my services

Thanks,I was told that 'The Travis CI build failed' because of '0x957C7090C1e2bBAAE73780d657df8132D6f3dA9D.png in images dir, that capital and small letter isn't quite the same with 0x957c7090c1e2bbaae73780d657df8132d6f3da9d'.
I want to delete the image named '0x957C7090C1e2bBAAE73780d657df8132D6f3dA9D.png', but I cant't find it in images dir.

**Comment by wenyanwang** [comment]
你好，请重新拉取文件提交信息，谢谢。
为了加速显示进度，请尽可能向我们提供完善的项目资料，以及知名区块链媒体报道，包括但不限于以下内容，以便 imToken 团队更了解你们的项目。

团队背景：
项目基本情况:
媒体报道：
推荐用户转账所使用的 Gas 数量（没有提供，我们默认值 60000）
PR 示例：
 [https://github.com/consenlabs/token-profile/pull/1636](https://github.com/consenlabs/token-profile/pull/1636)

**Comment by wenyanwang** [comment]
Incorrect information submitted, please go through our guide and check again.

**Pull request closed without merging**
