### PR TITLE
Add EOT token.

### PR DESCRIPTION
**Pull request by Skyge**
官方公告：https://www.supereot.com/index/index/indexs.html

### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

**.json 及 .png 文件检查项**
- [x] logo 尺寸：120*120 px
- [x] logo 背景：透明
- [x] 代币有至少一笔成功的转账记录
- [x] 此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
- [x] .json 和 .png 文件名一致（包括大小写）

**项目资料：**

- 团队背景：Distributed Global基金和3个团队一百多名技术人员建立而成，有着非常专业的市值管理团队和技术团队。
- 项目基本情况：supereot简称EOT，通过DPoS机制和整体架构分片多链（Shard Chains）等改变现有交易网络用户和Gas费用上涨循环。解决了ETH很多的扩容问题，可扩展的多链网络.创新安全强大的3.0区块链公链平台.
- 媒体报道：https://i.bishijie.com/detail/1982438 
- Twitter: https://twitter.com/supereot
- 转账所需 Gas Limit（对 ERC-20 项目方）：60000

### CODE REVIEW

**Comment by Skyge** [comment]
@sfsy520 Hi, could you please check for this PR? If I do something wrong, please tell me and then I will make changes.

**Comment by Lumos-yiqun** [comment]
LOGO 不符合要求

**Comment by Skyge** [comment]
Okay, I will have a check.

**Comment by Skyge** [comment]
Ohhhh, it seems like the logo background is not transparent, sorry for that, I will change it later.

**Comment by Skyge** [comment]
@Lumos-yiqun  Hi, how about now?

**Comment by Skyge** [comment]
@sfsy520 Hi, I have uploaded the new logo, could you please have a check, Thanks!

**Comment by Skyge** [comment]
@sfsy520 Hi, I have uploaded the new logo, could you please have a check, Thanks!

**Comment by Lumos-yiqun** [comment]
抱歉，无法验证资料真实性，不予通过。可通过代币合约地址在 imToken 中添加此代币。

**Comment by Skyge** [comment]
@Lumos-yiqun Which information do you mean, let me have a check?

**Comment by Skyge** [comment]
@Lumos-yiqun @sfsy520 Hi, we are trying to do as you recommended, but we can not find our token by contract address in imtoken, and we are sure we have satisfied the following requirements:
- `please check if there is no successful transaction records`: https://etherscan.io/tx/0x19a34486c143756c9e6d949308d709d07c3b416db1205084d38f516f6b722bb0
- `please verify your contract information on Etherscan`: https://etherscan.io/address/0x9e8d7c41941503c485eaaeb06283998936bf8901#code

So could you please help us manually add it. Thanks a lot!

**Comment by Skyge** [comment]
I have realized the issue, thanks for your help. we can close this PR totally.

**Pull request closed without merging**
