### PR TITLE
Add ATHENA token

### PR DESCRIPTION
**Pull request by cdcdx**
### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

**.json 及 .png 文件检查项**
- [x] logo 尺寸：120*120 px
- [x] logo 背景：透明
- [x] 代币有至少一笔成功的转账记录
- [x] 此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
- [x] .json 和 .png 文件名一致（包括大小写）

**项目资料：**

官方公告：https://twitter.com/WalletPandoras/status/1143512485712056321
团队背景：Timur Gavrilov - CEO, Pandoras founder, investment professionals, former M&A and TMT Business Strategy Director, has a total asset valuation of over $95 million. Pavel completed a $250 million investment in Vestments, M&A and debt financing.
John Martin - CTO, With 10 years of experience as the founder and CEO of IT Summa, IT Summa is a 60-person DevOps company with offices in Russia and San Francisco, California.
Anton Vdovin - Core Development, Experienced full stack software developer and architect. Design a HA/FT solution for the web. Experience in software security, hiding, DDoS, and hacker mitigation. Deep participant in the EOS developer community, a core member of Scholar Testnet. A committed EOS believer and open source community contributor.

项目基本情况：Athena is a Pandoras Wallet token, "Pandoras" DAPP wallet is a decentralized mobile wallet, supporting multiple underlying token system, ATHENAitioning decentralized multi-chain wallet DAPP+, Currently,"Pandoras" wallet mainly focuses on asset management and builds a full-chain DApp application ecosystem +, through Pandoras Labs incubating massive DApp and multi-dimensional ecological cooperation to dig deep into the market and establish industry awareness.
媒体报道：https://www.criptotendencias.com/patrocinado/pandoras-centrandose-en-la-ecologia-descentralizada-de-las-dapps/
https://bitsionarys.com/pandoras-es-el-monedero-que-busca-lograr-un-ecosistema-global-para-incubacion-de-dapps-a-nivel-mundial/
收录的交易所：Findex / Newdex / Whaleex
转账所需 Gas Limit（对 ERC-20 项目方）：（默认为 60000）None

---

### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [x] logo dimensions: 120*120 px
- [x] logo background: Transparent
- [x] At least one transaction on the token contract
- [x] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [x] Same document name for both .json and .png (Including capitalization)

**Project background:**

Official announcement: https://twitter.com/WalletPandoras/status/1143512485712056321
Project team background: Timur Gavrilov - CEO, Pandoras founder, investment professionals, former M&A and TMT Business Strategy Director, has a total asset valuation of over $95 million. Pavel completed a $250 million investment in Vestments, M&A and debt financing.
John Martin - CTO, With 10 years of experience as the founder and CEO of IT Summa, IT Summa is a 60-person DevOps company with offices in Russia and San Francisco, California.
Anton Vdovin - Core Development, Experienced full stack software developer and architect. Design a HA/FT solution for the web. Experience in software security, hiding, DDoS, and hacker mitigation. Deep participant in the EOS developer community, a core member of Scholar Testnet. A committed EOS believer and open source community contributor.

Project basic information: Athena is a Pandoras Wallet token, "Pandoras" DAPP wallet is a decentralized mobile wallet, supporting multiple underlying token system, ATHENAitioning decentralized multi-chain wallet DAPP+, Currently,"Pandoras" wallet mainly focuses on asset management and builds a full-chain DApp application ecosystem +, through Pandoras Labs incubating massive DApp and multi-dimensional ecological cooperation to dig deep into the market and establish industry awareness.
Media publications: https://www.criptotendencias.com/patrocinado/pandoras-centrandose-en-la-ecologia-descentralizada-de-las-dapps/
https://bitsionarys.com/pandoras-es-el-monedero-que-busca-lograr-un-ecosistema-global-para-incubacion-de-dapps-a-nivel-mundial/
Tradeable exchanges: Findex / Newdex / Whaleex
Recommended Gas Limit (For ERC-20 project teams) for transaction: (Default is 60,000) None

### CODE REVIEW

**Comment by tstt** [comment]
https://github.com/consenlabs/token-profile/blob/master/tutorial/erc20-tutorial.zh-CN.md#%E8%B5%84%E6%96%99%E7%9A%84%E5%AE%8C%E6%95%B4%E5%92%8C%E5%87%86%E7%A1%AE

image

**Comment by cdcdx** [comment]
Hello, the ARHENA information is complete.

**Comment by athena-creator** [comment]
yes it's me.

**Comment by tstt** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 管理资产。

**Pull request merged**
