### PR TITLE
Create 0xFF6CDF357B8D4a9C2db4e4E4D56dc66D9C4D23c0.json

### PR DESCRIPTION
**Pull request by FTchain**
remove number 1 from FTCC token display on  im token.

### CODE REVIEW

**Comment by FTchain** [comment]
we are FT chain team ,we are develop FTCC token, now the token is displayed FTCC1 on im token, we need you help remove the number 1, thank.

**Comment by kaichen** [comment]
Please add more detail of your token. And you can attach the image as its logo.

**Comment by FTchain** [comment]
[飞天链.docx](https://github.com/consenlabs/token-profile/files/2067045/default.docx)

logo
[0xFF6CDF357B8D4a9C2db4e4E4D56dc66D9C4D23c0.txt](https://github.com/consenlabs/token-profile/files/2067051/0xFF6CDF357B8D4a9C2db4e4E4D56dc66D9C4D23c0.txt)

**Comment by FTchain** [comment]
any updates?

**Comment by makoshan** [comment]
你好，请根据我们的 [教程](https://github.com/consenlabs/token-profile/blob/master/README.md)，通过 PR 方式提交代币资料。

**Comment by makoshan** [comment]
Please update token information.

**Pull request closed without merging**
