### PR TITLE
Add ORA token

### PR DESCRIPTION
**Pull request by ORAChain**
### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：
**.json 及 .png 文件检查项**

* [x]  logo 尺寸：120*120 px
* [x]  logo 背景：透明
* [x]  代币有至少一笔成功的转账记录
* [ ]  此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
* [x]  .json 和 .png 文件名一致（包括大小写）

**项目资料补充：**

团队背景：
甲骨数链是由新加坡甲骨数链基金会发起的区块链数据库项目，团队发起人包括任职于联合国支持基金会大中华区董事的成功企业家Phil Paul，以及曾任职于中国商务部的现任香港区块链协会联合创始人兼共同主席石柱。此外，甲骨数链的开发团队由超过20位具有区块链公链项目丰富开发经验的技术人员组成。

项目基本情况：
甲骨数链的目标是建立一个高性能的数据库公链，全面支持Web3.0时代各种应用的数据库、文件存储需求。甲骨数链的经济体系采用双通证设计，通过权益通证和功能通证并行的双轨制维持稳定的网络使用成本。当前，甲骨数链已经开启测试，并支持部分应用的运行。此外，甲骨数链已经设计了完善的生态发展规划，将扶持优质的项目在甲骨数链上顺利开发、运行。

媒体报道：
https://www.lieyuncj.com/p/6568
http://8btc.com/forum.php?mod=viewthread&tid=274877&page=1#pid2014973
[https://www.shenliancaijing.com/portal/activity/activedetail.html?id=4430；](https://www.shenliancaijing.com/portal/activity/activedetail.html?id=4430%EF%BC%9B)
https://m.tuoniaox.com/news/p-308637.html?from=groupmessage
https://www.niubilai.com/index/information/content/id/55241/active/0
http://www.54daxiang.com/web/viewDetail.do?id=1413

收录的交易所：
悉尼数字货币交易所

转账所需 Gas Limit（对 ERC-20 项目方）：（默认为 60000）

### Please check the following to ensure a successful verification of Token Profile
**.json and .png document checklists**

* [x]  logo dimensions: 120*120 px
* [x]  logo background: Transparent
* [x]  At least one transaction on the token contract
* [ ]  For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
* [x]  Same document name for both .json and .png (Including capitalization)

**Project background details:**

Team background:
Oracle Data Chain is a blockchain database project initiated by Oracle Data Chain Foundation in Singapore. Team initiators include Phil Paul, a successful entrepreneur who is the director of the Foundation for the Support of the United Nations Greater China, and Zhu Shi, co-founder and co-chairman of the current Hong Kong Blockchain Association, who had served in the Chinese Ministry of Commerce. In addition, the IT development team for the Oracle Data Chain consists of more than 20 techn

### CODE REVIEW

**Comment by ORAChain** [comment]
### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：
**.json 及 .png 文件检查项**

* [x]   logo 尺寸：120*120 px
* [x]   logo 背景：透明
* [x]   代币有至少一笔成功的转账记录
* [ ]   此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
* [x]   .json 和 .png 文件名一致（包括大小写）

**项目资料补充：**

团队背景：
甲骨数链是由新加坡甲骨数链基金会发起的区块链数据库项目，团队发起人包括任职于联合国支持基金会大中华区董事的成功企业家Phil Paul，以及曾任职于中国商务部的现任香港区块链协会联合创始人兼共同主席石柱。此外，甲骨数链的开发团队由超过20位具有区块链公链项目丰富开发经验的技术人员组成。

项目基本情况：
甲骨数链的目标是建立一个高性能的数据库公链，全面支持Web3.0时代各种应用的数据库、文件存储需求。甲骨数链的经济体系采用双通证设计，通过权益通证和功能通证并行的双轨制维持稳定的网络使用成本。当前，甲骨数链已经开启测试，并支持部分应用的运行。此外，甲骨数链已经设计了完善的生态发展规划，将扶持优质的项目在甲骨数链上顺利开发、运行。

媒体报道：
https://www.lieyuncj.com/p/6568
http://8btc.com/forum.php?mod=viewthread&tid=274877&page=1#pid2014973
[https://www.shenliancaijing.com/portal/activity/activedetail.html?id=4430；](https://www.shenliancaijing.com/portal/activity/activedetail.html?id=4430%EF%BC%9B)
https://m.tuoniaox.com/news/p-308637.html?from=groupmessage
https://www.niubilai.com/index/information/content/id/55241/active/0
http://www.54daxiang.com/web/viewDetail.do?id=1413

收录的交易所：
https://trade.sdce.com.au/

转账所需 Gas Limit（对 ERC-20 项目方）：（默认为 60000）

### Please check the following to ensure a successful verification of Token Profile
**.json and .png document checklists**

* [x]   logo dimensions: 120*120 px
* [x]   logo background: Transparent
* [x]   At least one transaction on the token contract
* [ ]   For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
* [x]   Same document name for both .json and .png (Including capitalization)

**Project background details:**

Team background:
Oracle Data Chain is a blockchain database project initiated by Oracle Data Chain Foundation in Singapore. Team initiators include Phil Paul, a successful entrepreneur who is the director of the Foundation for the Support of the United Nations Greater China, and Zhu Shi, co-founder and co-chairman of the current Hong Kong Blockchain Association, who had served in the Chinese Ministry of Commerce. In addition, the IT development team for the Oracle Data Chain consists of more than 20 technicians with abundant development experience in blockchain public chain projects.

Current situation of the project:
The goal of Oracle Data Chain is to establish a high-performance database public chain, which fully supports the database and file storage requirements of various applications in the Web 3.0 era. The economic system of Oracle Data Chain adopts a dual-track design, and maintains stable network using cost through the dual-track system of equity token and functional token. At present, Oracle Data Chain’s test net has launched and supported some applications. In addition, Oracle Data Chain has designed an all-round ecological development plan, which will support the high-quality projects to develop and run on the Oracle Data Chain.

Media exposures:
https://www.lieyuncj.com/p/6568
http://8btc.com/forum.php?mod=viewthread&tid=274877&page=1#pid2014973
[https://www.shenliancaijing.com/portal/activity/activedetail.html?id=4430；](https://www.shenliancaijing.com/portal/activity/activedetail.html?id=4430%EF%BC%9B)
https://m.tuoniaox.com/news/p-308637.html?from=groupmessage
https://www.niubilai.com/index/information/content/id/55241/active/0
http://www.54daxiang.com/web/viewDetail.do?id=1413

Tradeable exchanges:
https://trade.sdce.com.au/

Recommended Gas Limit (For ERC-20 project teams) for transaction: (Default is 60,000)

**Comment by ORAChain** [comment]
json格式检验过，没看出问题在你来啊

**Comment by ORAChain** [comment]
json格式校验没问题，问题在哪里？

**Comment by tstt** [comment]
如果通不过机器人检查，说明 json 文件有问题，请自查（可参考教程中模版 json）

**Comment by ORAChain** [comment]
> 如果通不过机器人检查，说明 json 文件有问题，请自查（可参考教程中模版 json）

检查过很多遍了，复制别人的修改也不行，麻烦大神帮忙看看

**Comment by tstt** [comment]
json 中某些 link 如果为空，可以删掉。参考：https://github.com/consenlabs/token-profile/tree/master/eos-token

**Comment by ORAChain** [comment]
检查过json中没有空link，在工具中校验json是合法的

**Comment by tstt** [comment]
可能没说明白，建议是把空字段删除再试：
image

**Pull request merged**
