### PR TITLE
adding cpi token

### PR DESCRIPTION
**Pull request by alexanderanter**
Project team background:

Herbert Law
CEO
Herbert founded Crypto Price Index coin in 2019, after a long track record of delivering innovation in the burgeoning technology space.

Scotty Crandlemire
Co-Founder
Scotty is a serial inventor, business creator and philanthropist.

Jesse Christophel
Technology Advisor
Senior Systems Engineer with over 22 years of experience in the field and four years as an operations manager. Held senior positions at Expedia and Microsoft.

Project basic information:
Crypto Price Index is a new innovative way to easily track the top 200 cryptocurrencies by market capitalization. Like the Dow Jones Industrial Average, the CPI Index, alongside it’s native governance token the CPI token, provides an insight into the trading history of the leading blockchain projects.

Website : https://cpiindex.io/
Twitter: https://twitter.com/cpi_blockchain
Media publications:
https://www.howtotoken.com/career/how-to-quickly-check-the-crypto-market-condition-before-making-an-investment-decision/
https://cointelegraph.com/press-releases/emirati-royal-family-endorses-crypto-price-index-project-joins-board
https://markets.businessinsider.com/news/stocks/crypto-price-index-to-solve-for-rampant-crypto-market-volatility-with-token-tied-to-most-comprehensive-market-index-1028739958
https://blockchain.news/Post?id=crypto-price-index-predicted-to-revolutionize-the-cryptocurrency-market

Tradeable exchanges: No
Recommended Gas Limit for transaction: 95000

### CODE REVIEW

**Comment by sfsy520** [comment]
为确保资料提交的真实性，请在贵方官网或其他经过认证的社交媒体渠道发布公告，并将此公告链接附于「官方公告」。推荐文案：
#imToken# #1636# 我们正在完善 XXX 在 imToken 中的代币相关资料。完成后，大家可以在 imToken 里看到 logo，更方便地管理 XXX，同时能看到更多代币信息。
注：
* 1636 为 pr 序号，如 https://github.com/consenlabs/token-profile/pull/1636 的序号为 1636，这是帮助 imToken 判断 pr 真实性的关键。
* #imToken #1636 标签及其展示形式可自行调整。
* 若未提供「官方公告」，则无法显示代币信息。

**Comment by alexanderanter** [comment]
@sfsy520  https://medium.com/@cpi.index2019/cpi-added-to-imtoken-d4390210df46

**Comment by sfsy520** [comment]
请在官网添加跳转至官方公告的链接。

**Comment by alexanderanter** [comment]
Link to the announcement is now in the "MEDIA" section at the bottom of the website:
https://www.cpiindex.io/

**Comment by sfsy520** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 管理资产。

**Pull request merged**
