### PR TITLE
Adding MEXC

### PR DESCRIPTION
**Pull request by mhishami**
### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

**.json 及 .png 文件检查项**
- [x] logo 尺寸：120*120 px
- [x] logo 背景：透明
- [x] 代币有至少一笔成功的转账记录
- [x] 此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
- [x] .json 和 .png 文件名一致（包括大小写）

**项目资料：**

官方公告：
团队背景：
项目基本情况：
媒体报道：
收录的交易所：
转账所需 Gas Limit（对 ERC-20 项目方）：（默认为 60000）

---

### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [x] logo dimensions: 120*120 px
- [x] logo background: Transparent 
- [x] At least one transaction on the token contract
- [x] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [x] Same document name for both .json and .png (Including capitalization)

0x7DE2d123042994737105802D2abD0A10a7BdE276

**Project background:**

Official announcement: https://bitcointalk.org/index.php?topic=5162841.msg51747065#msg51747065
Project team background: https://mexc.life
Project basic information: 
MEXC is a unique creation of utility token for the Emergency Medical Services (EMS) industry. 
EMS or ambulance services provide pre-hospital medical care and transportation services to hospitals and medical facilities. The rise in demand for emergency medical services has led to the growth in the ambulance equipment market.
Our EMS products and services are based on new inventions, new innovations, and creativities in providing the best, and cost-effective products and solutions for the EMS industry. We have 25 inventions, 5 industrial designs, and 6 copyrights in the EMS industry.

Media publications:
Tradeable exchanges: DOBI Exchange
- https://www.dobiexchange.com/en/trade/mexc_eth
- https://www.dobiexchange.com/en/trade/mexc_btc
- https://www.dobiexchange.com/en/trade/mexc_usdt

Recommended Gas Limit (For ERC-20 project teams) for transaction: (Default is 60,000)

Token Symbol: MEXC
Token Contract Address: 0x7DE2d123042994737105802D2abD0A10a7BdE276
Etherscan Link: https://etherscan.io/token/0x7DE2d123042994737105802D2abD0A10a7BdE276

### CODE REVIEW

**Comment by mhishami** [comment]
DOBI Exchange:

https://www.dobiexchange.com/en/trade/mexc_eth
https://www.dobiexchange.com/en/trade/mexc_btc
https://www.dobiexchange.com/en/trade/mexc_usdt

**Comment by tstt** [comment]
about official annoucement, you can refer to this:
https://github.com/consenlabs/token-profile/blob/master/tutorial/erc20-tutorial.en.md#completeness-and-accuracy-of-the-information

image

**Comment by mhishami** [comment]
Hi,

We have added the announcement on the `news` section on our website at
https://mexc.life

Thanks for your cooperation.

Regards,
Hisham.

**Comment by tstt** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 管理资产。

**Pull request merged**
