### PR TITLE
IZIChain (IZI) update token profile

### PR DESCRIPTION
**Pull request by herryvu1702**
### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

**.json 及 .png 文件检查项**
- [ ] logo 尺寸：120*120 px
- [ ] logo 背景：透明
- [ ] 代币有至少一笔成功的转账记录
- [ ] 此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
- [ ] .json 和 .png 文件名一致（包括大小写）

**项目资料补充：**

团队背景：
项目基本情况：
媒体报道：
收录的交易所：
转账所需 Gas Limit（对 ERC-20 项目方）：（默认为 60000）

---

### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [ ] logo dimensions: 120*120 px
- [ ] logo background: Transparent
- [ ] At least one transaction on the token contract
- [ ] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [ ] Same document name for both .json and .png (Including capitalization)

**Project background details:**

Team background:
Current situation of the project:
Media exposures:
Tradeable exchanges:
Recommended Gas Limit (For ERC-20 project teams) for transaction: (Default is 60,000)

### CODE REVIEW

**Comment by tstt** [comment]
问题已在标签中注明，请补充和修改相关信息。

**Comment by herryvu1702** [comment]
Fixed all

**Comment by tstt** [comment]
image
项目资料仍然没有；代币 logo 重复提交了，去掉其中一个。

**Comment by herryvu1702** [comment]
> image
> 项目资料仍然没有；代币 logo 重复提交了，去掉其中一个。

**Project background details:**

Team background: 
1. Mr. Hakim Nguyen (Founder & CEO): https://www.linkedin.com/in/hakim-nguyen-10870016a/
2. Mr. Herry Vu (CTO): https://www.linkedin.com/in/herry-vu-189566149/
3. Mr. Tony Tran (Website Development): https://www.linkedin.com/in/tony-tran-76870516a/
4. Mr. Ryker Tran (Blockchain Engineer): https://www.linkedin.com/in/ryker-tran-88b6ba16a/
Current situation of the project: ICO done, begin distribute token
Media exposures: 
1. https://t.me/izichainnetwork
2. https://www.facebook.com/izichainnetwork/
3. https://twitter.com/chain_izi
4. https://bitcointalk.org/index.php?topic=5042873.new#new
Tradeable exchanges:
1. https://token.store/trade/IZI
2. https://coinplace.pro
3. https://www.tokenmom.com/exchange/IZI-WETH
Recommended Gas Limit (For ERC-20 project teams) for transaction: (Default is 60,000): 100,000

**Comment by tstt** [comment]
Your logo pr is repeated, delete the wrong one, we'll check.
image

**Pull request closed without merging**
