### PR TITLE
CADEOS.io将令牌合同帐户名更改为“ cadeositoken”

### PR DESCRIPTION
**Pull request by CADEOS**
项目背景：

CADEOS.io-去中心化的CAD.FILES和项目管理平台

官方公告：

https://twitter.com/CadeosI/status/1068175488659714048

项目团队背景：

https://www.linkedin.com/in/guillermo-galindo-saeta-749a2557
https://www.linkedin.com/in/jes%C3%BAs-moya-galindo-bb24861a
https://www.linkedin.com/in/javier-saeta-hidalgo

项目基本信息：

如今，对企业家和创造者的最大限制之一是昂贵的软件许可，并且借助CADEOS.io，我们希望通过消除分散式软件的问题来为每个人提供便利。在直观和用户友好的环境中，我们将使创建过程和产品发布变得负担得起且非常容易。
通过标记各种项目，我们的用户可以看到他们的想法和努力已成功实施。我们的平台将为那些因市场壁垒而停滞不前的聪明人带来机会。
从最初的草图到制造过程，用户都可以在我们的产品生命周期管理器（PLM）平台中监视设计状态。工厂，供应商和所有相关的第三方都将能够在我们的平台上查看您的报价请求（RFQ），并发送每个组件的制造价格。
借助CADEOS.io，您可以使用我们的分散式CAD软件来设计任何机械和电子组件，并在成千上万寻求最佳创意的投资者的注视下在我们的社区中进行推广。
CADEOS.io平台将托管来自数千个不同品牌的大型组件库，并将负责提供尽可能广泛的资源，以简化产品的组成。
通过创建您的供应商组合，您将获得最佳建议，并与全球任何行业的最佳专业人员直接交流。每个区域都有自己的交流渠道和聊天室。
通过在动态用户配置文件中进行的每次创建，您将为所有产品，3D模型，3D打印机零件，电子方案等增加价值，从而有利于投标和销售，这将在CADEOS.io平台上取得成功。您的工作将永远不会丢失或遗忘，并且会不时地使用我们的代币ADE重新估价。

媒体出版物：

https://koreos.io/News/412220
https://medium.com/cadeos-io
https://www.stateofthedapps.com/dapps/cadeos
https://t.me/cadeos
https://marketcap.one/es/m/ADE

可交易的交易所：

https://token.store/eos/trade/cadeositoken-ade-eos
https://newdex.io/trade/cadeositoken-ade-eos
https://findex.pro/trade/cadeositoken_ADE-eosio.token_EOS
https://eosdaq.com/exchange/ADE_EOS
https://mydex.win/

Project background:

CADEOS.io - DECENTRALIZED CAD.FILES & PROJECT MANAGEMENT PLATFORM

Official announcement:

https://twitter.com/CadeosI/status/1068175488659714048

Project team background:

https://www.linkedin.com/in/guillermo-galindo-saeta-749a2557
https://www.linkedin.com/in/jes%C3%BAs-moya-galindo-bb24861a
https://www.linkedin.com/in/javier-saeta-hidalgo

Project basic information:

Today one of the biggest constrains for entrepreneurs and creators are the expensive software licenses and, with CADEOS.io, we want to facilitate this process to everyone by getting rid of the problem with our decentralised software. We will make the creation process and product launch affordable and very easy within an intuitive and user friendly environment.
By tokenising all kind of projects our users can see their ideas and effort successfully implemented. Our platform would will bring an opportunity to those brilliant minds that are stopped by the market barriers.
From the first sketch to the manufacture process, the users can monitor the state of your design in our Product Lifecycle Manager (PLM) platform. Factories, suppliers and all the 3rd parties interested will be able to review your Request for Quotation (RFQ) in our platform and send the manufacture price for each component.
With CADEOS.io you can design any mechanical and electronic component with our decentralised CAD software and promote it in our Community, under the watchful eye of thousands of investors looking for the best idea.
CADEOS.io platform will host a large gallery of components from thousands of different brands and will be responsible of providing the most extensive resources as possible for an easy product composition.
By creating your portfolio of suppliers you will have the best advice and direct communication with the best professionals in any industry around the world. Each area will have their own communication channels and chatrooms.
With every creation within your dynamic user profile, you will add value to all your products, 3D models, 3D printer parts, electronic schemes, etc., favouring the bids and sales which will be a success in CADEOS.io Platform. Your work will never be lost or forgotten and will be revaluated from time to time with our token ADE.

Media publications:

https://koreos.io/News/412220
https://medium.com/cadeos-io
https://www.stateofthedapps.com/dapps/cadeos
https://t.me/cadeos
https://marketcap.one/es/m/ADE

Tradeable exchanges:

https://token.store/eos/trade/cadeositoken-ade-eos
https://newdex.io/trade/cadeositoken-ade-eos
https://findex.pro/trade/cadeositoken_ADE-eosio.token_EOS
https://eosdaq.com/exchange/ADE_EOS
https://mydex.win/

### CODE REVIEW

**Comment by CADEOS** [comment]
https://bigone.zendesk.com/hc/zh-cn/articles/360025716714-BigONE-已暂停-ADE-的充提服务

https://medium.com/cadeos-io/cadeos-io-call-to-every-exchanges-to-change-ade-token-contract-account-to-cadeositoken-6c048a9e811b

**Comment by CADEOS** [comment]
https://bigone.zendesk.com/hc/zh-cn/articles/360025716714-BigONE-已暂停-ADE-的充提服务

https://medium.com/cadeos-io/cadeos-io-call-to-every-exchanges-to-change-ade-token-contract-account-to-cadeositoken-6c048a9e811b

**Comment by sfsy520** [comment]
关于重名及修改合约
在 imToken 1.0 里，如果你的项目名称和其它项目重复，我们会在后面加数字，如 TFT1、TFT2、TFT3 等；如果你希望去掉数字，我们首先声明，这是一个非常危险的操作，修改代币信息后，代币会突然消失，容易引起用户恐慌，原则是对于持币人数多的项目，我们建议项目方推荐用户下载使用 imToken 2.0，imToken 2.0 通过代币合约地址来区分代币，所以不存在代币名称重复。

如需修改合约地址，需要项目方在社区发布修改合约公告。并在 GitHub 提交新的 PR，将旧合约 Logo 作去色处理（Photoshop 操作路径：图像 - 调整 - 去色），然后提交新的代币合约和 Logo，并把公告链接在 PR 下留言，我们会核实情况修改。

**Comment by CADEOS** [comment]
I don't understand, can you write me in english please ? Translators from Chinese are really bad. This is the 5º time i try to change this following your instruction. Logo was discolored and attached here. Our token changed contract announced was attached here, i don't know what do you need more, please try to help me !!!

**Comment by sfsy520** [comment]
Regarding Duplicated Token Names or Contract Amendment
In imToken 1.0, if duplicated token names are found, imToken team will add a number after the token name for the project, like TFT1, TFT2 etc. If you wish to remove the number, we need to claim, this is a very dangerous operation. Removing the number is not advisable, as amending the token name will cause the token to disappear from imToken display and may cause unnecessary panic among users. For tokens with many holders, we recommend the token project to suggest to your users, to download and use imToken 2.0, as imToken 2.0 distinguish tokens via contract address. Therefore, this mitigates the problem of duplicated token names.

If there are update requests due to contract amendment, follow the checklist:

make an official announcement for the upgrade of the contract
submit a new PR in GitHub:
desaturate the old logo (In Photoshop: image - adjustments - desaturate)
resubmit new token contract’s json and logo
share your announcement link under the comment section in the PR
imToken team will evaluate the situation.

**Comment by CADEOS** [comment]
Hello, 

PR in Github : 

https://github.com/CADEOS/ADE-TOKEN-CONTRACT

Oficial token contract name announce :

https://twitter.com/CadeosI/status/1147270518426525698
https://medium.com/cadeos-io/cadeos-io-call-to-every-exchanges-to-change-ade-token-contract-account-to-cadeositoken-6c048a9e811b

Attached here desaturated old logo. 

Here resubmited new token contract’s json and logo.

Is exactly all i shared all time. 

Please check. What do you need more?

**Comment by sfsy520** [comment]
I'm sorry, Logo doesn't meet the requirements. 120 px * 120 px

**Comment by CADEOS** [comment]
Fixed the icon size, now is 120px x 120px . Sorry so much for every inconveniences and huge thanks for your help !

**Pull request merged**
