### PR TITLE
add Ccvt token

### PR DESCRIPTION
**Pull request by hivebanks**
### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

**.json 及 .png 文件检查项**
- [x] logo 尺寸：120*120 px
- [x] logo 背景：透明
- [x] 代币有至少一笔成功的转账记录
- [x] 此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
- [x] .json 和 .png 文件名一致（包括大小写）

**项目资料：**

官方公告：
http://news.fnying.com/news/4B77E311-515D-BD12-A86B-0EF15B7B0233.html

团队背景：

CCVT团队于上海，是国内较早研究区块链领域的技术团队，并拥有丰富的开发经验；项目发起人袁浩（Arthur）。上海风赢网络科技有限公司 CEO。资深 程序员架构师。原乐享比特币创始人。曾任日本野村证券安全项目经理。创办过 中国程序员联盟。韩国国技院认证跆拳道黑带二段。门萨俱乐部成员。

项目基本情况：
CCVT 是一种基于以太坊的 ERC20 Token, 其固定发行量为 100 亿，并且 以递减的方式投放到各大社交平台，希望通过 Token 奖励使社交平台中的聊天 产生更多思维的碰撞，通过沟通创造更多的价值，同时吸引更多用户加入使用 CCVT 的社群。 CCVT 在初期是以 token 的形式被持有，在社群发展壮大之后，CCVT 会以 多种形式被消耗。公链将在随后被开发出来，这将是一个集合了信息互联网和价 值互联网的完全独立的公链，用户则可以用持有的 token 去交换公链上的币，并通过交流继续去获得公链上的奖励。

媒体报道：
金色财经 https://www.jinse.com/blockchain/349597.html
链路财经 https://www.linksfin.com/event/3023
陨石财经 http://www.yunshi24.com/newsletter/detail/55167.html

收录的交易所：FUBT

转账所需 Gas Limit（对 ERC-20 项目方）：60000

---

### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [x] logo dimensions: 120*120 px
- [x] logo background: Transparent
- [x] At least one transaction on the token contract
- [x] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [x] Same document name for both .json and .png (Including capitalization)

**Project background:**

Official announcement:

http://news.fnying.com/news/4B77E311-515D-BD12-A86B-0EF15B7B0233.html

Project team background:

The CCVT team is based in Shanghai and is an early technical team in the field of blockchain research and has extensive development experience; project leader Yuan Hao (Arthur). CEO of Shanghai Fenghui Network Technology Co., Ltd. Senior Programmer Architect. The original music enjoys the founder of Bitcoin. He used to be the security project manager of Nomura Securities in Japan. Founded the Chinese Programmers Alliance. The Korea National Institute of Technology has certified the second section of the Taekwondo Black Belt. Member of the Mensa Club.

Project basic information:

CCVT is an ERC20 Token based on Ethereum, with a fixed circulation of 10 billion, and is delivered to major social platforms in a declining manner. It is hoped that the Token reward will enable more chats in the chat on the social platform. Create more value while attracting more users to the community using CCVT. CCVT was initially held in the form of tokens, and after the community grew, CCVT would be consumed in many forms. The public chain will be developed later. This will be a completely independent public chain that integrates the information Internet and the value Internet. Users can use the tokens they hold to exchange coins on the public chain and continue to get public through communication. The reward on the chain.

Media publications:

Jinse https://www.jinse.com/blockchain/349597.html
linksfin https://www.linksfin.com/event/3023
yunshi24  http://www.yunshi24.com/newsletter/detail/55167.html

Tradeable exchanges:
Recommended Gas Limit (For ERC-20 project teams) for transaction: 60,000

### CODE REVIEW

**Comment by tstt** [comment]
文件名及 json 文件中的合约地址需做 checksum

**Comment by hivebanks** [comment]
> 文件名及 json 文件中的合约地址需做 checksum

已checksum，请查阅

**Comment by hivebanks** [comment]
> 文件名及 json 文件中的合约地址需做 checksum

已checksum，请查阅

**Comment by tstt** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 管理资产。

**Pull request merged**
