### PR TITLE
Create 0xd9267633aa3bcf2fa55ba8eebbc0487ae6eef5fb.json

### PR DESCRIPTION
**Pull request by galfen**
本次提交新增token logo

### CODE REVIEW

**Comment by jarifee** [comment]
ERROR! json file 0xfaaf0Ecfb3246902de6A2C77c5B114DA555695A3.json's links every field must be an url
npm ERR! Test failed.  See above for more details.

**Comment by zhen6939** [comment]
Sorry about that. I just fixed the CI failed at the master branch.
Please make a new commit to trigger the CI again.

**Comment by galfen** [comment]
ok

**Comment by galfen** [comment]
请问为什么关闭我们的请求？发自我的华为手机-------- 原始邮件 --------主题：Re: [consenlabs/token-profile] Create 0xd9267633aa3bcf2fa55ba8eebbc0487ae6eef5fb.json (#1049)发件人：Weli 收件人：consenlabs/token-profile 抄送：galfen ,Author Closed #1049.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/consenlabs/token-profile","title":"consenlabs/token-profile","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/consenlabs/token-profile"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #1049."}],"action":{"name":"View Pull Request","url":"https://github.com/consenlabs/token-profile/pull/1049#event-1745999950"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/consenlabs/token-profile/pull/1049#event-1745999950",
"url": "https://github.com/consenlabs/token-profile/pull/1049#event-1745999950",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [consenlabs/token-profile] Create 0xd9267633aa3bcf2fa55ba8eebbc0487ae6eef5fb.json (#1049)",
"sections": [
{
"text": "",
"activityTitle": "**Weli**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@wenyanwang",
"facts": [

]
}
],
"potentialAction": [
{
"targets": [
{
"os": "default",
"uri": "https://github.com/consenlabs/token-profile/pull/1049#event-1745999950"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 356857124\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by wenyanwang** [comment]
@galfen 按照正确的格式重新提交一个，谢谢。

**Pull request closed without merging**
