### PR TITLE
add DWCC token

### PR DESCRIPTION
**Pull request by dwcctoken**
### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

**.json 及 .png 文件检查项**
- [x] logo 尺寸：120*120 px
- [x] logo 背景：透明
- [x] 代币有至少一笔成功的转账记录
- [x] 此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
- [x] .json 和 .png 文件名一致（包括大小写）

**项目资料：**

团队背景：滴滴洗车团队囊括了来自于区块链+互联网+AI智能三大领域的顶级专家组合而成，团队成员履历丰功硕果，具体有来自于滴滴洗车香港华夏股份资深投资人、滴滴洗车平台联合创始人、互联网网红会创始人、海外顶尖媒体平台、全球顶尖华为云技术、全球一流运营团队联盟合作
项目基本情况：滴滴洗车是一个全新的电子商务营销S2B2C平台，滴滴洗车采取的是基于以太坊开发，实现区块链股权透明技术，最终达成洗车联盟公链DWCC的进阶。通过区块链技术将用户行为大数据权益归还给汽车用户，带领汽车用户进行行业革命，对用户行为的数据资产进行记账和公平分配。
媒体报道：
收录的交易所：比特QQ
转账所需 Gas Limit（对 ERC-20 项目方）：（默认为 60000）

---

### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [x] logo dimensions: 120*120 px
- [x] logo background: Transparent
- [x] At least one transaction on the token contract
- [x] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [x] Same document name for both .json and .png (Including capitalization)

**Project background:**

Project team background:DWCC team consists of top experts from the three areas of blockchain + Internet + AI intelligence. The team members have a lot of achievements, including the senior investors from DWCC Hong Kong Huaxia Co., Ltd. Co-founder of DWCC Platform, Founder of Internet Red Cross, Overseas Top Media Platform, Global Top Huawei Cloud Technology, Global First-Class Operation Team Alliance
Project basic information:DWCC is a brand new e-commerce marketing S2B2C platform. DWCC is based on the development of Ethereum, realizing the transparent technology of blockchain equity, and finally reached the advanced stage of the car wash alliance public chain DWCC. Through the blockchain technology, the user behavior big data rights are returned to the car users, leading the car users to carry out the industry revolution, accounting and fair distribution of the data assets of the user behavior.
Media publications:
Tradeable exchanges:bitqq
Recommended Gas Limit (For ERC-20 project teams) for transaction: (Default is 60,000)

### CODE REVIEW

**Comment by sfsy520** [comment]
请仔细阅读要求，并提供符合要求的PR
pr 中存在的问题已在标签中指出，请参考教程检查修改
教程链接：
https://github.com/consenlabs/token-profile#token-profile-guideline

**Comment by dwcctoken** [comment]
已修改DWCC项目的LOGO，并发布公告，
公告地址：http://www.dwcc.top/announcement.html

**Comment by sfsy520** [comment]
Logo不符合要求，请按要求修正

**Comment by dwcctoken** [comment]
我无法修改logo，请您指教一二

**Pull request closed without merging**
