### PR TITLE
Yest token

### PR DESCRIPTION
**Pull request by yes-ex**
### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

**.json 及 .png 文件检查项**
- [x] logo 尺寸：120*120 px
- [x] logo 背景：透明
- [x] 代币有至少一笔成功的转账记录
- [x] 此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
- [x] .json 和 .png 文件名一致（包括大小写）

**项目资料：**

官方公告：
团队背景：
项目基本情况：
媒体报道：
收录的交易所：
转账所需 Gas Limit（对 ERC-20 项目方）：（默认为 60000）

---

### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [ ] logo dimensions: 120*120 px
- [ ] logo background: Transparent
- [ ] At least one transaction on the token contract
- [ ] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [ ] Same document name for both .json and .png (Including capitalization)

**Project background:**

Official announcement:
Project team background:
Project basic information:
Media publications:
Tradeable exchanges:
Recommended Gas Limit (For ERC-20 project teams) for transaction: (Default is 60,000)

### CODE REVIEW

**Comment by sfsy520** [comment]
存在问题：
1.请丰富项目内容介绍
2.官方访问无效
3.请发布官方公告

**Comment by yes-ex** [comment]
Project background:

Official announcement:
https://twitter.com/LeeJack24827302/status/1189247144328384513
Project team background:
The Yesex team consists of more than 30 highly talented indivi-duals from different nationalities. More than half of the employees are Yest in class software and blockchain developers, while the other half are experienced professionals in their individual fields. 
All employees share the vision and are driven by the idea of shaping the future of the financial services industry. Yesex fosters an innovative corporate culture where new ideas are always embraced and achievements are immediately recognised. Yesex is growing rapidly and expanding its team. 
Project basic information:
Media publications:
YEST - Yesex Ecosystem Token will be issued by Yesex through an Initial Exchange Offering on the Yesex platform. YEST will be issued on the Ethereum Blockchain as an ERC20 token. An amount of 1 billion YEST will be created, never to be increased.
YEST will be listed and tradeable on the Yesex Global Exchange against the available fiat currencies as well as Bitcoin (BTC). Afterwards, YEST will be added to Yesex’s digital investment platform as well.

Recommended Gas Limit (For ERC-20 project teams) for transaction: 3000000
----------------------------------------------------------------------------------------------------
All the added content has been updated，please help me review it again, thank you very much!

**Comment by yes-ex** [comment]
> 存在问题：
> 1.请丰富项目内容介绍
> 2.官方访问无效
> 3.请发布官方公告
------------------------------------------------------------------------------------------------
Project background:

Official announcement:
https://twitter.com/LeeJack24827302/status/1189247144328384513
Project team background:
The Yesex team consists of more than 30 highly talented indivi-duals from different nationalities. More than half of the employees are Yest in class software and blockchain developers, while the other half are experienced professionals in their individual fields.
All employees share the vision and are driven by the idea of shaping the future of the financial services industry. Yesex fosters an innovative corporate culture where new ideas are always embraced and achievements are immediately recognised. Yesex is growing rapidly and expanding its team.
Project basic information:
Media publications:
YEST - Yesex Ecosystem Token will be issued by Yesex through an Initial Exchange Offering on the Yesex platform. YEST will be issued on the Ethereum Blockchain as an ERC20 token. An amount of 1 billion YEST will be created, never to be increased.
YEST will be listed and tradeable on the Yesex Global Exchange against the available fiat currencies as well as Bitcoin (BTC). Afterwards, YEST will be added to Yesex’s digital investment platform as well.

Recommended Gas Limit (For ERC-20 project teams) for transaction: 3000000
-----------------------------------------------------------------------------------------------

**All the added content has been updated，please help me review it again, thank you very much!**

**Comment by sfsy520** [comment]
请丰富项目内容介绍

**Comment by sfsy520** [comment]
非常抱歉，由于该PR长时间未更新，我们先关闭这个PR
如果仍需提交，请参考教程重新提交：
https://github.com/consenlabs/token-profile#token-profile-guideline

**Pull request closed without merging**
