### PR TITLE
Add MTE token

### PR DESCRIPTION
**Pull request by panxianhai**
官方公告
https://twitter.com/MeteoriteQT/status/1496849398302527491

团队背景：
The MTE team has several developers with over 10 years of Internet experience and has focused on blockchain development in recent years.

项目基本情况：
MTE is the only official token of Meteorite,  Meteorite is a decentralized quantitative strategy platform with full DAO management, a robust ecosystem, high-quality data services and a limited NFT series.

官网：https://www.mte.cool
Telegram：https://t.me/meteorite_official
Twitter：https://twitter.com/MeteoriteQT

媒体报道：
收录的交易所：
转账所需 Gas Limit：60000

### CODE REVIEW

**Comment by kaiko1203** [comment]
Parsing error in line 1:

**Comment by kaiko1203** [comment]
Please use the official Twitter @@imTokenOfficial

**Comment by panxianhai** [comment]
> Parsing error in line 1:

parsing error in json file？

**Comment by panxianhai** [comment]
> Please use the official Twitter @imTokenOfficial，Then send me the link

how can i do this？which link should I send a twitter?

**Pull request merged**
