### PR TITLE
Upload CMZ token

### PR DESCRIPTION
**Pull request by cryptomagz**
dear consenlabs, please accept my pull request for add CMZ token listed in im token. thank

### CODE REVIEW

**Comment by cryptomagz** [comment]
0x9715f0e15eafd789647827218e0263ebdb11d54a

**Comment by cryptomagz** [comment]
Please Accept my Request for upload CMZ token

**Comment by wenyanwang** [comment]
你好，已经添加。

**Comment by cryptomagz** [comment]
Thank you Master wenyanwang.

**Pull request merged**
