### PR TITLE
add 0x5D4232EAC1EA003a4dB87138585aA5078DeD2b10

### PR DESCRIPTION
**Pull request by 4stone**
增加ERC20合约0x5D4232EAC1EA003a4dB87138585aA5078DeD2b10

### CODE REVIEW

**Comment by kaichen** [comment]
Please attach your image as well.

**Comment by 4stone** [comment]
照片已提交，请审核

**Comment by 4stone** [comment]
@kaichen 多久可以确认生效

**Comment by makoshan** [comment]
请提供相关媒体报道和官方网站介绍

**Comment by 4stone** [comment]
http://www.zhongxuntv.com/news/97738.html

http://www.qixin.com/company/7394024f-2636-443b-8942-6822dac0963c?token=a48c7a2f9a44088eda12199b5d0d78a9&from=bkdt

**Pull request closed without merging**
