### PR TITLE
Daot Detail

### PR DESCRIPTION
**Pull request by DaotTrade**
Project background details:
DAOT Is Algorithmic & Blockchain Solutions for Crypto-Trading and Protect your Investments.

Team background:
Ramon Ostrander is an expert who started his career in 2016 in the field of exchange and is now the CEO at Daot trade

Richard William is a marketing and project manager in this project,he has started his career as a marketing in 2015

Clayton Thomas is a CTO who is an expert in his field, he is also the one who will make an application for our exchange,he is also a reliable programmer and has started a career from 2017

Media exposures: https://medium.com/@DAOTOfficial
Twitter: https://twitter.com/daottrade
Telegram: https://t.me/DAOTGlobal
Web: https://daot.trade/
Recommended Gas Limit (For ERC-20 project teams) for transaction: (Default is 60,000)

### CODE REVIEW

**Comment by tstt** [comment]
问题已在标签中注明，请参考教程修改。

教程链接：
https://github.com/consenlabs/token-profile#token-profile-guideline

**Comment by DaotTrade** [comment]
Update done

**Comment by tstt** [comment]
https://github.com/consenlabs/token-profile/blob/master/tutorial/erc20-tutorial.zh-CN.md#%E5%85%B7%E4%BD%93%E5%A6%82%E4%BD%95%E6%93%8D%E4%BD%9C

image

**Comment by DaotTrade** [comment]
verified :  https://twitter.com/Daottrade/status/1144710004835926016

**Comment by tstt** [comment]
image

**Pull request closed without merging**
