### PR TITLE
Add logo png file for holo host.

### PR DESCRIPTION
**Pull request by nifflerfox**
Contract address:
0x6c6ee5e31d828de241282b9606c8e98ea48526e2

Official website:
http://holo.host/

### CODE REVIEW

**Comment by makoshan** [comment]
Please provide more info about the token.

**Comment by nifflerfox** [comment]
Important information already in your database, just logo image missed.

**Comment by nifflerfox** [comment]
管理员，您要补充的详细信息早就入库了，唯独缺少Logo，我补充了Logo，不需要其他信息

**Comment by nifflerfox** [comment]
@kaichen 管理员你帮合并一下，谢谢

**Pull request merged**
