### PR TITLE
Add MBH token

### PR DESCRIPTION
**Pull request by Jame286**
Official announcement:  http://mbhcoin.xyz/
Project team background:
The MBH project team has a very experienced team of senior experts, and the team members have many years of experience in the blockchain industry. The MBH project team has five core members, and dozens of excellent blockchain experts and development engineers are joining our team.Founder: Steven——Blockchain serial entrepreneurs have extensive operational experience in digital asset management and have obtained double degrees in engineering and economics. Focus and focus on the research of the Internet finance industry and mutual financial project investment, and have in-depth research on blockchain financial projects.
Project basic information:
MBH is committed to promoting the development and improvement of the distributed financial DeFi ecosystem. Based on the three major businesses of banking, securities and insurance in the traditional financial sector, it introduces the modern financial troika into the blockchain field to create on-chain finance and build efficient Operating distributed financial DeFi ecological infrastructure. MBH will be used in a wealth of distributed financial application scenarios such as asset tokenization, prediction markets, securities, stable coins, financial derivatives, lending, payment, data storage, insurance, etc., for the financial ecosystem including banks, securities, insurance, etc. Provide innovative solutions to the pain points in Let participants in the industrial chain of financial financing, deposits and loans, derivatives, investment management, trading and payment, feel the value of blockchain technology, make blockchain smart contracts more grounded and more in line with business rules, and build reality The bridge from the world to the blockchain world provides better support for distributed financial (DeFi) services.
Recommended Gas Limit (For ERC-20 project teams) for transaction:  60,000

### CODE REVIEW

**Comment by sfsy520** [comment]
请至少保证存在一笔转账记录

**Comment by Jame286** [comment]
已做了转账记录，麻烦重新审核一下，谢谢!

**Comment by Jame286** [comment]
@sfsy520 ，你好，已做了转账记录，麻烦重新审核一下吧，谢谢!

**Comment by sfsy520** [comment]
非常抱歉，由于该PR长时间未更新，我们先关闭这个PR
如果仍需提交，请参考教程重新提交：
https://github.com/consenlabs/token-profile#token-profile-guideline

**Pull request merged**
