### PR TITLE
0x9715f0e15eafd789647827218e0263ebdb11d54a.json

### PR DESCRIPTION
**Pull request by cryptomagz**
Cryptomagz is a platform for the future of funding that 
is built on trust and reputation with the ERC20 Ethereum ecosystem.

### CODE REVIEW

**Comment by kaichen** [comment]
Please attach the token logo image.

**Comment by cryptolordproject** [comment]
Cryptomagz Logo
Link: https://cryptomagz.info/cryptomagz.png

**Comment by cryptomagz** [comment]
Cryptomagz Logo
Link: https://cryptomagz.info/cryptomagz.png

**Comment by makoshan** [comment]
Please follow our tutorial and submit the Logo to the imges folder:
https://github.com/consenlabs/token-profile/blob/master/README.md

**Comment by cryptomagz** [comment]
Cryptomagz Logo

Please find our Logo by link : https://cryptomagz.info/cmzlogo.png


Best Regards
Admin
Cryptomagz

**Comment by makoshan** [comment]
The token logo needs to named as same as the json file.

**Comment by cryptomagz** [comment]
okay sir. thank for your info

**Comment by makoshan** [comment]
Please check the [CI error](https://travis-ci.org/consenlabs/token-profile/builds/397606900?utm_source=github_status&utm_medium=notification).

**Comment by cryptomagz** [comment]
Please cheek, i has been reslove

**Pull request closed without merging**
