### PR TITLE
Added AMLT

### PR DESCRIPTION
**Pull request by rad-p**
### 为确保 Token Profile 的顺利通过，务必逐一确保以下检查项并补充项目资料：

**.json 及 .png 文件检查项**
- [ ] logo 尺寸：120*120 px
- [ ] logo 背景：透明
- [ ] 代币有至少一笔成功的转账记录
- [ ] 此项对于 ERC-20 项目方：合约地址有大小写（做 checksum）
- [ ] .json 和 .png 文件名一致（包括大小写）

**项目资料：**

官方公告：
团队背景：
项目基本情况：
媒体报道：
收录的交易所：
转账所需 Gas Limit（对 ERC-20 项目方）：（默认为 60000）

---

### Please check the following to ensure a successful verification of Token Profile

**.json and .png document checklists**
- [+ ] logo dimensions: 120*120 px
- [ +] logo background: Transparent
- [+ ] At least one transaction on the token contract
- [+ ] For ERC-20 project teams: Upper and lower capitalized alphabets in token address (For checksum purposes)
- [ +] Same document name for both .json and .png (Including capitalization)

**Project background:**

Official announcement: https://twitter.com/AMLT_Token/status/1129014567412129797
Project team background: https://www.coinfirm.com/team/all
Project basic information: “The fuel for the AMLT Network and the industry leading Coinfirm AML Platform, AMLT tokens are not only the reward for Network Members but preferred choice of payment and access for Coinfirm solutions and services used by over 100 entities across blockchain and financial industries.
Media publications: https://blog.coinfirm.com
Tradeable exchanges: https://coinmarketcap.com/currencies/amlt/#markets
Recommended Gas Limit (For ERC-20 project teams) for transaction: (Default is 60,000)

### CODE REVIEW

**Comment by tstt** [comment]
image

and provide valid official announcement link

**Comment by rad-p** [comment]
> image
> 
> and provide valid official announcement link

Our blog is a place for announcements.

**Comment by tstt** [comment]
the problems have been figured out in the label, please refer to the tutorial to check and solve these problems.

about "auto check failed", you can see details here:
image

**Comment by tstt** [comment]
the two problems remain, refer to the tutorial to fix it

**Comment by tstt** [comment]
pls attach the official annoucement link here

**Comment by rad-p** [comment]
> pls attach the official annoucement link here

Can you please explain what exactly announcement link?

Is it the very first announcement about ICO start
or 
Is it the link to blog\forum where we announcements are posted ?

**Comment by tstt** [comment]
image

**Comment by rad-p** [comment]
> pls attach the official annoucement link here

https://twitter.com/AMLT_Token/status/1129014567412129797

**Comment by rad-p** [comment]
@tstt I have attached the announcement link above as commnet and in description.

**Comment by tstt** [comment]
欢迎在社区中推荐用户使用 imToken 2.0 管理资产。

**Pull request merged**
